### ISSUE TITLE
[BUG] @prizm-ui/components - Ошибка при запуске проекта, после установки v3.4.0

### ISSUE THREAD

**Issue by Anna-Prokhorova** [zyfra/Prizm#1001]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Скрин проблемы

![image](https://github.com/zyfra/Prizm/assets/59168625/8ad4929c-8093-4028-8b54-33c8277a9990)

### Описание проблемы

Попытались перейти на v3.4.0 с v3.0.0
Установка прошла успешно, но при запуске проекта возникает ошибка

**Comment by ZurabDev** [comment]
Сранно lodash-es не установился, попробуйте устанивить вручную
