### ISSUE TITLE
[BUG] @prizm-ui/components/tabs - Неправильное поведение события activeTabIndexChange

### ISSUE THREAD

**Issue by RoxVell** [zyfra/Prizm#1003]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

Tabs

### Версия

Операционная ситема:

`MacOs Sonoma 14.0`

Браузер:

`Google Chrome Версия 117.0.5938.149 (Официальная сборка), (arm64)`

NodeJS:

```
➜ node --version
v16.20.1
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components@3.3.0
```

```
➜ npm ls @angular/core

├─┬ @angular/animations@16.2.9
│ └── @angular/core@16.2.9 deduped
├─┬ @angular/cdk@16.2.8
│ └── @angular/core@16.2.9 deduped
├─┬ @angular/common@16.2.9
│ └── @angular/core@16.2.9 deduped
├─┬ @angular/compiler@16.2.9
│ └── @angular/core@16.2.9 deduped
├── @angular/core@16.2.9
├─┬ @angular/forms@16.2.9
│ └── @angular/core@16.2.9 deduped
├─┬ @angular/platform-browser-dynamic@16.2.9
│ └── @angular/core@16.2.9 deduped
├─┬ @angular/platform-browser@16.2.9
│ └── @angular/core@16.2.9 deduped
├─┬ @angular/router@16.2.9
│ └── @angular/core@16.2.9 deduped
├─┬ @ngx-translate/core@14.0.0
│ └── @angular/core@16.2.9 deduped
├─┬ @prizm-ui/components@3.1.0
│ ├── @angular/core@16.2.9 deduped
│ ├─┬ @ng-web-apis/common@3.0.3
│ │ └── @angular/core@16.2.9 deduped
│ ├─┬ @ng-web-apis/intersection-observer@3.1.2
│ │ └── @angular/core@16.2.9 deduped
│ ├─┬ @ng-web-apis/mutation-observer@3.0.1
│ │ └── @angular/core@16.2.9 deduped
│ ├─┬ @ng-web-apis/resize-observer@3.0.3
│ │ └── @angular/core@16.2.9 deduped
│ └─┬ ngx-mask@16.2.6
│   └── @angular/core@16.2.9 deduped
├─┬ @prizm-ui/core@3.1.0
│ └── @angular/core@16.2.9 deduped
├─┬ @prizm-ui/helpers@3.1.0
│ └── @angular/core@16.2.9 deduped
├─┬ @prizm-ui/i18n@3.1.0
│ └── @angular/core@16.2.9 deduped
├─┬ @prizm-ui/icons@3.1.0
│ └── @angular/core@16.2.9 deduped
├─┬ @prizm-ui/theme@3.1.0
│ └── @angular/core@16.2.9 deduped
├─┬ angular-split@16.2.1
│ └── @angular/core@16.2.9 deduped
├─┬ ngx-quill@22.1.0
│ └── @angular/core@16.2.9 deduped
└─┬ single-spa-angular@9.0.1
  └── @angular/core@16.2.9 deduped
```

### Проект в котором используется Prizm

marketplace

### Описание проблемы

Есть проблема следующего характера:
Перед тем, как компонент табов удаляется из dom-дерева (скрытие элемента по условию, переход на другую страницу)  или меняются сами табы событие activeTabIndexChange эмитит лишние события.

Шаги воспроизведения:

1. Перейти по адресу [stackblitz](https://stackblitz.com/edit/angular-sppqkh?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp-routing.module.ts)
2. Скрыть элемент нажав на кнопку "Change" или поменять список табов, нажав на кнопку "Change tabs"
3. Итог: в консоли выводятся изменение индекса активного таба: "1 2 3". При этом результат события также зависит от того, какой таб в данный момент активен (например, если сначала кликнуть на таб "Вкладка 3", а потом скрыть табы, то в консоли увидим всего 1 лишнее срабатывание).

**Comment by ickisIckis** [comment]
@alexhawkins94, нужно проверить в 3.11.1, вероятно исправлено
