### ISSUE TITLE
[BUG] prizm/components - Нельзя задать высоту для SideBar

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#101]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[Accordion](http://zds.zyfra.com/components/accordion)

### Версия

1.0.0-beta.26

### Описание проблемы

Комопнент SideBar не испоьзует высоту, указанную в параметрах PrizmDialogBaseOptions.

_Шаги воспроизведения_:

Вызвать откртие SideBar на странице
Указать в PrizmDialogBaseOptions.height любую высоту

**Comment by ZurabDev** [comment]
высота используется при позиции снизу или сверху

**Comment by badeevdm** [comment]
> высота используется при позиции снизу или сверху

Спасибо, частично это решило проблему, но всплыла другая. Высота применятся два раза, на блоке .z-overlay-wrapper и компоненте <prizm-sidebar>

![image](https://user-images.githubusercontent.com/48792714/227545083-0d8aea57-ee32-4ff8-a5bb-90fe1bf5bef7.png)

**Comment by ZurabDev** [comment]
<img width="472" alt="CleanShot 2023-03-29 at 15 53 58@2x" src="https://user-images.githubusercontent.com/75216044/228541575-3ff61752-9b71-48a5-948c-2cba9ac821e2.png">

Спс. Исправили. Будет доступно в 28 версии

**Comment by ZurabDev** [comment]
Просьба проверить и закрыть тикет
