### ISSUE TITLE
[FEATURE] @prizm-ui/components - `PrizmDataListComponent` has no borders when used without DropdownHost

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#1027]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

[`PrizmDataListComponent`](https://github.com/zyfra/Prizm/blob/main/libs/components/src/lib/components/data-list/data-list.component.ts)

### Версия

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 3.4.0
```

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/2631748/feb8b644-b75e-4032-99fd-dc3ff205492a)

### Воспроизведение проблемы

просто вставляем PrizmDataList в разметку

### Описание проблемы

Разрабатываем кастомный компонент типа меню (по аналогии с выпадающим списком `PrizmInputSelect`, но не контрол формы)

После изменений https://github.com/zyfra/Prizm/commit/e411daa916e1215498441a2391df7ab8b5883699 у компонента `PrizmDataList` нет бордера, т.к. правила описанные на https://github.com/zyfra/Prizm/blob/792b3c7aa8f4e11dde894613e015b9efd4063592/libs/components/src/lib/components/data-list/data-list.component.less#L14-L17 перекрывают `border`, но соответствующие переменные не имеют значений по-умолчанию.

P.S. (есть тривиальный воркэраунд)

P.P.S. во многих местах [используется](https://github.com/zyfra/Prizm/blob/792b3c7aa8f4e11dde894613e015b9efd4063592/libs/components/src/lib/components/dropdowns/select/input-select.component.html#L92C9-L92C45) `dropdownhost[style.--prizm-data-list-border]="0" > datalist`, возможно имеет смысл убрать бордер по умолчанию у DropdownHost, т.к. предполагается его использование с произвольным контентом где у пользователя должно быть больше контроля над отображением (в т.ч. границ). В этом случае не придется повсеместно "насильно" отключать двойной бордер у data-list.

**Comment by ickisIckis** [comment]
@PrizmDS, рассмотреть возможность сделать это настраиваемым параметром

**Comment by PrizmDS** [comment]
Да, можно.

**Comment by AleksandrSibiakov** [comment]
@PrizmDS check comment above, please
