### ISSUE TITLE
[Feature] Отображение хинта в селекте если значение не отображено полностью

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#1030]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[InputSelect](https://prizm.site/components/input-select)

### Предложение

Есть потребность отображать хинты с указанными значениями у селектов, если значение не отображается полностью (не вмещаются в видимую область контрола). Такое было уже сделано для текстовых полей в https://github.com/zyfra/Prizm/issues/615 .

**Comment by ickisIckis** [comment]
Должно войти в версию 3.5.0: https://github.com/zyfra/Prizm/issues/984
