### ISSUE TITLE
[BUG] @prizm-ui/components - ResizeObserverModule - не собирается пайплайн приходится ставить доп зависимости когда используешь призм

### ISSUE THREAD

**Issue by stepandr** [zyfra/Prizm#1033]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [x] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:
$ node -v
v16.16.0
$ npm -v
9.6.6

### Проект в котором используется Prizm

Несколько в ЦИП

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/11865854/a00a8d4d-dbf6-48a2-8a1e-fa08acd3f83b)

### Воспроизведение проблемы
Установил призм и пайплайн не собирается без правок что описал

### Описание проблемы

"@prizm-ui/components": "^1.4.0",
    "@prizm-ui/core": "^1.4.0",
    "@prizm-ui/helpers": "^1.4.0",
    "@prizm-ui/i18n": "^1.4.0",
    "@prizm-ui/icons": "^1.4.0",
    "@prizm-ui/theme": "^1.4.0",

Вот без этого что ниже билд не соберется вообще.

npm i @ng-web-apis/common@^2.0.0 @ng-web-apis/intersection-observer@^3.0.0 @ng-web-apis/resize-observer@^1.0.3 ngx-mask@14.2.4 lodash-es --save-dev  --legacy-peer-deps --force

"@prizm-ui/components": "^2.3.0",
    "@prizm-ui/core": "^2.3.0",
    "@prizm-ui/helpers": "^2.3.0",
    "@prizm-ui/i18n": "^2.3.0",
    "@prizm-ui/icons": "^2.3.0",
    "@prizm-ui/theme": "^2.3.0",

Вот без этого не поставить 

npm i @ng-web-apis/common@^2.0.0 @ng-web-apis/intersection-observer@^3.1.6 @ng-web-apis/resize-observer@^2.1.0 ngx-mask@15.1.5 lodash-es --save-dev  --legacy-peer-deps --force

Причем такая фигня на всех версиях призма если собираешь зависимости на windows и потом они в Linux тоже не собираются.

В проекте используется npm i --legacy-peer-deps --force 
Для обычной установки

Если собирать на макбуке то такой проблемы нет. 

Прошу пофиксить, достало очень сильно.

**Comment by ZurabDev** [comment]
Принято на этот спринт
