### ISSUE TITLE
[Feature] Фиксированная позиция для колонки в таблице

### ISSUE THREAD

**Issue by ickisIckis** [zyfra/Prizm#104]
### Библиотека

- [ ] `@prizm-ui/core`
- [X] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

Table

### Предложение
Сейчас в разработке очень широкая табличка, часть данных которой уходит в горизонтальный скролл. 
Для таких случаев было бы здорово иметь возможность зафиксировать на месте произвольное количество первых слева колонок для удобного просмотра данных.

**Comment by ZurabDev** [comment]
<img width="527" alt="CleanShot 2023-03-31 at 04 49 06@2x" src="https://user-images.githubusercontent.com/75216044/229002340-91194519-5c14-4ed3-a714-4276e433b318.png">
Добавлено. Будет в 28 версии

**Comment by ZurabDev** [comment]
Просьба проверить и закрыть тикет
