### ISSUE TITLE
[Int] Витрина. В темной теме скролл на странице сливается с фоном страницы

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1045]
-Включить темную тему
-Перейти к примерам Table
-Начать скроллить страницу с примерами
ФР: скролл становится незаметным как только он доходит до части страницы с темным фоном
ОР: скролл должен оставаться заметным 

![image](https://github.com/zyfra/Prizm/assets/122870313/13bda7c1-7eb2-4528-8695-ed6e5bc28f17)
![image](https://github.com/zyfra/Prizm/assets/122870313/02d61d4f-cb7c-4286-be69-b5768941d96f)

**Comment by ickisIckis** [comment]
Fixed indirectly

**Comment by alexhawkins94** [comment]
fixed
