### ISSUE TITLE
[Int] Cron. Rнопка копирования выражения и hr варианта остается в active state после нажатия

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1049]
-Перейти в cron
-Выбрать любые компоненты выражения
-Нажать кнопку копирования выражения и hr 
ФР: после нажатия кнопка остается в active state
ОР: после нажатия кнопка должна становиться default state
![image](https://github.com/zyfra/Prizm/assets/122870313/82907b67-605c-48d2-b26f-105625e0070d)

**Comment by ickisIckis** [comment]
Не воспроизводится на актуальных версиях 4.3.1 и 3.13.2
