### ISSUE TITLE
[Int] Carousel as input. Поправить отрисовку кнопки очистки при переключении между пустым и не пустым значением в карусели 

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1050]
если есть пустое значение, то при переключении между ним и неПустым значением случается некрасивая отрисовка кнопки очистки. видно как появляется сперва value затем кнопка и value как бы сдвигается

-Перейти в пример Carousel as input
-Сделать одно из значений пустым
-Переключиться между пустым и не пустым значением
ФР: при переключении на непустое значение кнопка очистки отрисовывается с задержкой. сперва появляется value, затем кнопка очистки и происходит сдвиг value влево. Выглядит некрасиво
ОР: корректная отрисовка кнопки очистки в этом случае - не должно быть сдвига value влево или задержки отрисовки

![chrome_WUpxzXVSG9](https://github.com/zyfra/Prizm/assets/122870313/7476e731-c2aa-4e7e-a462-aa85666b496f)

**Comment by ickisIckis** [comment]
@alexhawkins94 проверить с mr от @AleksandrSibiakov

**Comment by alexhawkins94** [comment]
больше не воспроизводится
проверено на 4.7 и 5.2

**Comment by alexhawkins94** [comment]
не воспроизводится в https://github.com/zyfra/Prizm/pull/2079
