### ISSUE TITLE
[Int] Skeleton. При активном скелетоне остаются границы от компонентов + поправить заливку в short режиме

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1055]
У toogle  и card отображаются границы при активном скелетоне
![image](https://github.com/zyfra/Prizm/assets/122870313/5100192c-774e-48a0-93d3-076286686f0b)

У toogle при активном скелетоне и short режиме заливка частично не отображается
![image](https://github.com/zyfra/Prizm/assets/122870313/7881f3e5-251b-4721-8d09-446cd54c31f5)

**Comment by ickisIckis** [comment]
> нужно проверить на актуальных версиях 3 и 4

проверить актуальность актуальности

**Comment by alexhawkins94** [comment]
больше не воспроизводится
проверено на 4.7 и 5.2
