### ISSUE TITLE
[Int] InputDateTimeRange. При появлении маски ввода кнопки внутри инпута сдвигаются вправо

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1058]
При появлении маски ввода кнопки внутри инпута сдвигаются вправо

-установить required = true, forceclear = true
-вызвать срабатывание валидации чтоб появился индикатор в инпуте
-сделать клик по инпуту
ФР: появляется маска ввода, при ее появлении кнопки и индикатор сдвигаются вправо
ОР: у кнопок и индикатора и иконок внутри инпута должно быть статичное положение при появлении маски ввода - не должно быть сдвигов

![chrome_NuW00tsPMR](https://github.com/zyfra/Prizm/assets/122870313/37ac5b68-3672-4399-ae35-6c7fcfec84d2)

**Comment by ickisIckis** [comment]
требуется проверить на актуальных версиях

**Comment by ZurabDev** [comment]
Не воспроизводится на 5
https://github.com/user-attachments/assets/686d219a-fb3f-46e6-aed5-8087d915eb86

**Comment by alexhawkins94** [comment]
на 4.7 5.2 не воспроизводится
