### ISSUE TITLE
[BUG] prizm/components - в документации не указаны обязательные пакеты для установки для успешного запуска

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#106]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [x] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

prizm

### Версия

Операционная ситема:

`Windows 11`

```
➜ node --version
v14.19.3
```

Dependencies:

```
➜ npm ls @prizm-ui/zyfra-components

@prizm-ui/zyfra-components 1.0.0-beta.27
```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Описание проблемы

Выполняю установку Prizm по шагам в документации. Сборка проекта выдает ошибки об отсутствии необходимых макетов для успешной сборки

./node_modules/@prizm-ui/components/fesm2015/prizm-ui-components.js:9:0-90 - Error: Module not found: Error: Can't resolve '@ng-web-apis/common' in 'C:\projects\zui-app-datalink\node_modules\@prizm-ui\components\fesm2015'

./node_modules/@prizm-ui/components/fesm2015/prizm-ui-components.js:10:0-51 - Error: Module not found: Error: Can't resolve '@ng-web-apis/resize-observer' in 'C:\projects\zui-app-datalink\node_modules\@prizm-ui\components\fesm2015'

./node_modules/@prizm-ui/components/fesm2015/prizm-ui-components.js:19:0-31 - Error: Module not found: Error: Can't resolve 'ngx-mask' in 'C:\projects\zui-app-datalink\node_modules\@prizm-ui\components\fesm2015'

./node_modules/@prizm-ui/components/fesm2015/prizm-ui-components.js:24:0-107 - Error: Module not found: Error: Can't resolve '@ng-web-apis/intersection-observer' in 'C:\projects\zui-app-datalink\node_modules\@prizm-ui\components\fesm2015'

в документации обязательность установки данных пакетов не указана. 

_Шаги воспроизведения_:

1. npm i @prizm-ui/core @prizm-ui/theme @prizm-ui/components
2. добавить модуль PrizmTabsModule(например) в module проекта
3. собрать проект

**Comment by irustm** [comment]
Это указано в peerDependencies к каждой версии

https://registry.npmjs.org/@prizm-ui/components

необходимости устанавливать вручную нет, автоматом все должно быть

**Comment by irustm** [comment]
не, не так, там сложнее

- before 3.0: are always installed if missing, and raise an error if multiple incompatible versions of the dependency would be used by different dependencies.
- expected to start on 3.0 (untested): give a warning if missing on npm install, and you have to solve the dependency yourself manually. When running, if the dependency is missing, you get an error (mentioned by @nextgentech) This explains it nicely: https://flaviocopes.com/npm-peer-dependencies/
- in version 7 peerDependencies are automatically installed unless an upstream dependency conflict is present that cannot be automatically resolved

**Comment by AntonGrekov** [comment]
Аналогичная ситуация у меня, при чем как на 14-ой node'e и 6-ом npm'e, так и на 16 и 18 ноде и 8.19.3 npm-e

````sh
$ node -v && npm -v
v18.13.0
8.19.3
````

peerDeps'ы не ставятся. Приходится в ручную их добавлять. Помимо этого 
```sh
$ ng add  @prizm-ui/install
````
не устанавливает все необходимые пакеты, чтобы PrizmUiRootModule собрался. В ручную добавлял ещё 

````json
    "@prizm-ui/icons": "^1.0.0-beta.31",
    "@prizm-ui/theme": "^1.0.0-beta.31",
    "@prizm-ui/i18n": "^1.0.0-beta.31",
````

только после этого всё собралось.

**Comment by ZurabDev** [comment]
Начиная с npm версии 7, установка peerDependencies стала происходить автоматически по умолчанию. Если вы используете npm версии 7 или выше, вам не нужно выполнять дополнительных действий для автоматической установки peerDependencies.

Однако, если вы используете npm версии 6 и хотите, чтобы peerDependencies устанавливались автоматически, вы можете воспользоваться сторонним пакетом npm-install-peers. Вот как это сделать:

Установите npm-install-peers глобально, выполнив следующую команду:
```npm install -g npm-install-peers```

Перейдите в каталог вашего проекта и выполните команду:
```npm-install-peers```

**Comment by AntonGrekov** [comment]
@ZurabDev Я же написал в сообщении, что с нпм версией 8 не устанавливаются peerDeps все равно.

**Comment by ZurabDev** [comment]
Обновим схематикс и @ng-web-api перенес в dependencies
