### ISSUE TITLE
[BUG][InputLayoutDateTime] @prizm-ui/components - В инпуте при выборе даты не проставляется дефолтное значение времени

### ISSUE THREAD

**Issue by opalleq** [zyfra/Prizm#1067]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmInputLayoutDateTimeComponent

### Версия

Операционная система:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v18.15.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.6.0
```

### Проект в котором используется Prizm

- Энергоконтроль

### Описание проблемы

В версии 1.3.0 и ниже при выборе даты автоматически проставлялось время по умолчанию (или наоборот, при выборе часа - дата по умолчанию).
Выглядело это так: 
![inputdatetime_143](https://github.com/zyfra/Prizm/assets/17828551/661ec1bb-0521-42e8-8c57-72f742e03090)

Начиная с версии 1.4.0, в момент выбора даты значение времени остается пустым. При этом оно проставляется, если кликнуть на инпут еще раз и убрать фокус. Аналогично с проставлением дефолтной даты при выборе часа. См. гиф:
![inputdatetime_current](https://github.com/zyfra/Prizm/assets/17828551/70acc2e3-92f7-4810-8715-98de5dd3e426)

Просьба проверить, баг ли это и, если да, вернуть поведение, которое было в версиях до 1.4.0.

**Comment by ZurabDev** [comment]
@PrizmDS как такие кейсы должны работать?

**Comment by PrizmDS** [comment]
@ZurabDev Обычно ставится системное время

**Comment by ickisIckis** [comment]
требуется проверить воспроизводимость на актуальных версиях

**Comment by opalleq** [comment]
Больше не воспроизводится. Спасибо!
