### ISSUE TITLE
[BUG] Документация на сайте. Раздел Компоненты - Table - Examples. Перестали отображаться примеры

### ISSUE THREAD

**Issue by spnikit** [zyfra/Prizm#1069]
### Скрин / Видео проблемы

<img width="1465" alt="image" src="https://github.com/zyfra/Prizm/assets/18352747/02676322-48dd-437a-959b-56bedf806c03">

### Описание проблемы

1. Зайти по адресу [prizm](https://prizm.site/components/table)

**Comment by ZurabDev** [comment]
Исправлено
