### ISSUE TITLE
[BUG] prizm/components - Ошибка при вызове конструктора PrizmDayRangePeriod()

### ISSUE THREAD

**Issue by outsidious** [zyfra/Prizm#107]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент
`InputDateRange`, класс `PrizmDayRangePeriod`

### Версия

Операционная сиcтема:
Windows 10 Pro 21H2

Браузер:
Google Chrome Версия 110.0.5481.180 (Официальная сборка), (64 бит)

NodeJS:
v16.16.0

Dependencies:
"@prizm-ui/components": "^1.0.0-beta.26",
"@prizm-ui/core": "^1.0.0-beta.26",
"@prizm-ui/helpers": "^1.0.0-beta.26",
"@prizm-ui/icons": "^1.0.0-beta.26",
"@prizm-ui/theme": "^1.0.0-beta.26",

### Проект в котором используется КБ
ИДЛ

### Скрин / Видео проблемы
![image](https://user-images.githubusercontent.com/66782814/227894945-9d7a05be-9b9c-4d49-a781-6c5bdb31ad27.png)

### Описание проблемы
Input-поле `[items]` компонента `InputDateRange `должно быть типа `PrizmDayRangePeriod`. Возникает ошибка при вызове конструктора данного класса. Текст ошибки:
`src_app_modules_analytics_analytics_module_ts.js:2 ERROR TypeError: _prizm_ui_components_lib_core_classes_day_range_period_d__WEBPACK_IMPORTED_MODULE_6__.PrizmDayRangePeriod is not a constructor`
    
    
_Шаги воспроизведения_:
1. Импортировать класс в любом компоненте ('"@prizm-ui/components"' has no exported member named 'PrizmDayRangePeriod', поэтому import напрямую из day-range-period.d):
`import { PrizmDayRangePeriod } from '@prizm-ui/components/lib/@core/classes/day-range-period.d';`
2. Вызвать конструктор PrizmDayRangePeriod:
```
ngOnInit(): void {
    //this.setItems();
    const test = new PrizmDayRangePeriod(
      new PrizmDayRange(new PrizmDay(2023, 3, 25), new PrizmDay(2023, 3, 28)),
      'test',
    );
    console.log(test);
}
```

**Comment by ZurabDev** [comment]
Исправили; В 28 версии export будет доступен из '@prizm-ui/components'

Импорт должен быть из prizm components
```import { PrizmDayRangePeriod } from '@prizm-ui/components'```

**Comment by ZurabDev** [comment]
Просьба проверить и закрыть тикет
