### ISSUE TITLE
[BUG] @prizm-ui/components - При использовании prizmInput без оборачивания в prizmInputLayout возникает NullInjectorError

### ISSUE THREAD

**Issue by spnikit** [zyfra/Prizm#1070]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [X] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmInputDirective PrizmInputLayoutComponent

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:
20
```
➜ node --version
v20
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 3.5.1
```

```
➜ npm ls @angular/core 16.2.0
```

### Скрин / Видео проблемы

<img width="910" alt="image" src="https://github.com/zyfra/Prizm/assets/18352747/a67e18d5-7244-40a8-859c-58a4c0badb62">

### Описание проблемы

Если не оборачивать input с директивой prizmInput в PrizmInputLayoutComponent возникает ошибка

**Comment by ZurabDev** [comment]
Попробуйте 3.5.2

**Comment by spnikit** [comment]
> Попробуйте 3.5.2

к сожалению все равно падает.

**Comment by AleksandrSibiakov** [comment]
Тоже столкнулись с этой проблемой на версии 3.5.2
