### ISSUE TITLE
[BUG] @prizm-ui/components - Нарушена совместимость версий

### ISSUE THREAD

**Issue by dmitriy-sokolov** [zyfra/Prizm#1073]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент
IconComponent (или PrizmIconComponent)

### Версия

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.9.0
```

### Проект в котором используется Prizm

- Мнемосхемы

### Скрин / Видео проблемы

![изображение](https://github.com/zyfra/Prizm/assets/25181659/f445467d-8753-4cdf-9eb2-99b0ee5be0cf)

### Воспроизведение проблемы

Есть сборка пакета на версии prizm 1.8.0. Приложение, используеющее пакет начинает использовать версию prizm 1.9.0. Во время компиляции линковщик, не находит `IconComponent`. **Версия 1.8.0 обратно не совместима с версией 1.9.0**

### Описание проблемы

Обнаружено: прошел [комит](https://github.com/zyfra/Prizm/pull/975/commits/bd3a9c3db84095e3b54a808b6425b294b87851ac), который зачем-то переименовывает **открытый** контаракт с `IconComponent` в `PrizmIconComponent`. 
Чтобы вернуть совместимость в версии prizm 1.9.1 был добавлен следующий код. 
![изображение](https://github.com/zyfra/Prizm/assets/25181659/4bf0893e-e3a4-49e3-86b6-5e7b128970ce)
Обратите внимание на директиву `@Component`, чтобы вернуть полную совместимость.

**Comment by ZurabDev** [comment]
Попробуйте 1.9.2, работу проверили, такой код работает
По поводу нового экспорта, сделали что бы вернуть прошлое наименвание до перехода на standalone

**Comment by dmitriy-sokolov** [comment]
Если сделать сборку с 1.9.2, а потом обнаружить кучу ошибок и попытаться откатиться до 1.8.0 (так как она более стабильная), то это сдлеать не получиться... так как селектор prizm-icon будет уже указывать на PrizmIconComponent. А данного класса нет в 1.8.0 (совместимость сломана)
