### ISSUE TITLE
[BUG] @prizm-ui/components - DropdownHost - закрывается при переключении даты

### ISSUE THREAD

**Issue by AndreySZyfra** [zyfra/Prizm#1074]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

DropdownHost 

### Проект в котором используется Prizm

- КПЕ

### Скрин / Видео проблемы

![defect](https://github.com/zyfra/Prizm/assets/151609798/7b6f2be0-b139-48e0-a450-a81dc75d2281)

### Описание проблемы

если в DropdownHost вложить <prizm-input-layout-date-time> или любой другой выбор даты (легче проверить на выборе месяца) - нажатие на смену даты по стрелочкам вправо-влево закрывает dropdownhost

1. Зайти по адресу [prizm](https://prizmui-next.web.app/components/dropdowns/dropdown-host)
2. посмотреть пример Date Range Template (Nested Dropdown)

**Comment by alexhawkins94** [comment]
@AndreySZyfra обходное решение - не пользоваться стрелками а использовать выпадашки с выбором месяца - не помогает Вам ?

**Comment by AndreySZyfra** [comment]
не пользоваться стрелками - помогает с выбором года или месяца, проблема в том, что если стоит компонент выбора месяца, то там кроме стрелок "вправо-влево" нет других элементов управления
