### ISSUE TITLE
[BUG] @prizm-ui/components - Ошибка ObjectUnsubscribedError если убить компонент в котором есть Tabs

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#1079]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Tabs

### Версия

Браузер:

`Google Chrome Версия 119.0.6045.160 (Официальная сборка), (x86_64)`

Dependencies:

@prizm-ui/components 1.9.2

### Проект в котором используется Prizm

-  @prizm-ui/components

### Воспроизведение проблемы

1. Открыть https://prizm.site/components/tabs
2. Открыть консоль браузера
3. Перейти на вкладку Live demo
4. Вернуть на вкладку Examples

### Описание проблемы

В консоли браузера ошибка 
![image](https://github.com/zyfra/Prizm/assets/20378994/cd8afacb-4818-480c-86ab-f5756359d9fd)

**Comment by alexhawkins94** [comment]
есть такая проблема в бэклоге
https://github.com/zyfra/Prizm/issues/842
