### ISSUE TITLE
[BUG] prizm/components - Диалоги игнорируют параметр `width`

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#108]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

_Dialogs (Dialog, ConfirmDialog, Sidebar?)_

### Версия
1.0.0-beta.26

### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/2631748/227913754-da23c7ca-58bb-47f8-b0cd-9045b04516d1.png)

### Описание проблемы

Параметр `width` задает только размер `z-overlay-wrapper`, что действует как `max-width` для диалога, который "растягивается" по `display: flex;` правилам (fit-content?).

1. Зайти по адресу [prizm](http://zds.zyfra.com/components/dialogs/dialog/Live_demo?tuiMode=null&width=800px) 
2. Открыть диалог (контент должен быть не длинным, чтобы не было переполнения указанной ширины)
3. Убедиться что размер окна меньше чем заданный в параметре.

**Comment by ZurabDev** [comment]
Просьба проверить и закрыть тикет
