### ISSUE TITLE
[Int] ConfirmPopUp/Tooltip/hint. Error ng0100 при первом вызове

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1091]
Error ng0100 при первом вызове конфирм поп-апа
Аналогично для тултипа, хинта.

Воспроизводится локально в дев режиме

![image](https://github.com/zyfra/Prizm/assets/122870313/adaf6e7b-8085-4752-a9b0-bd2e19e3895b)

**Comment by ickisIckis** [comment]
Та же проблема с хинтом при использовании prizmInputStatusText
