### ISSUE TITLE
[BUG] [InputLayoutDateRange]@prizm-ui/components - Ручной ввод  не всегда учитывает min и max

### ISSUE THREAD

**Issue by annzolotareva** [zyfra/Prizm#1092]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputLayoutDateRange

Операционная сиcтема:

`Windows 10`

Браузер:

`Google Chrome`

### Проект в котором используется Prizm

ИДЛ
Ошибка воспроизводится в примере на официальном сайте Prizm

### Скрины проблемы

![image](https://github.com/zyfra/Prizm/assets/92973848/fab9ebc7-f5b9-447f-b115-5a4e75ad8b61)
![image](https://github.com/zyfra/Prizm/assets/92973848/60b1b861-0716-499e-922b-83656eff064c)

### Описание проблемы
При ручном вводе, если ввести значения, которые не соответствуют min и max, они не всегда сбрасываются до минимально и максимально возможных.
На первом скрине, в 21 и 23 строках, задаются соответственно минимальное и максимальное значения. На 2 скрине воспроизведена ошибка: введённые даты не сбросились до указанных значений min и max. 

_Шаги воспроизведения_:

1. Зайти по адресу: https://doc.prizm.zyfra.com/components/input-layout-date-range
2. Выбрать любой из примеров, где задаётся min и max.
3. Ввести даты, которые не соответствуют указанным значениям min и max. 
Если даты сбросятся до указанных значений, ещё раз выполнить этот пункт.

**Comment by alexhawkins94** [comment]
при исправлении учесть еще другой баг, когда границы не учитываются https://github.com/zyfra/Prizm/issues/883
