### ISSUE TITLE
[BUG] @prizm-ui/components - PrizmHintDirective. Хин-контейнер имеет data-prizm-theme="undefined"

### ISSUE THREAD

**Issue by digital-plant-guard** [zyfra/Prizm#1123]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmHintDirective

NodeJS:

```
➜ node --version
v18.16.0
```

Dependencies:

Settings for zui-app-shell:
      v 5.0.0-rc.2
      angular 16.2.11
      prizm components ^3.4.0
      useServerApplicationUnits: true

```
➜ npm ls @prizm-ui/components

zui-app-interface-manager@3.1.0-alpha.1
├─┬ @digital-plant/dc-sdk@8.0.0
│ └── @prizm-ui/components@3.6.0 deduped
└── @prizm-ui/components@3.6.0
```

```
➜ npm ls @angular/core

zui-app-interface-manager@3.1.0-alpha.1
├─┬ @angular/animations@16.2.12                                               
│ └── @angular/core@16.2.12 deduped                                           
├─┬ @angular/cdk@16.2.12                                                      
│ └── @angular/core@16.2.12 deduped                                           
├─┬ @angular/common@16.2.12                                                   
│ └── @angular/core@16.2.12 deduped                                           
├─┬ @angular/compiler@16.2.12                                                 
│ └── @angular/core@16.2.12 deduped                                           
├── @angular/core@16.2.12                                                     
├─┬ @angular/forms@16.2.12                                                    
│ └── @angular/core@16.2.12 deduped                                           
├─┬ @angular/platform-browser-dynamic@16.2.12                                 
│ └── @angular/core@16.2.12 deduped                                           
├─┬ @angular/platform-browser@16.2.12                                         
│ └── @angular/core@16.2.12 deduped                                           
├─┬ @angular/router@16.2.12                                                   


```

### Проект в котором используется Prizm

- zui-app-interface-manager

### Скрин / Видео проблемы

<img width="440" alt="prizm hint" src="https://github.com/zyfra/Prizm/assets/126816006/3843711b-2f45-49e3-8277-1bef4455c4c3">

![image](https://github.com/zyfra/Prizm/assets/126816006/4d1c89d5-b5ab-4f04-9265-3d1fc66dee81)

### Описание проблемы
После обновления Prizm c 3.4.0 на 3.6.0 изменился цвет хинтов тк data-prizm-theme="undefined". Воспроизводится как при импортировании модуля PrizmHintModule, так и standalone компонента PrizmHintDirective.

**Comment by ickisIckis** [comment]
Исправлено в 3.10.0 #1309

**Comment by digital-plant-guard** [comment]
Воспроизводится в Prizm 4.0.0-next.2 (Angular 17.2.x)

**Comment by imonogarov** [comment]
@digital-plant-guard просьба проверить на последней версии Prizm

**Comment by digital-plant-guard** [comment]
> @digital-plant-guard просьба проверить на последней версии Prizm

Проверил на v4.3.1 - работает как нужно. спасибо!
