### ISSUE TITLE
[BUG] Документация - Ссылки ведут на внешний сайт

### ISSUE THREAD

**Issue by bumalai** [zyfra/Prizm#1133]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [x] Сайт документации

### Компонент

- Docs

### Описание проблемы

_Делаю задачу_

_Есть проблема следующего характера:_

<img width="364" alt="image" src="https://github.com/zyfra/Prizm/assets/131881448/5ef057b3-2ca1-4202-91c8-2bc6c094920b">

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](https://doc.prizm.zyfra.com)
2. Увидеть что ссылается на prizm.site. 

_Ожидаемый результат_:

Должны ссылаться на тот хост, на котором находится.

**Comment by ickisIckis** [comment]
Так же в документации есть устаревшие ссылки на статьи (jira). Необходимо обновить тексты, связанные с ними.

**Comment by ickisIckis** [comment]
Требуется принять решение по реализации
