### ISSUE TITLE
[Int] Calendar. Поправить отрисовку/рендеринг переключения на выбор года

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1147]
странно рендерится переключение на выбор годов - выглядит дергано/прыгает. 
Должно быть более smoothly/плавно/гладко.

![image](https://github.com/zyfra/Prizm/assets/122870313/ebb0a4c4-ec31-4354-82c7-a74482cfdd14)

**Comment by ickisIckis** [comment]
@alexhawkins94, нужно проверить, актуально ли для версий 3.12.0 и 4.1.0

**Comment by alexhawkins94** [comment]
не актуально на 4.1 и 3.12
