### ISSUE TITLE
[Int] Inputs. При клике на кнопку очистки на мгновение появляется фокус у самого инпута

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1152]
Во всех инпутах кроме input text, input mask, password, input carousel при клике на кнопку очистки на мгновение появляется фокус у самого инпута.

Ожидаемый результат:  "Фокус не на мгновение а на постоянку, т.к мы кликнули по инпуту и начали с ним взаимодействовать. Обычно если пользователь что-то решил стереть, то он хочет ввести новые данные"

![chrome_FsJrQeMUol](https://github.com/zyfra/Prizm/assets/122870313/73643cce-3664-4f0b-a43d-3a4de788a5e6)

**Comment by ickisIckis** [comment]
нужно проверить, воспроизводится ли на актуальных версиях

**Comment by alexhawkins94** [comment]
не актуально, но фокус при очистке не устанавливается - завёл отдельно баг https://github.com/zyfra/Prizm/issues/2168
