### ISSUE TITLE
[Feature] Paginator. Добавить расположение элементов Left

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#1154]
### Библиотека

- [ ] `@prizm-ui/core`
- [X] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_Paginator_

### Предложение

_Работаю в рамках задачи массового создания операций проекта СОУ_

![image](https://github.com/zyfra/Prizm/assets/26089012/76fd5cb7-d247-4be3-8627-742fef1af9ab)

На актуальной странице пагинатора в фигме есть 2 варианта раскладки, которые называются Right и Left

![image](https://github.com/zyfra/Prizm/assets/26089012/742c94ad-d702-422d-baa5-444d7edc10d1)

В текущей версии 3.6.0 компонента реализован только Right https://prizm.site/components/paginator

 _Предлагаю реализовать второй вариант и добавить возможность указывать направление (Right и Left)_

**Comment by PrizmDS** [comment]
Будет проведен рефакторинг

**Comment by PrizmDS** [comment]
Решили оставить 2 варианта. Необходимо добавить пример на витрину
