### ISSUE TITLE
[BUG] prizm/components - Select: значение Null Content не доступно для выбора, если в поле уже выбрано значение

### ISSUE THREAD

**Issue by pitrukevgenii** [zyfra/Prizm#116]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

Select

### Версия

Операционная сиcтема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/zyfra-components

@prizm-ui/zyfra-components 0.1.1
```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Проект в котором используется КБ

Z-MEB

### Скрин / Видео проблемы

https://disk.yandex.ru/d/lsUDGgZUfw_GGQ

### Описание проблемы

Значение Null Content не отображается, если предварительно в поле выбрано другое значение, предварительно требуется его очистить, и только после этого выбрать Null Content. Это не очевидное поведение.

_Шаги воспроизведения_:

1. Зайти по адресу https://doc.prizm.zyfra.com/components/dropdowns/select
2. Раскрыть произвольный Select
3. Выбрать любое значение (кроме "Не выбрано").
4. Раскрыть Select ещё раз 

Ожидаемый результат:
"Не выбрано" отображается в списке и доступно для выбора

Фактический результат: 
"Не выбрано" не отображается в списке

**Comment by ZurabDev** [comment]
Просьба проверить и закрыть тикет

**Comment by pitrukevgenii** [comment]
Проверил на 1.0.0-beta.28.
