### ISSUE TITLE
[Feature] добавить отдельный сайт по темизации компонентов

### ISSUE THREAD

**Issue by bumalai** [zyfra/Prizm#1163]
### Предложение

Предлагаю сделать отдельный проект/страницу по темизации и вариантов его использования.
Документ по расширению тем должен оставаться на страницах основной доки.

Примеры реализации:

Theme builder: 
https://m3.material.io/theme-builder#/custom

Figma builder:
https://www.figma.com/community/plugin/1034969338659738588/material-theme-builder

Devexpress:

https://devexpress.github.io/ThemeBuilder/

**Comment by ickisIckis** [comment]
Theme changer в 4.0
