### ISSUE TITLE
[BUG] PrizmIconsSvgComponent - отступы при задании размера иконок

### ISSUE THREAD

**Issue by OlgaMerkulova** [zyfra/Prizm#1165]
Компонент
PrizmIconsSvgComponent

### Описание проблемы
При задании размера иконки в самом компоненте есть отступы, ввиду чего размер иконки меньше фактически заданного
![image](https://github.com/zyfra/Prizm/assets/52113470/ea7313c2-afa3-4ac2-a8ca-09474eb9e946)

**Comment by PrizmDS** [comment]
Размер самой иконки и контейнера всегда будут отличаться. У каждой иконки свой визуальный размер и для их балансировки нужно пространство

**Comment by ickisIckis** [comment]
В новых иконках 4.0 добавлен компонент fullsize
