### ISSUE TITLE
[BUG] PrizmIconsSvgComponent - обводка у иконок шире, чем на макете

### ISSUE THREAD

**Issue by OlgaMerkulova** [zyfra/Prizm#1166]
Компонент
PrizmIconsSvgComponent

Описание проблемы
Слева иконка на макетах, справа иконка в prizm. Видно, что в компоненте обводка сильно толще, чем предполагалось
![image](https://github.com/zyfra/Prizm/assets/52113470/52fd7371-88cc-4914-b3ef-5679e778fff8)

**Comment by PrizmDS** [comment]
Иконки размывает из-за смежных пикселей

**Comment by ickisIckis** [comment]
В версии 4.0 появятся новый компоент

**Comment by ZurabDev** [comment]
Нужна задача для дизайна, для исправление векторных линий в фигме
