### ISSUE TITLE
[BUG] InputChips - в темной теме не соблюдена контрастность

### ISSUE THREAD

**Issue by OlgaMerkulova** [zyfra/Prizm#1167]
### Компонент
InputChipsComponent

### Описание проблемы
Цвет чипсов не соответствует макету
![image](https://github.com/zyfra/Prizm/assets/52113470/ee99eb81-b1d7-4e2c-b637-6a33a119200b)

**Comment by DenisBiktanov** [comment]
https://github.com/zyfra/Prizm/pull/1253

**Comment by DenisBiktanov** [comment]
решено в версии 3.9.0
