### ISSUE TITLE
[Feature] Disabled Switcher

### ISSUE THREAD

**Issue by Anna-Prokhorova** [zyfra/Prizm#117]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

Switcher

### Предложение

В рамках проекта "ИДЛ" требуется иметь возможность дизейблить компонент Switcher.

Было бы здорово добавить инпут поле "disabled" типа boolean.

**Comment by ZurabDev** [comment]
<img width="462" alt="CleanShot 2023-03-30 at 15 48 39@2x" src="https://user-images.githubusercontent.com/75216044/228840956-6d8e1f29-12ce-4af6-acca-e612fed6a78c.png">
Готово. Будет в 28 версии

**Comment by ZurabDev** [comment]
Просьба проверить и закрыть тикет
