### ISSUE TITLE
[BUG] @prizm-ui/icons - Отсутствует иконка poi-hand

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#1178]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [x] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

@prizm-ui/icon

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/20378994/56e5bee3-d091-4f21-8938-8aa901406421)

### Описание проблемы

Отсутствует иконка poi-hand

**Comment by PrizmDS** [comment]
Икона из набора КБ 3. В наборе Prizm такой нет

**Comment by ickisIckis** [comment]
Вы можете добавить в проект свою иконку в формате svg. Для этого необходимо использовать PrizmIconsSvgRegistry.


`
import { PrizmIconsSvgRegistry } from '@prizm-ui/icons';

export class PrizmIconSvgSvgExampleComponent {
  readonly myIcon = {
    name: 'myIconName',
    data:  svgIconData, // Здесь указать svg код иконки
  };

 constructor(private readonly iconRegistry: PrizmIconsSvgRegistry) {
    this.iconRegistry.registerIcons([myIcon]);
}
`
