### ISSUE TITLE
[BUG] prizm/components - Тосты перекрывают друг друга

### ISSUE THREAD

**Issue by ickisIckis** [zyfra/Prizm#118]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

Toast

### Версия

1.0.0-beta.27

### Скрин / Видео проблемы

![image_2023-03-30_10-36-09](https://user-images.githubusercontent.com/18642277/228815059-9c579bf6-0ea0-4a16-aa02-cf4bf098bbed.png)

### Описание проблемы

Серверные ошибки в проекте выводятся на экран с помощью тостов. И часть тостов перекрывают друг друга, как на примере в скирншоте.  
При этом один из тостов из примера (с 500 ошибкой) открывается из интерсептора, остальные три, которые не перекрывают друг друга и стоят ровно - из разных сервисов, относящихся к одному общему модулю.

**Comment by ZurabDev** [comment]
Просьба проверить и закрыть тикет
