### ISSUE TITLE
[BUG] @prizm-ui/components - Нет возможности отключить фокус у элемента checkbox

### ISSUE THREAD

**Issue by algashev123zyfra** [zyfra/Prizm#1180]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmCheckboxComponent

### Версия

Операционная сиcтема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v14.21.3
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.10.0
```

```
➜ npm ls @angular/core

@angular/core 14
```

### Проект в котором используется Prizm

- _Название проекта_

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/142902249/de962abd-a148-40bd-ae35-f7c331d35cf1)

### Описание проблемы
Необходима возможность отключения фокуса у элемента checkbox

**Comment by PrizmDS** [comment]
В чем необходимость? Это стандартное поведеие компонентов
