### ISSUE TITLE
[FEATURE] @prizm-ui/components - Добавить возможность отключить фокус у кнопок раскрытия навигационного меню

### ISSUE THREAD

**Issue by algashev123zyfra** [zyfra/Prizm#1181]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmNavigationMenuComponent

### Версия

Операционная система:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v14.21.3
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.10.0
```

```
➜ npm ls @angular/core

@angular/core 14
```

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/142902249/972072c1-3c50-4e70-8a11-a2eee2ba9f09)

### Описание проблемы
Необходима возможность отключения фокуса у кнопок раскрытия навигационного меню

**Comment by ZurabDev** [comment]
Это стандартное поведеие компонентов. 
 Обсуждение аналогичного запроса было #1180
