### ISSUE TITLE
[BUG] InputSelect Перестал отображаться placeholder в input-select

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#1187]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_InputSelect_

### Версия

В проекте 1.9.0, но воспроизводится в публичной песочнице 3.6.0 / 2.7.0 / 1.10.0

### Проект в котором используется Prizm

- СОУ

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/26089012/f9706a8c-1710-41aa-a6ec-495ca0da64ac)

### Описание проблемы

_Есть проблема следующего характера:_ Перестал отображаться placeholder

_Шаги воспроизведения_:

1. Зайти по адресу https://prizm.site/components/input-select/Live_demo?tuiMode=null&outer=true&label=%20&placeholder=Тэг%20не%20выбран

**Comment by alexhawkins94** [comment]
known bug

**Comment by alexhawkins94** [comment]
https://github.com/zyfra/Prizm/issues/1038
