### ISSUE TITLE
[BUG] prizm/components - Не отображается обязательность заполнения Select

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#119]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[Select](http://doc.prizm.zyfra.com/components/dropdowns/select)

### Версия

1.0.0-beta.27

### Описание проблемы

При использовании компонента Select с реактивной формой (через template-driven forms скорее тоже) нет возможности отобразить пользователю, что поле обязательно для заполнения. Более того поле ни как не подсвечивает ошибку валидации (отсутствует символ `*` в лейбле, красная рамка, иконка с хинтом).

Пример кода:
```ts
class SomeComponent {
  control = new FormControl(null, Validators.required);
  items = ['Option 1', 'Option 2', 'Option 3'];
}
```

```html
<prizm-select
  label="Field"
  size="m"
  [formControl]="control"
  [items]="items"
  [searchable]="true"
></prizm-select>
```

В макетах figma дизайн системы желаемый вид компонента отрисован:
![image](https://user-images.githubusercontent.com/52266097/229062804-a02458e4-db28-477c-91c2-35fd16065937.png)

**Дополнение:** Аналогичная проблема с компонентом [InputDateTime](http://doc.prizm.zyfra.com/components/input-date-time). Возможно, где-то ещё.

**Comment by dkshichkovskiy** [comment]
@ZurabDev А можно сделать такое же для prizm-input-date-time? Могу завести отдельный issue, если нужно

**Comment by ZurabDev** [comment]
@dkshichkovskiy Привет, да конечно.
Этот тикет закрой плиз

**Comment by ZurabDev** [comment]
Если речь идет о компоненте multiselect то создайте тикет плиз, а если о select в рамках этого тикета решим

**Comment by javadoffuad** [comment]
> ```
> если о select в рамках этого тикета решим
> ```

В селекте обнаружил следующую проблему:

1. В селекте ничего не выбрано, отсутствуют какие либо ошибки
2. Открываем дропдаун
3. Выбираем какой ни будь элемент из списка _(при выборе важно нажать и удерживать)_ 
4. В компоненте появляется уведомление об ошибке
5. После того так отпускаем нажатую кнопку, уведомление пропадает, выбранное значение отображается

![image](https://user-images.githubusercontent.com/7090093/230082839-07e405ce-3976-46e0-99d9-92e17a194e8b.png)
![image](https://user-images.githubusercontent.com/7090093/230082335-3455f1a8-235a-40c5-8975-b2e7135a0b28.png)

**Comment by javadoffuad** [comment]
@ZurabDev Для мультиселекта создал отдельный тикет https://github.com/zyfra/Prizm/issues/129
