### ISSUE TITLE
[BUG] @prizm-ui/components - `PrizmInputComponent` with `NgxMaskDirective` behaves incorrectly when changed from empty value

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#1190]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_PrizmInputComponent_

### Версия

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 3.7.0
```

### Воспроизведение проблемы

https://stackblitz.com/edit/prizm-v3-input-with-mask?file=src%2Fapp%2Fapp.component.html

### Описание проблемы

Сценарий - ограничение символов в поле ввода (числовое, или произвольное)

_Есть проблема следующего характера:_

При изменении значения `<input prizmInput mask="...">` с пустого на произвольное (т.е. первое изменение), это изменение 
* не помечает поле как `dirty`
* при вводе недопустимого символа, этот символ попадает в модель (см. Case 2 со stackblitz выше)

#### Результаты исследования

Дебаг выявил, что проблема появляется после попадания в следующий вызов
![image](https://github.com/zyfra/Prizm/assets/2631748/e23d91c8-dc0e-4520-a9d0-8b5e9af8ae0c)

Как видим, `this.value` получает значение `2` - значение из поля ввода, в то время как значение контрола еще не обновилось, это ведет к вызову `ngControl.control.setValue` на строчке https://github.com/zyfra/Prizm/blob/fe630b69de47158036040ea691fe19f49f7ec99d/libs/components/src/lib/components/input/input-text/input-text.component.ts#L272
тем самым обновляя значение `formControl` в обход стандартного потока значений - вызова колбэка зарегестрированного через `registerOnChange`.

Предлагаю:
* не использовать `FormControl.setValue` при апдейте значения в инпуте (и вообще) - это не верно, и такой функционал выходит  за рамки данной директивы\компонента (предполагаю, что вызов `updateHint` является целью вызова `updateValue` - можно `updateHint` вызвать напрямую)

**Comment by AleksandrSibiakov** [comment]
Еще подумал (в тему корректности использования `ngControl.setValue` в компоненте) - а вы проверяете поведение на сетапах типа `ngModelOptions="{ updateOn: 'blur' }"` ? 

Ведь в этом случае, к примеру при вызове `InputTextComponent.clear` (в котором тоже вызывается `updateValue -> control.setValue`), `setValue` апдейтит значение сразу, тогда как при нормальном потоке, через событие инпута на HTMLInputElement, или вызове зарегестрированного `registerOnChange` значение запишется только в `ngControl._pendingValue` и отправится в модель только по событию `blur` (а если точнее, после вызова зарегестрированного через `CVA.registerOnBlur` колбэка)

**Comment by AleksandrSibiakov** [comment]
Та же цепочка событий приводит к тому что валидаторы запускаются после первого символа, даже если явно указать `updateOn: blur` (нам нужно для ограничения кол-ва вызовов асинхронного валидатора).
Если надо, могу как отдельную проблему оформить, но суть та же - это из за вызова `FormControl.setValue`

**Comment by ZurabDev** [comment]
> Та же цепочка событий приводит к тому что валидаторы запускаются после первого символа, даже если явно указать `updateOn: blur` (нам нужно для ограничения кол-ва вызовов асинхронного валидатора). Если надо, могу как отдельную проблему оформить, но суть та же - это из за вызова `FormControl.setValue`

Можешь оформить пожалуйста отдельно?
