### ISSUE TITLE
[BUG] @prizm-ui/components - Не для каждого компонента есть пример на `stackblitz`

### ISSUE THREAD

**Issue by dmitriy-sokolov** [zyfra/Prizm#1210]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Navigation menu

### Версия

Операционная ситема:

`Manjaro linux`

Браузер:

`Firefox 120.0.1 (64-разрядный)`
`Chromium Версия 120.0.6099.109 (Официальная сборка), Arch Linux (64 бит)`

### Проект в котором используется Prizm

- Мнемосхемы

### Скрин / Видео проблемы

![изображение](https://github.com/zyfra/Prizm/assets/25181659/cc7ac13e-23b9-4eb1-b788-09f3650a4c46)

### Воспроизведение проблемы

Переходим в [песочницу компонентов](https://doc.prizm.zyfra.com/components/navigation-menu). В примерах, нет перехода на stackblitz. 

### Описание проблемы

Переводжу проводник документов на `prizm`. Требуются примеры на `stackblitz`.

### Ожидаемое поведение

Каждому примеру песочницы есть рабочий пример в `stackblitz`.

**Comment by ZurabDev** [comment]
Надо провести иследование, декомпозицую задачи, и добавлять в рамках 4 версии в каждую итерацию

**Comment by imonogarov** [comment]
В настоящий момент не было задачи добавить stackblitz для всех примеров в силу разного рода ограничений. Для этого есть общий stackblitz пример в переключалке версий.
