### ISSUE TITLE
[BUG] @prizm-ui/components - При динамическом изменении размеров родительского блока у PrizmInputMultiSelect некорректно работает обрезание текста

### ISSUE THREAD

**Issue by algashev123zyfra** [zyfra/Prizm#1215]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmInputMultiSelect

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v14.21.3
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.10.0
```

```
➜ npm ls @angular/core

@angular/core: 14

```

### Скрин / Видео проблемы
![Анимация](https://github.com/zyfra/Prizm/assets/142902249/f309c0a2-786e-4ff9-a0be-a209368f13e6)

https://github.com/zyfra/Prizm/assets/142902249/416b4c37-f683-4b8d-b08e-6ed3df6eb4a9

### Описание проблемы
В нашем кейсе данный инпут используется как ячейка таблицы. при динамическом изменении размеров ячейки ellipsis некорректно подстраивается под текущие размеры. при открытии выпадающего списка ширина задается корректно.

**Comment by imonogarov** [comment]
@alexhawkins94 просьба перепроверить

**Comment by alexhawkins94** [comment]
fixed
