### ISSUE TITLE
[Question] Есть ли возможность реализовать настройку колонок в таблице с несколькими сроками и объединением колонок в заголовке? 

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#1218]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Table

### Проект в котором используется Prizm

СОУ

### Вопрос

Есть ли возможность реализовать настройку колонок в таблице с несколькими сроками и объединением колонок в заголовке
![image](https://github.com/zyfra/Prizm/assets/17219726/8c4c000a-ba90-4d1f-9ff6-26e450c668fc)
если да, можно ли добавить пример в документацию?

**Comment by ickisIckis** [comment]
Такого результата можно добиться с помощью атрибутов rowspan и colspan. Похожий пример есть в документации (раздел Search)
https://prizm.site/components/table#search
