### ISSUE TITLE
[Int] Multiselect. Blinking at rerender chips 

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1220]
Выносим замечание из МР-а https://github.com/zyfra/Prizm/pull/1206

Наблюдаю новую проблему отрисовки в мультиселекте  при выборе/снятии чекбоса мерцает чипс в инпуте и многоточие отображается вне ипнута
![image](https://github.com/zyfra/Prizm/assets/122870313/32a59215-31e1-4475-a543-6ba457fe4acd)

**Comment by ickisIckis** [comment]
исправлено в версии 4.3.6 с #1718
