### ISSUE TITLE
[Int] Multiselect. Отсутствует фокус

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1225]
Отсутствует фокус у мультиселекта при клике в инпут и при навигации на него через tab

**Comment by ickisIckis** [comment]
Связано с #1297

**Comment by ickisIckis** [comment]
По согласованию с @PrizmDS, фокус устанавливается только в случае управления с клавиатуры

**Comment by ickisIckis** [comment]
В этой задаче также необходимо решить проблему с focus-visible в элементах input

**Comment by dkshichkovskiy** [comment]
@ickisIckis Такое поведение `:focus-visible` на инпутах вполне ожидаемое - https://github.com/WICG/focus-visible/issues/131 . Может быть нам так и оставить? 

Да и думаю для пользователя будет странным, если при вводе значение в инпут, у него не будет отображаться рамка фокуса у данного поля. Обычно так не делают.

**Comment by ickisIckis** [comment]
> @ickisIckis Такое поведение `:focus-visible` на инпутах вполне ожидаемое - [WICG/focus-visible#131](https://github.com/WICG/focus-visible/issues/131) . Может быть нам так и оставить?
> 
> Да и думаю для пользователя будет странным, если при вводе значение в инпут, у него не будет отображаться рамка фокуса у данного поля. Обычно так не делают.

Да, в браузерах именно так себя и ведут элемент ввода: это поведение по спецификации, сделано в целях повышения удобства доступа для людей с ограниченными возможностями (accesebility) в том числе. Изучали этот вопрос в рамках работы над задачей по focus-visible. Есть возможность имитации поведения focus-visible, в Prizm уже реализован сервис этого, но нужно ли это делать - пока открытый вопрос. 
На данный момент для latest версий (3.12, 4.1.0) поведение с фокусом для инпутов не менялось и баг для мультиселекта все еще актуален. Задача на изучении.

@PrizmDS, обрати внимание, пожалуйста.

**Comment by imonogarov** [comment]
попробовать FocusZone

**Comment by imonogarov** [comment]
связано с #1984

**Comment by imonogarov** [comment]
связано #1850
