### ISSUE TITLE
Как при нажатии на кнопку в Dialog закрыть окно? 

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#123]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Dialog 

### Проект в котором используется Prizm

- Конфигуратор

### Вопрос

В Dialog добавлена кнопка через ng-template. При ее нажатии должна запускаться определенная функция (это сделано) и также закрываться диалоговое окно, как это сделать? 
![image](https://user-images.githubusercontent.com/17219726/229704642-107f9c6e-0643-491a-a6bd-aad2b1dbc2ac.png)

**Comment by ZurabDev** [comment]
Обновлены примеры
