### ISSUE TITLE
[Feature] [Accordion] - Добавить возможно изменять иконку для раскрытия аккордеона 

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#1235]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Accordion

### Предложение

Задача https://jira.zyfra.com/browse/IDPPSOU-3431
Просьба добавить возможность изменять иконку для раскрытия аккардеона.
На данный момент иконка: 
![image](https://github.com/zyfra/Prizm/assets/17219726/f508497e-7a50-4c59-a73e-a9ea843930a8)
требуется реализовать такую:
![image](https://github.com/zyfra/Prizm/assets/17219726/c510bd4e-40fd-41ed-934d-2c8382b2da89)

**Comment by ickisIckis** [comment]
@PrizmDS, необходимо уточнить, можно ли менять иконку в аккордеоне по гайдлайнам.

**Comment by PrizmDS** [comment]
Иконка привязана к функционалу. Возможность менять иконку из коробки -- предоставлять не будем.
