### ISSUE TITLE
[BUG] prizm/components - Не отображается обязательность заполнения InputDateTime

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#124]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[InputDateTime](http://doc.prizm.zyfra.com/components/input-date-time)

### Версия
1.0.0-beta.28

### Описание проблемы
При использовании компонента InputDateTime с реактивной формой (через template-driven forms скорее тоже) нет возможности отобразить пользователю, что поле обязательно для заполнения. Более того поле ни как не подсвечивает ошибку валидации (отсутствует символ * в лейбле, красная рамка, иконка с хинтом).

Проблема аналогична https://github.com/zyfra/Prizm/issues/119.

**Comment by ZurabDev** [comment]
<img width="534" alt="CleanShot 2023-04-14 at 14 04 55@2x" src="https://user-images.githubusercontent.com/75216044/232027817-f75cecbb-47c2-461b-b2ee-8e389a4d66b7.png">
Добавлено будет в 30 версии
