### ISSUE TITLE
[BUG] @prizm-ui/components - prizm-input-date-time-range декабрь 2023 работает не правильно

### ISSUE THREAD

**Issue by stepandr** [zyfra/Prizm#1241]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [X] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

prizm-input-date-time-range

### Версия

Операционная система:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

➜ npm ls @prizm-ui/components

@prizm-ui/components 3.8.0

### Проект в котором используется Prizm

- Уведомления

### Скрин / Видео проблемы

ссылка на видео https://disk.yandex.ru/i/IqLHgUz2ruZPIQ

<prizm-input-date-time-range
            [formControl]="dateControl"
            [label]="'common.period' | translate"
            [max]="maxDate"
            [forceClear]="false"
            testId="date"
          ></prizm-input-date-time-range>

**Comment by stepandr** [comment]
Проверили в 3.1.2 не воспроизводится, спасибо

**Comment by AntonGrekov** [comment]
По неизвестным причинам баг временно не воспроизводился. Сейчас при новом тестировании воспроизводится в 3.12.0
Прикладываю видео. На видео видно как в одном случае месяц слипается с годом(нет пробела), а далее при переключении месяцев расстояние между месяцем и годом то увеличивается то уменьшается

[screen-capture (1).webm](https://github.com/zyfra/Prizm/assets/44285258/f816bb72-5979-4a49-8717-4ca80c4c5895)

**Comment by imonogarov** [comment]
@stepandr просьба проверить на текущей версии

**Comment by ickisIckis** [comment]
> Проблема больше не воспроизводится

спасибо, закрываем
