### ISSUE TITLE
[BUG] @prizm-ui/components - `PrizmNavigationMenu` нижний бордер двигается вместе со скроллом

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#1243]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_PrizmNavigationMenu_

### Версия

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 3.8.0
```

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/2631748/affe5b56-065b-40d5-8084-c8a80136b56b)

### Описание проблемы

_Есть проблема следующего характера:_

Имеем навигационное меню длинее области видимости. У нижней границы видим бордер (отделяет нижнюю и верхнюю части). При скролле этот бордер уезжает наверх.
Визуально, в зависимости от zoom и разрешения экрана, бордер может попасть на элемент меню, при скролле это выглядит как зачеркнутый элемент меню.

**Comment by ickisIckis** [comment]
проблему не удается воспроизвести на версии 4.3.1
@alexhawkins94, нужно дополнительно проверить, актуальна ли еще задача.

**Comment by alexhawkins94** [comment]
could not reproduce
