### ISSUE TITLE
[BUG] Input при outer=true стал неверный отступ у label

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#1259]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_Input_

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 2.9.0
```

### Проект в котором используется Prizm

- _СОУ_

### Скрин / Видео проблемы

Actual
![image](https://github.com/zyfra/Prizm/assets/26089012/b099bb44-92a9-4d2d-b4f6-23631dad7578)

Expected
![image](https://github.com/zyfra/Prizm/assets/26089012/f7b23ac4-7556-4696-b2b6-b353cf127fb9)

1. Зайти по адресу [prizm](https://prizm.site/components/input/Live_demo?tuiMode=null&outer=true)
2. ...

**Comment by bree7e** [comment]
Вероятно под капотом связано с https://github.com/zyfra/Prizm/issues/1245

**Comment by alexhawkins94** [comment]
@bree7e  сверьтесь с новыми макетами 
![chrome_Quog9Xa9d6](https://github.com/zyfra/Prizm/assets/122870313/944b72c1-3345-4ecb-a1a9-492669aa79d0)

https://www.figma.com/file/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8E-Prizm.-%D0%A1omponent-base-4.0?type=design&node-id=10993-186105&mode=design&t=6iSRD8Q2QrnvDrSd-0

судя по вашему скриншоту в expected - вы смотрели в раздел Descriptions для инпутов, так вот там могут быть не актуальные макеты

@PrizmDS

**Comment by bree7e** [comment]
Ох уже эти неактуальные страницы. Закрываем тогда.
