### ISSUE TITLE
[BUG] prizm/components - Не работает сортировка по умолчанию в Table

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#126]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[Table](http://doc.prizm.zyfra.com/components/table)

### Версия

1.0.0-beta.28

#### Не выполняется сортировка по умолчанию

Если прокинуть в директиву `prizmTable` свойство `sort`, а так же определить для конкретных колонок свойство `sorter`, то в шапке столбца отображена сортировка по колонке, однако сортеры не вызываются, пока через UI не поменяешь сортировку. Как следствие в таблице данные не отсортированы.  

```typescript
 public initSortOptions: PrizmTableCellSorter<unknown>[] = [
  {
    options: {
      id: 'field',
      order: 'desc',
    },
  },
];
```
```html
<table
  prizmTable
  [columns]="columns"
  [sort]="initSortOptions"
>
  <th
    prizmTh
    *prizmHead="'field'"
    [sorter]="sorter"
  >
    Колонка
  </th>
```

Но если поменять `initSortOptions`  на следующее, то сортировка по умолчанию отрабатывает:
```typescript
public initSortOptions: PrizmTableCellSorter<unknown>[] = [
  {
    options: {
      id: 'field',
      order: 'desc',
    },
    sorter: this.sorter.bind(this),
  },
];
```

То есть сортеры на колонках при инициализации сортировки не учитываются, и это странно.

#### При двустороннем биндинге [(sort)] сбрасывается значение в []

Если биндить через `[(sort)]` (`(sortChange)` доступен, так что это валидный биндинг), то значение перетирается из table на `[]`, т.е. сбрасывает сортировку при инициализации таблицы.

**Comment by dkshichkovskiy** [comment]
@ZurabDev Подскажи плиз по статусу. Уже можно проверять или ещё в работе?

**Comment by ickisIckis** [comment]
Проблема проверена в версии 3.1.0 - стартовые значения сортировки устанавливаются, в документацию добавлен пример.
