### ISSUE TITLE
[BUG] В обязательном Input не отображается индикация об ошибке после сброса значения

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#1284]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Input](https://prizm.site/components/input)

### Описание проблемы

Есть контрол Input с валидацией обязательности значения, у него изначально проставлено значение, пользователь с контролом не взаимодействовал. Если пользователь кликает на иконку сброса выбранного значения, то индикация ошибки не отображается. Так до тех пор пока пользователь не кликнет, например, на сам контрол.

Проблема скорее всего идентична https://github.com/zyfra/Prizm/issues/1076.

Воспроизводится на ветрине: https://prizm.site/components/input#validation-example

**Comment by AleksandrSibiakov** [comment]
@ZurabDev Это ожидаемо, что после фикса поле больше не фокусируется после нажатия кнопки `clear`?

P.S. Если расфокусировку убрали "случайно", то при описанных в баге обстоятельствах не уверен что ошибка должна отображаться сразу по нажатии кнопки, т.к. технически мы остаемся внутри контрола, и он не должен помечаться как touched до события blur. Нам дизайнер так же часто делал замечания, что ошибки не должны показываться до тех пор, пока пользователь не закончил взаимодействие с контролом.

**Comment by AleksandrSibiakov** [comment]
@alexhawkins94 может ты можешь помочь с вопросом выше?
