### ISSUE TITLE
[BUG] @prizm-ui/theme - Происходит смена темы на стандартную (светлую) при инициализации сервиса PrizmThemeService

### ISSUE THREAD

**Issue by RoxVell** [zyfra/Prizm#1287]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [x] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

PrizmTheme

### Проект в котором используется Prizm

AppShell

### Воспроизведение проблемы

1. Перейти в приложение, которое поддерживает смену темы, например: "Управление расчетами" (<стенд>/cs/calculations)
2. Включить ночной режим
<img width="410" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/499c2b2c-989c-4f96-8915-4e4eab568487">  

При этом атрибут "data-prizm-theme" должен принять значение "dark" на элементе body

<img width="234" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/f0f47937-8ec1-45fc-b99c-e76e425ce50d">

3. Перейти в приложение, которое инжектит сервис PrizmThemeService (например, если оно показывает хинты). Пример приложений: <стенд>/market, <стенд>/security-settings и тд. После перехода в приложение тема меняется на дефолтную (светлую).

<img width="224" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/63b855d9-44e3-4b50-a958-0d85020979c0">

Причина заключается в том, что в конструкторе сервиса "PrizmThemeService" выполняется метод с параметром el = undefined, в итоге элементу body устанавливается атрибут data-prizm-theme="light".
```ts
this.setToHtml(theme.theme, theme.el);

setToHtml(theme, el) {
  (el ?? this.rootElement)?.setAttribute(this.attThemeKey, theme);
}
```

![image](https://github.com/zyfra/Prizm/assets/17107421/7337bb67-dad7-4e2b-a66c-aa01747eeeca)

**Comment by ZurabDev** [comment]
Вопрос о втором шаге, как именно вы переключаете режим на начно? Вы используйте метода update у PrizmThemeService сервиса для установи ночной темы?

**Comment by RoxVell** [comment]
> Вопрос о втором шаге, как именно вы переключаете режим на начно? Вы используйте метода update у PrizmThemeService сервиса для установи ночной темы?

Да, именно так
