### ISSUE TITLE
[Feature] Перейти с :focus на :focus-visible для интерактивных элементов

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#1297]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Сейчас фокусное состояние у кнопок и прочих интерактивных элементов отображается не только при переходе через клавиатуру, но и по клику. Это не удобно: фокус отображается, но вроде бы избыточно.

Предлагаю для всех интерактивных элементов использовать `:focus-visible` вместо `:focus`. Так фокус будет отображаться только при переходе на элемент через клавиатуру.

**Comment by PrizmDS** [comment]
Так и нужно) Исправим

**Comment by ickisIckis** [comment]
Существуют технические ограничения для элементов input - даже при клике, на них устанавливается псевдокласс focus-visible.

**Comment by ickisIckis** [comment]
Focus visible для input будет рассмотрела в задаче #1225
