### ISSUE TITLE
[BUG] prizm/components - Контейнер содержимого SideBar не растягивается на всю высоту 

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#130]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[Dialog](http://doc.prizm.zyfra.com/components/dialogs/dialog)

### Версия

1.0.0-beta.28

### Описание проблемы

Содержимое диалога prizm-sidebar не растягивается на всю доступную высоту диалога. Это порождает проблему, изображённую на скрине:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/52266097/230096940-64d385d1-0d27-45ed-a319-d673245f5f39.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/52266097/230097408-c05ae088-d8c2-438a-8444-3d8f5c235b1b.png">

Здесь невозможно выровнять надпись по вертикали по центру диалога из-за этого. Плюс есть кейсы, где хотелось бы расположить некий блок в нижней части диалога.

**Comment by dkshichkovskiy** [comment]
@ZurabDev Не до конца поправлено. Внутри элемента `prizm-scrollbar` есть ещё `.content`, которым не управляет клиент. Этот блок тоже нужно растянуть на всю высоту.
![image](https://user-images.githubusercontent.com/52266097/233113362-1a1ce78d-6817-4d7f-8cd2-097e7e983815.png)

**Comment by AleksandrSibiakov** [comment]
Наблюдаю такую же проблему в приложении (кейс, когда только контент задан), так что внесу свои 5 копеек..

Мне кажется текущий лейаут (beta.35) для контейнера `display: grid; grid-rows: min-content 1fr min-content` слишком заточенный под 3 элемента, и если остается один елемент (контент в нашем случае), или просто нет хедера, то размерность смещается, получается для контента применяется `min-content`.

ИМХО лучше бы подошла структура контейнера `display: flex; flex-direction: column` + `header, footer { flex: 0 0 auto } content { flex: 1 1 0 }`. (не помню точно, но вроде у диалогов как раз что то подобное)
