### ISSUE TITLE
[BUG] PrizmInputNumberDefaultControlsComponent в PrizmInputNumber - некорректная высота контрола (50px вместо 44px)

### ISSUE THREAD

**Issue by kolynchick** [zyfra/Prizm#1308]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PizmInputNumber

### Проект в котором используется Prizm

Прикладная ОМ

### Скрин / Видео проблемы

Высота - 50px

![image](https://github.com/zyfra/Prizm/assets/12861107/9003d581-e3ad-4921-894a-6470bc273464)

В другом контроле высота 44px

![image](https://github.com/zyfra/Prizm/assets/12861107/94685c57-e757-41ae-bc87-096a7134316d)

### Воспроизведение проблемы

https://prizm.site/

**Comment by kolynchick** [comment]
Достаточно уменьшить высоту кнопок внутри PrizmInputNumberDefaultControlsComponent с 24px до 21px

**Comment by alexhawkins94** [comment]
@ZurabDev 
следствие https://github.com/zyfra/Prizm/issues/1179 
пофиксить оба
