### ISSUE TITLE
[Question] Настраиваемая подсказка для кнопки "Закрыть" компонента SideBar

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#131]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

SideBar

### Версия

1.0.0-beta.28

### Вопрос

Возможно ли добавить параметр в настройки SideBar, который позволял бы устанавливать текст-подсказку для кнопки закрытия окна (крестик в правом верхнем углу)?

**Comment by ZurabDev** [comment]
появиться дополнить параметр для контроля hint (к примеру closeHintText)

**Comment by badeevdm** [comment]
@ZurabDev проверял в версиях 1.0.0-beta.30 и 1.0.0-beta.35, не нашел парметра. Подскажи, пожалуйста, он реализован и если да, то какое у него имя?

**Comment by ZurabDev** [comment]
Header задепрекейтим, добавим props headerTemplate который будет менять весь хедер вместо с  кнопкой
