### ISSUE TITLE
[Feature] Добавить hint для элементов навигационного меню

### ISSUE THREAD

**Issue by algashev123zyfra** [zyfra/Prizm#1312]
### Библиотека
- [x] `@prizm-ui/components`
-

### Компонент

PrizmNavigationMenuComponent

### Предложение

На данный момент в навигационном меню элементы с большим названием урезаются в три точки, но при наведении на них не отрисовывается hint. Данный вопрос обсуждался с дизайнером, который в свою очередь сказал, что дизайн система подразумевает отрисовку хинтов в тех случаях, когда текст урезан.
![image](https://github.com/zyfra/Prizm/assets/142902249/7464806a-57d3-4cfb-80e8-4da640730d89)

**Comment by ickisIckis** [comment]
Связанная задача: https://github.com/zyfra/Prizm/issues/295

**Comment by ickisIckis** [comment]
#1216 дубликат
