### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by katkovergina** [zyfra/Prizm#1317]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_Название компонента или группы компонентов_

### Предложение

_Работаю в рамках задачи_

_Предлагаю сделать ..._

**Comment by alexhawkins94** [comment]
@katkovergina  ? ? ?

**Comment by katkovergina** [comment]
ошибка, сорри, закрываю

**Comment by katkovergina** [comment]
открыто по ошибке
