### ISSUE TITLE
[Int] Accordion. Отображение нижней границы панели в раскрытом аккордеоне

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1322]
На данный момент в раскрытом аккордеоне нет нижней границы у панели.
![image](https://github.com/zyfra/Prizm/assets/122870313/9a384a87-a771-4269-9c0d-4087e65a43f9)

В макетах в Фигме есть вариант без границы
![image](https://github.com/zyfra/Prizm/assets/122870313/904cb0db-dad0-4414-b396-1454abfa846b)

И есть вариант с границей. 
![image](https://github.com/zyfra/Prizm/assets/122870313/253db82b-9237-458b-99fe-a9c124336feb)

Плюс в описании компонента в анатомии отображена эта граница.
![image](https://github.com/zyfra/Prizm/assets/122870313/517e7106-22d1-42a6-9a4c-92fef50503d8)

Как правильно?

**Comment by PrizmDS** [comment]
Граница должна отображаться

**Comment by PrizmDS** [comment]
Предлагается сделать отображение нижний границы настраиваемым параметром
