### ISSUE TITLE
[Feature] Добавить hint для BackButton компонента Panel

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#1324]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Panel](https://prizm.site/components/panel#withBack)

### Предложение

Возможно ли добавить отображение хинта с кастомным текстом при наведении на кнопку "назад"?

**Comment by ickisIckis** [comment]
Для решения этой задачи в панели возможно реализовать кастомную кнопку назад.
например:
` <prizm-panel header="Да это же главный заголовок" subheader="А это подзаголовок">
    <div buttons>
      <button
            [icon]="'arrows-back'"
            [prizmHint]="hintText"
            (click)="myBackClick()"
            prizmIconButton
            appearanceType="ghost"
            appearance="secondary"
            size="m"
      ></button>
    </div>
  </prizm-panel>`
