### ISSUE TITLE
[BUG] @prizm-ui/components - Внешний вид текста-заполнителя в строке фильтрации таблицы

### ISSUE THREAD

**Issue by vadimRRV** [zyfra/Prizm#1328]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

https://doc.prizm.zyfra.com/components/table#datasource
Фильтрация в таблице

### Проект в котором используется Prizm

- ZQL https://jira.zyfra.com/wiki/display/ZQL/Zyfra+Quality+Lab

### Описание проблемы
Добрый день, шрифт в текстовых заполнителях строки фильтрации больше, чем заголовки таблицы. Заполнитель выглядит как основной текст, а не вспомогательный. Приложил скрин из реализации. Прошу рассмотреть возможность изменить внешний вид заполнителя.
![image](https://github.com/zyfra/Prizm/assets/158169092/9e370879-641a-422f-a34f-4e5209bec2db)
![image](https://github.com/zyfra/Prizm/assets/158169092/52bbe4e0-a003-4ea6-b418-aa2276df8a64)

**Comment by ickisIckis** [comment]
Размеры шрифтов в данный момент соответствуют дизайну, нужно провести исследование.
@PrizmDS

**Comment by PrizmDS** [comment]
Цвета будут скорректированы. 
Размер корректный
