### ISSUE TITLE
[Int] Navigation. Не хватает охранной зоны между кебабом и длинным названием айтема меню.

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1329]
Многоточие обрезки длинного названия и кебаб расположены близко друг к другу, как следствие при наведении курсора легко промахнуться и вызвать не тот тултип/хинт. 
Возможно стоит подумать про увеличение охранной зоны или пересмотреть взаимное расположение компонентов в такой ситуации.

![image](https://github.com/zyfra/Prizm/assets/122870313/5c529a2e-6268-4ffb-ac00-3bad70ef6c51)
![image](https://github.com/zyfra/Prizm/assets/122870313/330db824-4766-47e4-ba1f-d773346120fa)

**Comment by PrizmDS** [comment]
Отступы от любых контейнеров -- 8px
