### ISSUE TITLE
[Question] Как добавить дополнительные оси на график?

### ISSUE THREAD

**Issue by if1t** [zyfra/Prizm#1341]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [x] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Версия

NodeJS:

```
➜ node --version
v16.20.2
```

Dependencies:

`
"@prizm-ui/charts": "3.3.0",
"@prizm-ui/components": "3.3.0",
"@prizm-ui/core": "3.3.0",
"@prizm-ui/helpers": "3.3.0",
"@prizm-ui/icons": "3.3.0",
"@prizm-ui/theme": "3.3.0",
`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Вопрос

Как реализовать несколько осей для линий с разными единицами измерения на одном графике?
Пример:
![изображение](https://github.com/zyfra/Prizm/assets/93567572/c55d95cb-82aa-4fa3-ae6b-9f8dc187783b)

**Comment by ickisIckis** [comment]
Добрый день, для того, чтобы добавить дополнительные оси на график, нужно использовать DualAxis
Пример в документации antV:
https://g2plot.antv.antgroup.com/en/examples/dual-axes/dual-line/#dual-line
