### ISSUE TITLE
[BUG] @prizm-ui/components - <prizm-navigation-menu> При очистке поля ввода появляется ошибка

### ISSUE THREAD

**Issue by digital-plant-guard** [zyfra/Prizm#1344]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент
Prizm v3.10.0
https://prizm.site/components/navigation-menu

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/126816006/c4d934ee-534d-4633-9f30-b3196a141df7)

![image](https://github.com/zyfra/Prizm/assets/126816006/b2a0a671-933b-44a4-9055-52fd9dd932ce)

### Воспроизведение проблемы

https://stackblitz.com/edit/ngx-14-title-demo-enp5ng?file=src%2Fapp%2Fapp.component.html

### Описание проблемы

При очистке поля ввода появляется ошибка.

_Шаги воспроизведения_:

1. Перейти на сайт https://prizm.site/components/navigation-menu
2. Ввести текст в поле поиска
3. Нажать кнопку очистить 

В консоли появляется ошибка "Cannot read properties of null (reading 'toLowerCase')"

**Comment by ickisIckis** [comment]
#1213

**Comment by ickisIckis** [comment]
По согласованию с @PrizmDs поведение поиска будет исправлено:
при пустом значении поиска и до его начала в списке будут отображены все элементы. Описания будут исправлены с #1352
