### ISSUE TITLE
[BUG] @prizm-ui/components-prizmSwitcher - нет выделения задизейбленного активного элемента

### ISSUE THREAD

**Issue by gustav2775** [zyfra/Prizm#1348]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [Х] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Switcher 

### Версия

@prizm-ui/components@3.11.0

### Скрин / Видео проблемы

Дизайн Switcher
![image](https://github.com/zyfra/Prizm/assets/71187404/f1203079-13a6-4c8b-a851-e76b1c01b5b3)

Фактическое. Заблокированные все свичеры, активный свитч первый
![image](https://github.com/zyfra/Prizm/assets/71187404/6fdfd562-ffef-440e-9eed-b21945ff1598)

### Воспроизведение проблемы

Пример:

https://prizm.site/components/switcher/Live_demo?tuiMode=null&disabled=true

### Описание проблемы

Представление служит только для просмотра инфы, в нем есть  Switcher.
 Не возможно определить актиный свич

**Comment by ickisIckis** [comment]
@PrizmDS, сейчас свитчер умеет менять тип кнопок: ему можно прокинуть все доступные варианты appearanceType и appearance. Надо изучить этот момент: как должны разные типы кнопок в свитчере себя вести в состоянии ative+disable

**Comment by ickisIckis** [comment]
После обсуждения с @gustav2775, выяснили, что с табами все хорошо.
