### ISSUE TITLE
[Feat] @prizm-ui/components - Добавить возможность локализация текста подсказок в директиве prizmInputStatusText.

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#1354]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

@Directive prizmInputStatusText

### Версия

```
@prizm-ui/components 1.15.0
```

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/20378994/987faaff-9f08-47a7-b162-7de31ada3aef)

### Описание проблемы
Отсутствует локализация текста подсказок в директиве prizmInputStatusText.

**Comment by ickisIckis** [comment]
Добрый день, такая задача сейчас есть как раз в работе. Скорее всего, будет в версии 4.0

Чтобы не ждать фикса, пока можно воспользоваться кастомными текстами для локализации:
<prizm-input-layout>
...
</prizm-input-layout >

**Comment by NikoStV** [comment]
Спасибо! Сейчас так и используем.
