### ISSUE TITLE
[BUG] @prizm-ui/components - InputNumber - ломает обновление состояние контролов форме 

### ISSUE THREAD

**Issue by gustav2775** [zyfra/Prizm#1358]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputNumber

### Версия

3.11.0

### Скрин / Видео проблемы

версия призм 3.0.0

[Screencast from 2024-02-08 10:00:34 PM.webm](https://github.com/zyfra/Prizm/assets/71187404/0a1669f4-cff8-4b92-936f-104915ce1ab2)

версия призм 3.11.0

[Screencast from 2024-02-08 10:02:50 PM.webm](https://github.com/zyfra/Prizm/assets/71187404/7434b7dd-01d6-47ab-8ea5-89594ce0d286)

![image](https://github.com/zyfra/Prizm/assets/71187404/f1935a1d-14af-4e38-b81f-2e21f3412a6d)

### Воспроизведение проблемы

Пример:
 
1. Создать форму, объявить в ней контролы A и B
2. На форму повесить валидацию,  значение контрола А > значение контрола B

const formValidator = (): ValidatorFn => {
  return form => {
    if (!form) return null;

    const a = form.controls.a;
    const b = form.controls.b;

    if (!Number.isInteger(period.value) || !Number.isInteger(offset.value)) {
      return null;
    }

    if (a.value > b.value) {
      a.updateValueAndValidity({
        onlySelf: true
      });
      b.updateValueAndValidity({
        onlySelf: true
      });

      return null;
    }

    if (offsetInSec > MAX_SECONDS_OFFSET) {
      offset.updateValueAndValidity({
        onlySelf: true
      });
    } else {
      a.setErrors({
        b: true
      });
    }

   b.setErrors({
      b: true
    });
    a.markAsTouched();
    b.markAsTouched();

    return {
      a: true,
      b: true
    };
  };
};

3. Добавить знаки + или  -

### Описание проблемы

1. После первого изменения состояния валидации на всех контрола формы перестает обновления состояния. 
2. Появилась возможость воодить знаки + и - , в следствие в value после добавления знака приходит null

**Comment by ickisIckis** [comment]
Актуальна ли эта проблема в последних версиях v4?
@gustav2775,  какую версию вы используете сейчас?

**Comment by gustav2775** [comment]
> Актуальна ли эта проблема в последних версиях v4?
> @gustav2775,  какую версию вы используете сейчас?

После перехода на 4.3.5 проблема пропала.

**Comment by ickisIckis** [comment]
Спасибо, закрываем.
