### ISSUE TITLE
[Int] Navigation. Исправить верстку внутри названий вкладок предпросмотра кода для примера Groups

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1365]
-перейти к примеру groups
ФР: верстка текста на кнопках нарушена - текст наезжает на нижние границы, сверху большие отступы
![chrome_qDPgnr3mIK](https://github.com/zyfra/Prizm/assets/122870313/3c7d93e0-8c9c-4ae6-9026-7ccf82dba09e)

**Comment by ickisIckis** [comment]
Проблема связана с кнопками и расположением текста в две строки в них.
@alexhawkins94, @PrizmDS, требуется уточнить поведение в кнопках при переполнении.
Снимаю лейбл демо и навигация, тк касается не области демо, и не области навигации

**Comment by alexhawkins94** [comment]
Поресерчить поведение кнопок при уменьшении ширины зоны с кнопкой - сейчас текст переносится на вторую строку и кнопка увеличивается в высоту.


![image](https://github.com/user-attachments/assets/8383fe26-39b0-46b0-9f0e-2263853f2845)
![image](https://github.com/user-attachments/assets/2fd01e98-2618-4489-b420-07e46e225b7a)

**Comment by PrizmDS** [comment]
@ickisIckis, если уперлись в ширину контейнера -- водим текст в 3-точее и показываем хинт

**Comment by ickisIckis** [comment]
@PrizmDS, каким образом должен вести себя свитчер при переполнении?

**Comment by PrizmDS** [comment]
Макеты со сценарием поведения готовы. 
https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-5.0?m=auto&node-id=33757-101031&t=Lc9NHTRgMktmGXdh-1

**Comment by ickisIckis** [comment]
Реализация по свитчеру вынесена в отдельную задачу #2178 
т.к. выходит за рамки этого запроса
