### ISSUE TITLE
[Int] InputChips. Верстка инпута различается при SingleLine = true и при = false

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1370]
При изменении значения параметра singleLine меняется верстка инпута.

Label, placeholder меняют свои отступы от верхнего края инпута
Если есть чипсы в инпуте, то незначительно различается высота всего инпута 

Кажется, так быть не должно.

Параметр singleLine отвечает за отображения чипсов в одну(true) или несколько строк, и по идее не должен влиять на всё остальное.
@PrizmDS 

![chrome_jUJeaeFxn5](https://github.com/zyfra/Prizm/assets/122870313/7ee5ba65-2eb8-4913-9011-b2977c3a7c1a)
![chrome_sxsH3EMhpm](https://github.com/zyfra/Prizm/assets/122870313/0163deed-e773-48fc-85b8-b667bb39ab03)
![chrome_fS7jsrWcBO](https://github.com/zyfra/Prizm/assets/122870313/48a7fb0a-3bb4-4439-bf92-2c0def0805b3)
![chrome_w9mskF9M6E](https://github.com/zyfra/Prizm/assets/122870313/d6ce60ae-c62d-4700-a286-d7c9c6473ad5)
![chrome_CP3MUIb8Yq](https://github.com/zyfra/Prizm/assets/122870313/34ee356b-d1d3-4ec8-b5b6-9ca3ff162e1b)
![chrome_hxPHDcM7GD](https://github.com/zyfra/Prizm/assets/122870313/a3ba8d65-aa96-4856-bb44-a16fea746db8)

**Comment by ickisIckis** [comment]
В демо добавлены дополнительные отступы к чипсам, необходимо перенести их в реализацию компонента.
