### ISSUE TITLE
[BUG] @prizm-ui/components - InputNumber

### ISSUE THREAD

**Issue by RoxVell** [zyfra/Prizm#1383]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

InputNumber

### Проект в котором используется Prizm

NpiEditor

### Скрин / Видео проблемы

<img width="702" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/8fbaacaf-3832-45ac-8d66-ef9f44e84f76">

### Описание проблемы

Не меняется размер инпута при установке значения size в 'm' в случае использования контролов prizm-input-number-auxiliary-controls, при этом горизонтальные контролы отображаются корректно

1. Зайти по адресу [prizm](https://prizm.site/components/input-number/Live_demo?tuiMode=null)

**Comment by ickisIckis** [comment]
вероятно, связано с #1308
