### ISSUE TITLE
[Int] InputDateTimeRange. В live demo не устанавливается время начала - прокидывается 00:00 вместо выбранного времени

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1388]
-перейти в live demo компонента input date time range
-установить дату начала и конца через дропдаун
-установить время начала и конца через дропдаун
ФР: вместо выбранного времени прокидывается 00:00
ОР: должно прокидываться выбранное время
![chrome_PL5OFePRLn](https://github.com/zyfra/Prizm/assets/122870313/be4075fd-0ac7-456c-adba-e155464b34ce)

**Comment by ickisIckis** [comment]
Не получается воспроизвести проблему на версии 4.3.1,
@alexhawkins94 нужно валидировать задачу

**Comment by alexhawkins94** [comment]
could not reproduce
