### ISSUE TITLE
[Feature] Реализовать TreeSelect компонент

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#1417]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Предложение

Необходим компонент Select с выпадающим списком в виде дерева со следующими возможностями:
1) single/multi select
2) поиск (при поиске должны разворачиваться при необходимости свёрнутые узлы)

Сейчас такой компонент можно собрать из Tree и DropdownHost, но не уверен, что с текущим функционалом удастся реализовать пункт 2. Плюс, кажется, такой компонент был бы полезен много кому, вряд ли такое подпадает под слово "кастом".

Дополнительно, в ZQL есть проработанные требования к данному компоненту. Могу скинуть разработке Prizm, по запросу.

**Comment by imonogarov** [comment]
Требования: https://jira.zyfra.com/wiki/pages/viewpage.action?pageId=286801496
