### ISSUE TITLE
[BUG] @prizm-ui/components - Неправильно работает min/max в InputLayoutDateTime

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#1421]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputLayoutDateTime

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 3.11.0
```

### Проект в котором используется Prizm

- _СОУ_

### Скрин / Видео проблемы

[screencast-prizm.site-2024.03.04-21_02_14.webm](https://github.com/zyfra/Prizm/assets/26089012/3dc5aa4e-f5f2-4506-9444-9668e9701144)

### Воспроизведение проблемы

_Шаги воспроизведения_:

1. Зайти по адресу https://prizm.site/components/input-layout-date-time
2. Долистать до примера Min Max Day With Time
3. Выбрать время 21:00
4. Ожидаемое поведение: выбрано 21:00, фактическое поведение: выбрано 18:30

Складывается впечатление, что Time берет ограничение независимо от даты. В live примере
min: 01.02.2022 09:00
max: 10.11.2025 18:30
Соответственно можно выбрать любой доступный день, но с 09:00 до 18:30

**Comment by alexhawkins94** [comment]
посмотрим какие были изменения, сходу не припоминаю, несколько версий назад работало нормально
@ZurabDev

**Comment by AsyaSokolova** [comment]
https://github.com/zyfra/Prizm/assets/17219726/6011cfb6-31d2-4861-b3e5-e558aee895dc
https://stackblitz.com/edit/stackblitz-starters-siklu7?file=src%2Fapp%2Fapp.component.ts

Нужен фикс min и max в версии 2х
