### ISSUE TITLE
[BUG] Table - при добавлении обводки на наведенную ячейку таблица некорректно отображается

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#1422]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Table

### Проект в котором используется Prizm

- СОУ

### Скрин / Видео проблемы

https://github.com/zyfra/Prizm/assets/17219726/569894ba-7d19-4d6d-bd75-4c33bb0342b1

### Воспроизведение проблемы

_Ссылка на stackblitz с минимальным воспроизведением_
Пример:

https://stackblitz.com/edit/stackblitz-starters-azklzp?file=src%2Fapp%2Fapp.component.ts

### Описание проблемы

Создана таблица с двумя зафиксированными слева колонками, при наведении на ячейку добавляется красная обводка. Если таблицу не прокручивать вправо, то при наведении на ячейку таблица отображается корректно, но если прокрутить таблицу вправо, то при наведении на ячейку таблица "прыгает" и видно как отображаются столбцы, которые "заехали" под закрепленные (видимо проблема с z-index)

**Comment by ickisIckis** [comment]
В данном примере проблема появляется из-за изменения размера ячейки таблицы на состояние hover.
В качестве решения предлагаю стабилизировать размер ячейки: либо добавить прозрачный border, в состоянии без hover, как тут:
https://stackblitz.com/edit/stackblitz-starters-vpd15z?file=src%2Fapp%2Fapp.component.scss

либо использовать внутренние тени, как это реализовано для ячеек с инпутами:
https://prizm.site/components/table#editableCol
