### ISSUE TITLE
[Question] PrizmCheckbox - некорректное выделение

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#1424]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

PrizmCheckbox

### Проект в котором используется Prizm

- СОУ

### Вопрос

Есть пример https://stackblitz.com/edit/stackblitz-starters-zrjbdz?file=package.json
Требуется нажать на кнопку "Создать операцию", выбрать "Создать несколько операций", открыть значок фильтра, установить несколько чекбоксов. Все корректно работает. 

https://github.com/zyfra/Prizm/assets/17219726/cb3f7600-fff2-403d-a75c-ef577f7bb221

Такая же реализация используется у нас в проекте (архитектура приложения также воспроизведена на stackblitz),  но возникает ошибка в консоли, из-за этого чекбоксы не устанавливаются, также форма поиска работает некорректно. 

https://github.com/zyfra/Prizm/assets/17219726/a52e25b3-0bf7-447c-8a1c-fdefb6ee37fe

Ошибка в консоли: 
[localhost-1709628455950.log](https://github.com/zyfra/Prizm/files/14492715/localhost-1709628455950.log)

Просьба помочь разобраться в причине проблемы

**Comment by imonogarov** [comment]
У нас не воспроизводится, скорее всего это неправильное использование групп
