### ISSUE TITLE
[Int] Card. В live demo задублировано значение big-right для свойства shadow

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1434]
-перейти в live demo компонента card
-раскрыть дропдаун для свойства shadow
ФР: в дропдауне задублировано значение big-right
ОР: отсутствие дубля значения 

![image](https://github.com/zyfra/Prizm/assets/122870313/f5b04c03-2766-4f53-ae62-919bb84ee34c)

**Comment by AleksandrSibiakov** [comment]
Замечу, что нет варианта `None`, хотя такая опция доступна через enum
