### ISSUE TITLE
[Int] Tabs. Рамка фокуса обрезается справа при одновременном hover+focus для contained tab

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1435]
-перейти к примеру contained tabs компонента tab
-сделать фокус на любой таб в примере при помощи tab
-навести ховер на этот же таб
ФР: При одновременном состоянии фокуса и ховера на contained tab происходит обрезка правой границы у фокуса
ОР: рамка не должна обрезаться

![image](https://github.com/zyfra/Prizm/assets/122870313/24b989f8-7ab8-452f-997e-389809bb2740)

**Comment by ickisIckis** [comment]
связано с #1435

**Comment by ickisIckis** [comment]
@alexhawkins94, нужно провреить актуальность, кажется, чинили

**Comment by alexhawkins94** [comment]
уже исправлено

5.2 4.7
