### ISSUE TITLE
[Int] CalendarRange. Поправить верстку экранов выбора года и месяца

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1445]
Перейти к CalendarRange
На левом календаре раскрыть выбор месяца
На правом календаре раскрыть выбор года
Сравнить взаимное расположенние элементов
ФР: месяцы и годы сдвинуты относительно друг-друга, выглядит не красиво
![image](https://github.com/zyfra/Prizm/assets/122870313/b3050f31-5964-46fc-80a1-3e4e3da110b3)

https://www.figma.com/file/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8E-Prizm.-%D0%A1omponent-base-4.0?type=design&node-id=25937-25929&mode=design&t=HUfiwwx5JKDD6gHN-0

учесть https://github.com/zyfra/Prizm/issues/1242

**Comment by ickisIckis** [comment]
Необходимо исправить верстку для кнопок - между ними не должно быть отступов, размеры должны быть не относительными, а фиксированными.
@PrizmDS
