### ISSUE TITLE
[Int] Calendar. На шевронах переключения месяца висит дефолтный хинт, нужно использовать наш собственный.

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1457]
Calendar - на шевронах переключения месяца висит дефолтный хинт, нужно использовать наш собственный.

![image](https://github.com/zyfra/Prizm/assets/122870313/c5639628-794a-4347-a646-28aad1b5daec)

**Comment by ickisIckis** [comment]
@PrizmDs, необходимо уточнить позиционирование хинта
