### ISSUE TITLE
[Feature] PrizmNavigation: Добавить поддержку иконки в нераскрывающемся элементе

### ISSUE THREAD

**Issue by ZyfraOlgaPalkina** [zyfra/Prizm#1477]
### Библиотека

- [ ] `@prizm-ui/core`
- [x ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmNavigation
https://prizm.site/components/navigation

### Предложение

В данный момент иконка выводится только у раскрывающейся группы элементов:
![nav-actual](https://github.com/zyfra/Prizm/assets/130983761/08edacfb-b90b-478f-8101-db1cb04decc2)

Просьба реализовать поддержку иконки в обычном элементе (prizm-navigation-item-simple.component):
![nav-expected](https://github.com/zyfra/Prizm/assets/130983761/5003aa3b-755c-4306-be66-d80f0f3e6cb1)

**Comment by ickisIckis** [comment]
@PrizmDS, нужно подтвердить, что это по дизайну
