### ISSUE TITLE
[Feature] Заменить T(большое) на t(малое) в компоненте prizm-input-layout-date-relative

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#1479]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

prizm-input-layout-date-relative

### Предложение

В компоненте присутствует возможность выбора значения "полночь текущих суток T(большое)". Сервис ZifTime не поддерживает T(большое), он умеет работать только с t(малое) 
![image](https://github.com/zyfra/Prizm/assets/20378994/ca0eeb44-cefb-4168-8cb6-8be8294f89c6)
Заменить T(большое) на t(малое)

**Comment by imonogarov** [comment]
@PrizmDS просьба рассмотреть предложенный вариант

**Comment by PrizmDS** [comment]
Добавили иконку с t, добавили пункт в меню. Предлагаю сделать функционал скрытия элемента меню

**Comment by imonogarov** [comment]
@PrizmDS пришли иконку @ZurabDev

**Comment by ZurabDev** [comment]
@PrizmDS нужна иконка для 24 и 16

**Comment by imonogarov** [comment]
@PrizmDS нужна ссылка на иконку

**Comment by PrizmDS** [comment]
16: https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-5.0?m=auto&node-id=39212-9548&t=qAflR26vgDLLtjLH-1

24: https://www.figma.com/design/dhv3tzSiwqo1ztD2pewr03/%F0%9F%92%8E-Prizm.-Icons-24px?m=auto&node-id=7833-40&t=qoktj3XJyMh3H3nE-1
