### ISSUE TITLE
[BUG] prizm/components - Unable to write a reference to PrizmHintOptions

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#148]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

PrizmHint

### Версия

Операционная ситема:

`Windows 11, etc`

Браузер:

`Google Chrome Версия 111.0.5563.147 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v14.19.3
```

Dependencies:

```
➜ npm ls @prizm-ui/zyfra-components

@prizm-ui/zyfra-components 0.1.1
```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/20378994/230923302-3ef3ce71-971b-4375-becc-5bab903dab41.png)

### Описание проблемы

В проекте есть пакет , в который подключен PrizmButtonModule и PrizmHintModule. При попытке собрать пакет возникает ошибка указанная на скриншоте.

**Comment by NikoStV** [comment]
не собирается при такой конфигурации tsconfig.json 
`
{
  "compileOnSave": false,
  "compilerOptions": {
    "paths": {
      "@digital-plant/toolbar": [
        "dist/digital-plant/toolbar/digital-plant-toolbar",
        "dist/digital-plant/toolbar"
      ]
    },
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "noUnusedParameters": true,
    "noPropertyAccessFromIndexSignature": true,
    "skipLibCheck": false,
    "skipDefaultLibCheck": false,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
`

**Comment by ZurabDev** [comment]
Связана с другой задачей, закрываем текущую
