### ISSUE TITLE
[Int] Table. Отсутствует фокус на контролах сортировки, фильтрации, редактирования, шевронах табличного дерева

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1486]
В таблицах нет фокуса для контролов фильтра, сортировки, редактирования? шевронах дерева в таблице - возможно потому что используются просто иконки, а не кнопки.

![chrome_CVUKYZ6hPk](https://github.com/zyfra/Prizm/assets/122870313/4c1f0759-2e48-483f-a54c-3fb305224aef)
![chrome_MnXl0J6ixo](https://github.com/zyfra/Prizm/assets/122870313/37af4c21-af14-4973-adab-e5a80602e683)
![chrome_p8tkqxfPZI](https://github.com/zyfra/Prizm/assets/122870313/dd65e054-13ba-4984-9cda-4b5e1aec28b3)
![image](https://github.com/zyfra/Prizm/assets/122870313/76515558-39ab-4b06-990b-a8d7d9901d6e)

**Comment by PrizmDS** [comment]
лучше сделать фокус как у кнопки

**Comment by PrizmDS** [comment]
![image](https://github.com/zyfra/Prizm/assets/131430040/0840696b-1e60-4207-94d6-52e831a59eb4)

**Comment by PrizmDS** [comment]
Для всех Ghost Button в элементе Table не должно быть фона при состоянии Hover

**Comment by ickisIckis** [comment]
> Для всех Ghost Button в элементе Table не должно быть фона при состоянии Hover

Требуется уточнение ТЗ и решения
