### ISSUE TITLE
[Int] Icons & Table. В column settings примере компонента Icons иконка "lock" отображается в размере 11х13 вместо 16х16

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1487]
![chrome_Bjzs5MOHcp](https://github.com/zyfra/Prizm/assets/122870313/15e6bcbb-f870-4592-af3a-978a9114be50)
![chrome_W0sBtbfmiJ](https://github.com/zyfra/Prizm/assets/122870313/7b9d00d7-95c1-4b1c-89e1-1f36e448dd82)
![chrome_qjKVg4EzTW](https://github.com/zyfra/Prizm/assets/122870313/9eb9f749-69ec-483d-8a03-8aedf01ca948)

**Comment by afedoroff** [comment]
В тэге path хранится сама векторная картинка. Она оборачивается в тэг svg, который уже 16х16. Так у всех векторных, пример ниже. Думаю можно закрыть
![image](https://github.com/zyfra/Prizm/assets/86869655/3875c720-4250-43fc-b05d-a6d6e260609f)

![image](https://github.com/zyfra/Prizm/assets/86869655/c5227e84-b882-4e29-aa01-d3f63f064ac3)
![image](https://github.com/zyfra/Prizm/assets/86869655/8ea5ce4b-5f20-4586-96ae-f7e30e09ea19)
