### ISSUE TITLE
[Int] Charts. Bar. При переключении темы начинает отображаться ось Х

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1490]
На версии 4.Х в изначальном состоянии по дефолту не отображается ось Х у графика Bar.
После переключения темы ось появляется и отображается в обоих темах.

![chrome_3q1U1xIUmn](https://github.com/zyfra/Prizm/assets/122870313/805f086b-f586-4643-957b-5f8d65bf0910)
![chrome_7WKkavLXcy](https://github.com/zyfra/Prizm/assets/122870313/79bd22b1-0f6f-46c3-8dd9-eb3e224f8425)
![chrome_vjrmMv7Gjz](https://github.com/zyfra/Prizm/assets/122870313/52025cc4-e8d4-48ca-a5cc-d51f669fb4f4)

**Comment by ickisIckis** [comment]
Ось x должна присутствовать на графике по умолчанию - по согласованию с @PrizmDS
