### ISSUE TITLE
[BUG] @prizm-ui/components - Switcher используемый в Cron, неправильно отображает выбранный таб

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#1494]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Cron](https://prizm-v3.web.app/components/cron)

### Версия

@prizm-ui/components: "3.11.0"

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/48792714/b6b81e4d-e7ab-4540-a51e-df3ba9efa42d)
![image](https://github.com/zyfra/Prizm/assets/48792714/32f49f38-d253-47a8-aa81-b6afe3029556)

### Воспроизведение проблемы

![image](https://github.com/zyfra/Prizm/assets/48792714/ae602f67-fa6d-4333-8c0e-9bf93aed7125)
https://stackblitz.com/edit/angular-5xfwv3?file=src%2Fapp%2Fapp.component.ts

Не смог подключить стили, но в данном демо привере можно увидеть, что выбранный по умолчанию таб это "Часы". И контент под табами выбран верно, но сам элемент в Switcher не отмечен как активный (ng-reflect-is-active="false").

### Описание проблемы

Отсутсвуют стили для выбранного элемента из Switcher, используемый в Cron компоненте. Кейс воспроизводится только, если передать в Cron не все возможные варианты табов, например, убрать минуты. В таком случае, если передать в Input св-во (selected) первый элемент из массива tabs, то он не будет подсвечен как активный. Например, 

```html
<prizm-cron
  #item
  [tabs]="['hour', 'day', 'year']"
  [(period)]="period"
  [selected]="'hour'"
></prizm-cron>
```

_Шаги воспроизведения_:

1. Добавить Cron компонент на страницу
2. В св-во tabs передать ['hour', 'day', 'year']
3. В св-во selected передать 'hour'

Также это поведение можно увидеть тут https://doc.prizm.zyfra.com/components/cron/Live_demo?tuiMode=null. Если перейти на вкладку Live demo, пример сконфигурирован так, чтобы по умолчанию была открыта вкладка "Часы". Она действитетльно открыта, но таб не подсвечен.

**Comment by alexhawkins94** [comment]
@badeevdm в более свежей 4.0 версии на нашей витрине ок? https://prizm.site/components/cron/

**Comment by badeevdm** [comment]
> @badeevdm в более свежей 4.0 версии на нашей витрине ок? https://prizm.site/components/cron/

Да, в 4.x не воспроивзодится, кажется

**Comment by alexhawkins94** [comment]
@badeevdm в 4.0 чинили это направленно :) 
ожидаете ли это исправление в 3.Х ?

**Comment by badeevdm** [comment]
@alexhawkins94 нет, достаточно, что в версии 4.0 исправлено, спасибо.

**Comment by badeevdm** [comment]
Решено.

**Comment by alexhawkins94** [comment]
переоткрываем т.к. обнаружен критичный баг
