### ISSUE TITLE
[Feature]  - Как копировать название иконки на сайте http://prizm.site/components/icon не интуитивно понятно

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#150]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

icon

### Предложение

Что бы скопировать иконку нужно кликнуть по ее названию 2 раза, но в таком случает не понятно что скопировано, полного названия иконки не видно, если кликнуть по названию, что выделено не видно.

Возможно сделать? 
- При клике на название отображать его полностью
- При двойном клике отображать полностью выделенный текст. 
- При двойном клике копировать название в буфер, сопровождать действие уведомлением (Скопировано в буфер)

**Comment by ZurabDev** [comment]
Да. Тоже хотели давно сделать, руки не доходили. Займемся в ближайшее время

**Comment by ZurabDev** [comment]
При клике значение копируется. Доступно в 30 версии
