### ISSUE TITLE
[Int] Charts. Искажаются заданные в цветовой схеме цвета, вместо заданного в коде #339999 используется #329393

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1505]
В цветовой схеме задан цвет '#339999', https://www.color-hex.com/color/339999
В реальности вместо него отображается чуть другой по оттенку цвет 329393  https://www.color-hex.com/color/329393

Аналогично для всех остальных цветов

реальность
![chrome_y6U2IEUF4n](https://github.com/zyfra/Prizm/assets/122870313/f0888585-8687-433d-817a-f7608b797280)

макет
![chrome_iHVC9xpAnw](https://github.com/zyfra/Prizm/assets/122870313/7f2ee5f4-9792-4592-be09-8d280b6e8d8d)

**Comment by ickisIckis** [comment]
https://github.com/antvis/G2/issues/6158 -  issuie у antv g2plot
