### ISSUE TITLE
[BUG] @prizm-ui/components - Replacing the `context` object of an `EmbeddedViewRef` is deprecated

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#1506]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_PrizmTableRowInitDirective_ (замечено, возможно другие, где напрямую меняется `EmbeddedViewRef.context`)

### Версия

```
@angular/core 17.3.0
@prizm-ui/components 4.0.0
```

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/2631748/9f4ca7cb-d6c4-4cff-889a-b9c8be9b1d01)

### Воспроизведение проблемы

Открыть консоль на страницей демо таблицы

### Описание проблемы

Данный функционал помечен устаревшим в @angular/core@17 и рекомендовано поменять реализацию на Proxy, либо мутация существующего установленного контекста

**Comment by alexhawkins94** [comment]
Пример filter
Фильтрация отрабатывает не корректно, отображается ряд из скрытой категории  и не отображается из не скрытых категорий  - скрыта категория Premium, отображается Name 1
![chrome_tqRWokCxss](https://github.com/zyfra/Prizm/assets/122870313/a9695040-a058-4ade-8653-1b30939ab956)
![image](https://github.com/zyfra/Prizm/assets/122870313/5731dc41-e3b9-47ce-9596-81c597b31b13)

**Comment by alexhawkins94** [comment]
Base sort
Не происходит сортировка ни в каком из столбцов
![image](https://github.com/zyfra/Prizm/assets/122870313/2b986e52-d505-48b4-8d4d-eebd46d6c034)

**Comment by alexhawkins94** [comment]
Pagination
Не работает пагинация в таблице
При переключении между страницами отображаются одинаковые данные
![chrome_F0k4UMDiUL](https://github.com/zyfra/Prizm/assets/122870313/399756c1-9b68-43a6-9c38-31ada07b5175)
![chrome_F19SSFMbmW](https://github.com/zyfra/Prizm/assets/122870313/3b4595db-9ed9-4060-b8ff-680711353801)

**Comment by alexhawkins94** [comment]
Editable raw
Не удаляется выбранный ряд
![chrome_F19SSFMbmW](https://github.com/zyfra/Prizm/assets/122870313/6122043e-d113-410c-9b4a-f19b374a812c)
