### ISSUE TITLE
[Feature] - В prizmIconButton используются иконки помеченный как deprecated

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#151]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Вопрос

В prizmIconButton используются иконки помеченный как deprecated. Когда будут использовать актуальные иконки. 
![image](https://user-images.githubusercontent.com/20378994/230930131-ec6a6110-547d-4d5b-a27a-83156f9273b5.png)

**Comment by ZurabDev** [comment]
Теперь возможно передавать туда шаблон.
Добавлен пример 
<img width="997" alt="CleanShot 2023-04-14 at 14 41 29@2x" src="https://user-images.githubusercontent.com/75216044/232034536-363d25eb-a2c8-4c98-b375-611f37262d87.png">

Доступно в 30 версии
