### ISSUE TITLE
[BUG] @prizm-ui/components - PrizmInput - отсутствует подсказка на кнопке "Очистить"

### ISSUE THREAD

**Issue by kolynchick** [zyfra/Prizm#1515]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](https://prizm.site/components/input)
2.  В секции "Basic Example", в поле Input ввести произвольные данные
3. Навести мышкой на иконку "Очистить"

Ожидаемый результат:

Высвечивается PrizmHint с текстом "Очистить"

Фактический результат:

Подсказка отсутствует

P.S. Не забудьте добавить текст в русскую и английскую локализацию :)

**Comment by ickisIckis** [comment]
Такой сценарий, если требуется, можно реализовать на стороне проекта. Пример:
https://prizm.site/components/input#custom-clear-button

**Comment by kolynchick** [comment]
> Такой сценарий, если требуется, можно реализовать на стороне проекта. для этого необходимо к prizm-input-layout добавить шаблон с кнопкой [clearButton]="clearButtonTemplate"
> 
> Пример подробнее: https://prizm.site/components/input#custom-clear-button

Можно, но имплементировать кнопку заново ради добавление подсказки - как по мне - сомнительно. Было бы круто, если бы Prizm был более дружелюбным к пользователю и давал больше информации о действиях)

**Comment by ickisIckis** [comment]
В актуальных описаниях работы компонента такое требование отсутствует, поменяю тип задачи на запрос на функционал.  
@PrizmDs, необходимо уточнить требования к этой задаче. Должно ли такое поведение быть по умолчанию.

**Comment by PrizmDS** [comment]
Вообще это дружелюбное поведение для компонента, желательно интегрировать его

**Comment by ickisIckis** [comment]
> Вообще это дружелюбное поведение для компонента, желательно интегрировать его

нужно добавить описание поведения, с текстами подсказок и уточнить по поведению: всегда ли показываем или нужно добавить возможность отключения + значение delay для хинта,

**Comment by PrizmDS** [comment]
@ickisIckis Хинты снизу. Всегда изначально показываем. Функцию отключения нужно сделать. Дилей стандартный.

**Comment by kolynchick** [comment]
Предложу так же закрепить рекомендацию для других компонент, в которых есть кнопки для побуждения к действию
