### ISSUE TITLE
[BUG] @prizm-ui/components - InputCarousel иконки смещены

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#1529]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_InputCarousel_

### Версия

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 4.1.0
```

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/2631748/cb3869df-e6d3-486b-b184-532d3f56b12b)

### Воспроизведение проблемы

https://prizm.site/components/input-carousel/Live_demo?tuiMode=null

### Описание проблемы

Иконки не выровнены. справа отступ больше чем слева от края, и текст получается тоже прижат больше справа. На демо сайте они шире, и не так заметно.

**Comment by alexhawkins94** [comment]
справедливо для остальных инпутов тоже
