### ISSUE TITLE
[BUG] prizm/components - InputDateTime ограничивает ввод времени

### ISSUE THREAD

**Issue by javadoffuad** [zyfra/Prizm#154]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[InputDateTime](http://prizm.site/components/input-date-time)

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v14.15.0
```

Dependencies:

```
➜ npm ls @prizm-ui/zyfra-components

@prizm-ui/zyfra-components 1.0.0-beta.29
```
### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/7090093/231169596-10f458be-319a-4639-85b2-f3de5e2a199c.png)

### Описание проблемы

_Делаю задачу_

_Есть проблема следующего характера:_

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](http://prizm.site/components/input-date-time)
2. Текущее время 15:56, как скриншоте
3. Ввести текущее время (час) в поле: 01.01.2020 15:00
4. символ "5" нельзя вводить, видимо на стороне компонента дата и время приводится к UTC формату.

**Comment by ZurabDev** [comment]
У вас действительно последняя версия? Не можем воспроизвести

**Comment by javadoffuad** [comment]
> У вас действительно последняя версия? Не можем воспроизвести

проверяю на сайте призмы:
http://doc.prizm.zyfra.com/components/input-date-time

**Comment by alexhawkins94** [comment]
> > У вас действительно последняя версия? Не можем воспроизвести
> 
> такое же поведение наблюдается на сайте призмы: http://doc.prizm.zyfra.com/components/input-date-time

там пока еще 28ая старая версия с проблемами

**Comment by alexhawkins94** [comment]
а вот на https://prizm.site/components/input-date-time   не можем воспроизвести, там 29ая 
![image](https://user-images.githubusercontent.com/122870313/231454590-98d27505-8f89-4fd6-8a28-65ac00943202.png)
