### ISSUE TITLE
[BUG] prizm/components - InputDateTime значение отображается не сразу

### ISSUE THREAD

**Issue by javadoffuad** [zyfra/Prizm#155]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[InputDateTime](http://doc.prizm.zyfra.com/components/input-date-time)

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v14.15.0
```

Dependencies:

```
➜ npm ls @prizm-ui/zyfra-components

@prizm-ui/zyfra-components 1.0.0.beta.29
```

### Скрин / Видео проблемы

В таблице есть список мероприятий, после выбора мероприятия, актуализируется форма
![image](https://user-images.githubusercontent.com/7090093/231400168-9068acc5-c090-4067-88b8-4338a38442ec.png)

В поле дата установлено, но не отображается
![image](https://user-images.githubusercontent.com/7090093/231412440-b9a93549-d753-4c10-8b63-0b2eb8d0bcfd.png)

Установил фокус в поле,  дата появилась
![image](https://user-images.githubusercontent.com/7090093/231412585-d280ecb4-4fc3-435d-a260-c054dcb4fcbb.png)

### Пример кода:

```Javascript
class SomeComponent {
  public formControl = new FormControl<Date | null>(null);
  
  @Input() set currentEvent(value: {id: string, name: string; timestamp: number}) {
    const date = value.timestamp ? new Date(value.timestamp) : null;
    this.formControl.setValue(date);
  }
}
```

```Html
<prizm-input-date-time
    [label]="'The date time'"
    size="m"
    [formControl]="formControl"
    timeMode="HH:MM"></prizm-input-date-time>
```

**Comment by dkshichkovskiy** [comment]
@ZurabDev Стоит отметка `1.0.0-beta.30`, но в этой версии баг всё ещё воспроизводится.

**Comment by javadoffuad** [comment]
@ZurabDev Проверил на 1.0.0 версии, но проблема к сожалению все еще остается, откройте пожалуйста, тикет.

**Comment by javadoffuad** [comment]
использовал `prizm-input-layout-date-time`

```html
<prizm-input-layout
    size="m"
    [label]="'The date time'">
    <prizm-input-layout-date-time
      timeMode="HH:MM"
      [formControl]="formControl">
    </prizm-input-layout-date-time>
</prizm-input-layout>
```

**Comment by dkshichkovskiy** [comment]
Проверил на версии 1.2.4, проблема не актуальна.
