### ISSUE TITLE
[BUG] @prizm-ui/components - InputLayoutDateTime можно ввести неправильное время

### ISSUE THREAD

**Issue by MrDywar** [zyfra/Prizm#1572]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

InputLayoutDateTime

### Версия

@prizm-ui/components: "3.12.0"

### Скрин / Видео проблемы

![9999](https://github.com/zyfra/Prizm/assets/14540197/0587aa77-6bb5-499c-bc13-25830780c235)

### Воспроизведение проблемы

https://prizm-v3.web.app/components/input-layout-date-time

### Описание проблемы

В примере "Min Max Day With Time" если изменять время удаляя одну цифру за другой при помощи кнопки Backspace и заменяя ее например цифрой 9, то можно указать время равное 99:99. Что и продемонстрировано в приложенной GIF.

**Comment by alexhawkins94** [comment]
а в 4.х не воспроизводится вроде, посмотрим.

**Comment by imonogarov** [comment]
На актуальных версиях не воспроизводится
