### ISSUE TITLE
[BUG] Toggle - не поддерживает formControl на stackblitz

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#1579]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Toggle

### Версия

@prizm-ui/components 2.13.0

### Проект в котором используется Prizm

- СОУ

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/17219726/472913cd-ea60-4a42-9dac-74f6d28db9e7)

### Воспроизведение проблемы

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.html

### Описание проблемы

При попытке использовать formControl для prizm-toggle возникает ошибка:

Can't bind to 'formControl' since it isn't a known property of 'prizm-toggle'.
1. If 'prizm-toggle' is an Angular component and it has 'formControl' input, then verify that it is part of this module.
2. If 'prizm-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by ickisIckis** [comment]
Проблема с примером на stackblitz
