### ISSUE TITLE
 [BUG] @prizm-ui/components - Не работает ручной ввод если установлено минимальное значение 

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#1580]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmInputNumberModule

### Версия

1.16, 2.13.0, 3.12.0, 4.1.2

### Описание проблемы

https://prizm.site/components/input-number/Live_demo?tuiMode=null
1. У компонента "Input number" установить параметры [min]="10", [max]="80"
2. Изменить значение с помощь ручного вводу, например ввести значение 24.

Результат: После ввода двойки значение сбрасывается на 10, если продолжить ввод и ввести 4, значение сбрасывается на 80.

Ожидаемый результат: Иметь возможность ручного ввода.

**Comment by ickisIckis** [comment]
@PrizmDs, необходимо уточнить ux

**Comment by PrizmDS** [comment]
Это бага. Поведение должно давать пользователю ошибиться и сообщить ему об этом. Допустимые значения должны отображаться в хинте
