### ISSUE TITLE
[FEATURE] @prizm-ui/components - Отсутствуют подсказки у иконок в меню PrizmNavigationMenuComponent

### ISSUE THREAD

**Issue by digital-plant-guard** [zyfra/Prizm#1589]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmNavigationMenuComponent, любая версия Prizm https://prizm.site/components/navigation-menu

### Описание проблемы

Нам в команду, в рамках дизайн ревью, завели баг на отсутствие хинтов у кнопок в компоненте меню. Готовы сделать PR в Prizm, но нам нужно знать текстовки для подсказок.

<img width="470" alt="image" src="https://github.com/zyfra/Prizm/assets/126816006/361de026-4aff-48f0-8928-0657437537e4">

**Comment by imonogarov** [comment]
@PrizmDS нужен текст подсказок

**Comment by PrizmDS** [comment]
![image](https://github.com/zyfra/Prizm/assets/131430040/1b4ce22e-90fe-4b1d-b215-2232e51dc993)
