### ISSUE TITLE
[BUG] @prizm-ui/components - `parentContainer` из `defaultOptions` игнорируется при открытии диалоговых окон

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#1602]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_AbstractPrizmDialogService_ (все диалоги)

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/2631748/e0140382-9787-43d8-9965-edaf60c35d76)

### Воспроизведение проблемы

_Ссылка на stackblitz с минимальным воспроизведением_
Пример:

https://stackblitz.com/edit/prizm-v4-issue-1602

### Описание проблемы

[По дизайн документам](https://www.figma.com/file/IEsKtY2w1cx6mvpy3hqB9O/%F0%9F%92%8E-Prizm.-Descriptions-v-1.0?type=design&node-id=7917-450837&mode=design&t=LWaKGa2seQT7fJ9X-4) необходимо отображать сайдбары внутри контейнера приложения. При переопределении `defaultOptions.parentContainer` сервиса (через наследование, либо другим способом) данное значение при открытии игнорируется и всегда берется из параметров, переданных напрямую при вызове `service.open(..., options)`:

https://github.com/zyfra/Prizm/blob/5bb267e6eca7e28d1026c316cd223ac9bd091151/libs/components/src/lib/abstract/dialog.service.ts#L75

*Ожидаю*

* все опции из `defaultOptions` используются при открытии окон, если не переопределены явным образом через параметр `options` метода `AbstractDialogService.show`
* [optional] Возможность задать дефолтные опции для диалоговых окон через `InjectionToken` (раздельно для SidebarService/DialogService/etc.)

P.S. так же похоже изменения темы не меняют тему внутри диалоговых окок (в частности сайдбара, см. скриншот) - легко воспроизвести [на демо сайте](https://prizm.site/components/dialogs/sidebar) - открыть сайдбар и изменить тему через переключатель в нав-меню

**Comment by AleksandrSibiakov** [comment]
@ZurabDev Насколько я могу судить, основная проблема, описанная в задаче, не исправлена - а именно `parentContainer` берется из `options` (аргумента функции), где нет значения `defaultOptions`

https://github.com/zyfra/Prizm/blob/29cb58b60b3e9f04d5411cac8dc78ff28394f5e2/libs/components/src/lib/abstract/dialog.service.ts#L71

То же верно и для значений используемых ниже данной строчки - `zIndex` & `overscroll`

**Comment by AleksandrSibiakov** [comment]
Создал PR с правкой - он должен гарантировать, что все значения из `defaultOptions` будут учтены ниже по контексту

**Comment by ZurabDev** [comment]
Спс.

Я добавил пример как лучше переопределять опции дефолтные, так как в том примере stakblitz переопредлялись опции не правильно, не поддерживанемым способом

**Comment by AleksandrSibiakov** [comment]
Да, но это была не основная проблема - основная, это то что некоторые значения из defaultOptions не применялись вовсе
