### ISSUE TITLE
[BUG] prizm/components - MultiSelect После сброса значения обязательного поля, рамка поля не становится красной

### ISSUE THREAD

**Issue by javadoffuad** [zyfra/Prizm#161]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[MultiSelect](https://prizm.site/components/dropdowns/multi-select#validators)

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v14.15.0
```

Dependencies:

```
➜ npm ls @prizm-ui/zyfra-components

@prizm-ui/zyfra-components 1.0.0-beta.29
```

### Пример кода

[в документации тоже не работает](https://prizm.site/components/dropdowns/multi-select#validators)

```Javascript
export class PrizmMultiSelectValidatorsExampleComponent {
  readonly valueControl = new FormControl(['One'], [Validators.required]);
  readonly items = [
    'One',
    'Two',
    'Three',
  ];
  public setDefaultValue(): void {
    this.valueControl.setValue(null);
  }
}
```

```Html
<prizm-multi-select [formControl]="valueControl" [items]="items"></prizm-multi-select>
<br />
<div>
  <button prizmButton (click)="setDefaultValue()">Clear value</button>
</div>
```

### Описание проблемы

Сброс значения через ```setValue()``` у обязательного поля не валидирует поле, не появляется красная обводка

**Comment by javadoffuad** [comment]
@ZurabDev такая же проблема с inputText

**Comment by AleksandrSibiakov** [comment]
Обводка появляется только для touched контролов. Пробовали добавлять `valueControl.markAsTouched()`?

**Comment by javadoffuad** [comment]
> Обводка появляется только для touched контролов. Пробовали добавлять `valueControl.markAsTouched()`?

@AleksandrSibiakov пробовал, не помогает

**Comment by javadoffuad** [comment]
@ZurabDev спасибо, `setValue` теперь работает!

Но `valueControl.markAsTouched()` по прежнему не срабатывает для обязательного поля с пустым значением.
Валидация так же не сработает, если нажать на крестик на `prizm-chips-item`, 
![image](https://user-images.githubusercontent.com/7090093/232409152-d434681e-96a3-4f0f-a0bf-d6c6e4f0edd1.png)

**Comment by ZurabDev** [comment]
В процессе решения этой проблемы

**Comment by javadoffuad** [comment]
@ZurabDev проверил на 1.0.0 версии:

- `valueControl.markAsTouched()`, `valueControl.markAsDirty()` все еще не работают.
- так же валидация не срабатывает, если удалить выбранный (последний) prizm-chips-item.

откройте пожалуйста, тикет.

**Comment by alexhawkins94** [comment]
а проверьте сейчас?
![chrome_xyqQozwAKv](https://github.com/zyfra/Prizm/assets/122870313/29200ef5-f0f7-469c-8a5b-1fe5d8215de7)

**Comment by dkshichkovskiy** [comment]
На версии 1.2.4 работает. Спасибо.
