### ISSUE TITLE
[Feature] Сделать отступ от иконок в навигационном меню 8px вместо 4px

### ISSUE THREAD

**Issue by ZyfraIvanTerekhov** [zyfra/Prizm#1633]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/icons-loader`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Navigation menu

### Предложение

_Работаю в рамках задачи_   https://jira.zyfra.com/browse/PLATFORM01-39376

_Предлагаю сделать ..._ В навигационном меню отступ от иконок в 8px  так как в макетах везде рекомендован именно такой отступ https://www.figma.com/file/IEsKtY2w1cx6mvpy3hqB9O/%F0%9F%92%8E-Prizm.-Descriptions-v-1.0?type=design&node-id=6695-431480&mode=design&t=2em0ZljWjGp8QfRB-4
![image-2024-03-23-22-24-22-221](https://github.com/zyfra/Prizm/assets/167791224/dd94eaa6-1b6e-4c6c-aba5-9084488f093f)

**Comment by imonogarov** [comment]
@PrizmDS нужно уточнить размеры отступов

**Comment by PrizmDS** [comment]
8 px от контейнера иконки до текста
