### ISSUE TITLE
[BUG] @prizm-ui/components - Высокое потребление памяти

### ISSUE THREAD

**Issue by MrDywar** [zyfra/Prizm#1637]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

table

### Версия

Prizm 4.2.0 (в других вероятно тоже самое)

Операционная система:

Windows 11 23H2

Браузер:

`Chrome Version 124.0.6367.61 (Official Build) (64-bit)`
`Microsoft Edge Version 124.0.2478.51 (Official build) (64-bit)`

### Скрин / Видео проблемы

![Untitled](https://github.com/zyfra/Prizm/assets/14540197/c9372331-75f3-4bed-b6de-bc0b22307a1e)

### Воспроизведение проблемы

Переходим на сайт Prizm, открываем devtools, открываем вкладку Memory и начинаем переключаться между разделами Table и Tabs в течении нескольких минут.

https://prizm.site/components/table

### Описание проблемы

Высокое потребление памяти.
В task manager быстро доходит до 2 GB+, на вкладке memory до 1 GB и затем медленно снижается на несколько десятков процентов. Долго не ждал, снизится ли до стартовых показателей или нет не знаю (в Chrome нет в Edge снижает).

Также само переключение между разделами работает довольно медленно.

**Comment by alexhawkins94** [comment]
Я находил похожую проблему у нас ранее, мы пытались исследовать, она воспроизводилась не стабильно у нас (смотрели на нескольких машинах) и в какой-то момент перестали ее наблюдать и оставили на более пристальное изучение....
https://github.com/zyfra/Prizm/issues/1403

**Comment by ozknemoy** [comment]
за час работы на две сервере у меня доходит до 750МБ на страницу браузера со стартовых 250МБ. и начинает дико лагать консоль разраба. из-за этого бывает (редко) что даже в консоль выплевываются логи с задержкой 5-7 секунд

думаю это связанно с этим (примерно после часа работы дев сервера и сразу после перезагрузки страницы):
![image](https://github.com/zyfra/Prizm/assets/16036508/f06c131a-cd54-4565-baca-3cfd57d6f603)

вот как выглядит эта же страница если ее вновь открыть
![image](https://github.com/zyfra/Prizm/assets/16036508/e1435601-d11d-4729-8632-4680d8fc6cf9)

то есть 32 ворнинга против более 1300. лечится переоткрытием вкладки. потом пол часика шустро работает и снова повторяется



дебаггер ведет в аккордион. у нас их на странице около 10 всего. 

![image](https://github.com/zyfra/Prizm/assets/16036508/e182c046-bbc5-4d30-8d55-bbf42c14ced9)

но ДО аккордиона замечал это поведение на одиночном селекте. было даже так что открывая ПЕРВЫЙ раз селек с 10(!) options дропдаун раскрывался секунды 2
