### ISSUE TITLE
[Feature] - Добавить возможность управление позиционированием в DropdownHost

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#1639]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/icons-loader`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[DropdownHost](https://prizm.site/components/dropdowns/dropdown-host/Live_demo?tuiMode=null)

### Предложение

Привет.
Хотелось бы иметь возможность управлять тем, какую позицию относительно хост-элемента выбирает dropdown-элемент. Например, в material ui есть cdk/overlay, где при создании "плавающего окна" можно указать точку на хост-элементе, относительно которой это окно будет построено. 
Пример: 
<img width="331" alt="Без имени" src="https://github.com/zyfra/Prizm/assets/48792714/db3f3dcd-3b86-4d81-be0b-61210d284832">
скриншот 1

Проблема, которую этим хочется решить следующая - если хост-элемент находится близко к правой границе экрана, то в случае, когда dropdown не помещается в стандартной позиции отображения (нижняя левая точка хоста), он "прилипает к левой границе хоста (см. скрин 2). А мне бы хотелось, чтобы он сначала пробовал отображатся относительно правной нижней точки хоста (как на скриншоте 1).
![image](https://github.com/zyfra/Prizm/assets/48792714/29cb0c1c-f2e8-43ec-84e9-18ce2e1ed4bf)
скриншот 2

Возможно ли реализовать это через Input параметры [DropdownHost](https://prizm.site/components/dropdowns/dropdown-host/Live_demo?tuiMode=null)? Спасибо.

**Comment by ZurabDev** [comment]
Попробуйте выключить autoReposition
