### ISSUE TITLE
[BUG] @prizm-ui/components - Поправить height комопнента prizm-chips-item 

### ISSUE THREAD

**Issue by SergNGZ** [zyfra/Prizm#1641]
![chips 1](https://github.com/zyfra/Prizm/assets/157575739/eb0b71ed-488e-425e-bc52-8fe21698a1af)
Макеты и реализация компонента в призм  высота 24 px

![image](https://github.com/zyfra/Prizm/assets/157575739/9cc1f59d-2097-4329-9a68-52a5435bfcd3)
Реализация на полигоне и компоненты в призм в коде 16 px

### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

prizm-chips-item

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 2.12.1
```

```

### Проект в котором используется Prizm

- ОМ

### Скрин / Видео проблемы

### Воспроизведение проблемы

Реализация на полигоне и компоненты в призм в коде 16 пикселе, а по макетам д.б. 24px

**Comment by ickisIckis** [comment]
@PrizmDS, требуется уточнить высоту компонента. Она была изменена для работы внутри inputs, но макет не обновился.
Требуется ли отдельное значение для отдельно стоящего чипса? Нужно ли добавить переменную для управления высотой чипса?

**Comment by PrizmDS** [comment]
Даем переменную чипсу. 24 дефолт. В S размерах: 16px по высоте, горизонтальные паддинги 4px
