### ISSUE TITLE
[BUG] figma - Названия переменных css в фигма и в призме отличаются. перепутаны color и background

### ISSUE THREAD

**Issue by ozknemoy** [zyfra/Prizm#1653]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `figma`

### Скрин / Видео проблемы

https://github.com/zyfra/Prizm/assets/16036508/dad624b4-c47f-43b7-bbc1-a76970430d56

### Воспроизведение проблемы

например тут можно увидеть https://www.figma.com/file/gHbOaReKtL6QdurVRJHmlV/2024-%E2%80%94-%D0%AD%D0%96%D0%9A%D0%9E?type=design&node-id=5-5935&mode=design&t=q1T30vEVpedrq025-0

### Описание проблемы

при копировании стилей элемента, в буфере обмена:
  1) названия переменных css не совпадают в призме и в фигме (на видео это  --prizm-text-icon-primary и --Text-Icon-Primary)
  2) у некоторых компонентов color (цвет текста) перепутан с background(задний фон)

расшифровка видео:
копирую у блока "Информация о смене" стили 
ожидаемый результат : color: var(--prizm-text-icon-primary, #FFFFFF)
фактический результат background: var(--Text-Icon-Primary, #FFFFFF);

**Comment by imonogarov** [comment]
@PrizmDS просьба посмотреть по пункт 1.

**Comment by PrizmDS** [comment]
@imonogarov @ickisIckis это зависит от Figma. Форматирование не настроить, будем править названия сами. Добавление приставки нужно будет изучить. Взяли в проработку

**Comment by PrizmDS** [comment]
@ozknemoy привели формат стилей к единому виду. 

![image](https://github.com/user-attachments/assets/e2267601-c801-47a7-8cff-dddd04525eb7)
