### ISSUE TITLE
[BUG] @prizm-ui/components - у inputSelect и inputMultiSelect разные margin у label

### ISSUE THREAD

**Issue by katkovergina** [zyfra/Prizm#1659]
### Библиотека

- [x] `@prizm-ui/components`

### Компонент

PrizmSelectInputComponent
PrizmMultiSelectInputComponent

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.12
```

```
➜ npm ls @angular/core

    "@angular-devkit/build-angular": "^14.2.10",
    "@angular-eslint/builder": "~14.4.0",
    "@angular-eslint/eslint-plugin": "~14.4.0",
    "@angular-eslint/eslint-plugin-template": "~14.4.0",
    "@angular-eslint/schematics": "~14.4.0",
    "@angular-eslint/template-parser": "~14.4.0",
    "@angular/cli": "~14.2.10",
    "@angular/compiler-cli": "^14.2.0",
```

### Проект в котором используется Prizm

Энергоконтроль

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/51058477/10cb51d3-fd19-4fb8-b3ed-2ee7a4f883a9)
![image](https://github.com/zyfra/Prizm/assets/51058477/bdf9ccf6-e97c-4f87-82c8-35e17f96859a)

### Описание проблемы
если в компоненте PrizmInputLayoutComponent выбрать [outer] = ''true'', то у PrizmMultiSelectInputComponent у лейбла будет margin-botton, у PrizmSelectInputComponent margin-botton отсутствует, из-за этого проблема сделать в один уровень эти инпуты 
![image](https://github.com/zyfra/Prizm/assets/51058477/60c383c5-dba7-4c2d-a00c-bcc66153c436)

**Comment by ickisIckis** [comment]
https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-4.0?node-id=33661-419968&t=72Lkgp6jq0DORE8Q-0

размеры outer контролов
