### ISSUE TITLE
[BUG] @prizm-ui/components - File upload. Повторное добавление файлов перетирает предыдущие файлы

### ISSUE THREAD

**Issue by Zyfra123** [zyfra/Prizm#1662]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

[File upload](https://prizm.site/components/file-upload)

### Версия
Prizm 3.12.0

### Проект в котором используется Prizm

zui-app-workflow

### Описание проблемы

От первой линии поддержки заведена следующая задача: [IDPFLVS-5028](https://jira.zyfra.com/browse/IDPFLVS-5028).
Самостоятельно решить не удалось, т.к. извне не переписать свойство files компонента

_Шаги воспроизведения_:

1. Добавить один или несколько файлов в prizm-upload
2. Файлы отображаются в компоненте
3. Добавить еще один или несколько файлов
4. Предыдущие загруженные файлы перетираются, в списке файлов отображаются только новые

**Comment by RoxVell** [comment]
+1
Апшелу тоже необходим этот фикс

**Comment by ickisIckis** [comment]
@PrizmDS, нужно уточнить, как отображать ошибку при достигнутом максимальном количестве файлов и добавить описание ux

**Comment by PrizmDS** [comment]
Добавляем счетчик в пример файл аплоада. При достижении максимума – кнопка выбора файлов дизейблится. Зона дропдауна валидирует ошибку при попытке взаимодействия с ней
