### ISSUE TITLE
[BUG] @prizm-ui/components - PrizmCron - после обновления поехали стили у элемента prizm-cron-carousel

### ISSUE THREAD

**Issue by algashev123zyfra** [zyfra/Prizm#1672]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmCron

### Версия

Операционная система:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v20.12.2
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 4.2.0
```

```
➜ npm ls @angular/core

@angular/core@17

```

### Проект в котором используется Prizm

- DatalinkEditor

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/142902249/c419a14d-c23b-4240-854f-2466b8e65682)

### Воспроизведение проблемы

Пример:

https://prizm.site/components/cron

### Описание проблемы

В prizm-cron-carousel у стрелок разные отступы от числа, расположенного по центру

**Comment by imonogarov** [comment]
Дубликат #1529
