### ISSUE TITLE
[BUG] @prizm-ui/components input-layout-date-time Min Max Day With Time layout error

### ISSUE THREAD

**Issue by MrDywar** [zyfra/Prizm#1674]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

input-layout-date-time

### Версия

Prizm v4.2.0

### Скрин / Видео проблемы

![input-layout-date-time-min-max-layout](https://github.com/zyfra/Prizm/assets/14540197/4b6d0dc3-ef07-4a11-82ab-96fb00895263)

### Воспроизведение проблемы

Для input-layout-date-time указываем значения параметров "min" и "max" на дату и время на пару месяцев вперед. Открываем выбор даты, видим что открыт текущий месяц без возможности выбрать дату, в левом верхнем углу "слиплись" название месяца и год и доступна только кнопка перехода на следующий месяц, при нажатии на которую нас перенаправляет на месяц где можно выбрать даты. При перенаправлении могут быть пропущены недоступные месяцы.

### Описание проблемы

Желательно чтобы открывался тот месяц где можно что то выбрать.
Желательно чтобы между месяцем и годом было расстояние (как если бы там был контрол дропдауна).

**Comment by imonogarov** [comment]
@PrizmDS нужно прокомментировать поведение

**Comment by ickisIckis** [comment]
@PrizmDS, список вопросов по поведению:
1. На каком периоде открывать календарь, если текущая или установленная программно дата выходит не попадает в рамки мин/макс
2. Должны ли быть доступны стрелки перехода по календарю, вне зависимости от мин/макс (сейчас не доступны)?
3. Должны ли быть активны кнопки для выбора месяца и года, если мы находимся в рамках доступного периода?
4. Как экран с годами при ограничении мин-макс?
5. Как должен выглядеть экран месяцев  при ограничении мин-макс?

Нужно перепроверить поведение для calendarMonth?

**Comment by PrizmDS** [comment]
4-5. Отображаются все элементы. Недоступные просто зачеркиваются

**Comment by ickisIckis** [comment]
@PrizmDS, нужно добавить описание поведения годов (обсуждение было на созвоне)
