### ISSUE TITLE
[Question] @prizm-ui/components - Срабатывание валидаторов не подсвечивает поле.

### ISSUE THREAD

**Issue by if1t** [zyfra/Prizm#1693]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Все prizm-input поля.

### Версия

angular: 14
```
"@prizm-ui/components": "^1.4.2",
"@prizm-ui/core": "^1.4.2",
"@prizm-ui/flag-icons": "^1.4.2",
"@prizm-ui/helpers": "^1.4.2",
"@prizm-ui/icons": "^1.4.2",
"@prizm-ui/theme": "^1.4.2",
```

NodeJS:

```
➜ node --version
v18.16
```

### Воспроизведение проблемы

https://prizm.site/components/input#validation-custom-example

### Описание проблемы

Не появляется красный значок, что поле инвалидно при руччном вводе в инпут поля. Это то, что я заметил при работе с валидатором required. Также имеется проблема если пытаться применить на FormControl'ы другие валидаторы. Например, при навешивании самописного валидатора на FormControl и попытке его затригерить FormControl помечается как невалидный (this.formControl.invalid === true), но значок danger не появляется. Только при потере фокуса/(взаимодействии с кнопками "стереть", "календарь", "часы" на датапикере). При срабатывании самописного валидатора начинает показываться значок danger.

Есть ли возможность контролировать показ значка danger на поле?

_Шаги воспроизведения_:
1. Перейти по ссылке https://prizm.site/components/input#validation-custom-example.
2. Стереть значение через backspace.

Ожидаемое поведение: Появился красный значок (danger), что поле не валидно (без потери фокуса на поле).
Текущее поведение: Значок не появился.

**Comment by imonogarov** [comment]
@PrizmDS необходимо уточнить UX, в какой момент должна происходить валидация

**Comment by PrizmDS** [comment]
Есть 2 варианта валидации. 

1. **На горячую**: Если с полем взаимодействуют впервые, то валидация происходит после применения ввода. Далее валидация происходит сразу при взаимодействии с полем.
2. **По запросу**: Валидация происходит после нажатия на кнопку "сохранить"

**Comment by if1t** [comment]
Можно ли как-то вручную вызывать prizmInputStatusText? Условно свойство @Input() show. Костыльно, но на время можно закрыться этим.

**Comment by ZurabDev** [comment]
На данный момент такой возможности нет. Можете создать issue на feature для добавление такой возможности?
