### ISSUE TITLE
[BUG] InputMultiSelect - не отображается иконка удаления элемента из выбранного списка

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#1698]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

InputMultiSelect 

### Версия

@prizm-ui/components 4.2.0

### Проект в котором используется Prizm

- СОУ

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/17219726/e0de2172-5232-41fb-ae9f-a2c4ad789869)

### Воспроизведение проблемы

При подключении множественного списка, не отображается иконка удаления элемента из выбранного списка

Код html:
          <prizm-input-layout label="Выбор потока" size="m" [outer]="true">
            <prizm-input-multi-select
              placeholder="Выберите поток"
              [formControl]="flowControl"
              [searchable]="true"
              [items]="vm.flowList"></prizm-input-multi-select>
          </prizm-input-layout>

**Comment by gustav2775** [comment]
У нас на проекте такая же проблема
