### ISSUE TITLE
[BUG] @prizm-ui/components - InputMultiSelect ошибка импортов в шрифтов иконок

### ISSUE THREAD

**Issue by gustav2775** [zyfra/Prizm#1712]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputMultiSelect

### Версия

Dependencies:

@prizm-ui/components 4.2.0
```

### Скрин / Видео проблемы
![image](https://github.com/zyfra/Prizm/assets/71187404/82d1550b-4a3a-4071-9d9d-a87f7cd3fd2f)

Пример:

https://stackblitz.com/edit/ngx-14-title-demo-enp5ng?file=src%2Fapp%2Fapp.component.html

### Описание проблемы

_Делаю задачу_

_Есть проблема следующего характера:_

Ошибки импорта стилей при выборе любого item тз выпадающего списка.

_Шаги воспроизведения_:

1. открыть прилодение на продакшене
2. открыть логи
3. открыть выпадающий список
4. выделить любой items из списка

**Comment by ZurabDev** [comment]
Stackblitz с версией prizm 1.0.0-rc.2
Проблема не вовспроизводиться
Просьба проверить установив шрифты в angular json по инструкции, и создать stackblitz если вопспроизводиться
