### ISSUE TITLE
[Int] CalendarMonth. Кнопка календаря не скрывается при disabled=true

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1728]
Calendar month - кнопка календаря затемняется вместо полного исчезновения при disabled состоянии.
![image](https://github.com/zyfra/Prizm/assets/122870313/3486be6d-7426-4b24-8470-551ac376ac66)

ОР: контролы в инпуте должны скрываться при disabled=true

актуально для 3.х и 4.х

**Comment by imonogarov** [comment]
@PrizmDS посмотреть, как реализовано в других библиотеках

**Comment by imonogarov** [comment]
Скрытие иконок при disabled нераспространенная практика

**Comment by PrizmDS** [comment]
Нет смысла отображать интерактивные элементы, если с ними нельзя взаимодействовать.
