### ISSUE TITLE
[BUG] DropdownHost  - Не работает placement

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#1734]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

DropdownHost  

### Версия

@prizm-ui/components 4.2.0

### Проект в котором используется Prizm

- СОУ

### Скрин / Видео проблемы

https://github.com/zyfra/Prizm/assets/17219726/54a3f071-b6da-4efb-af05-8d7577547e6e

### Воспроизведение проблемы

[_Ссылка на stackblitz с минимальным воспроизведением_](https://stackblitz.com/edit/stackblitz-starters-sv2sjd?file=package.json)

### Описание проблемы

Не работает изменение расположение темплейта для prizm-dropdown-host

**Comment by bree7e** [comment]
Баг затрагивает ZMEB

**Comment by ZurabDev** [comment]
[В](https://stackblitz.com/edit/stackblitz-starters-mebv7p?file=package.json)
Версии 4.3.5 не воспроизводиться
Можете проверить
