### ISSUE TITLE
[BUG] @prizm-ui/icons - Иконка (selection-checkbox-marked-circle) не корректно отображается

### ISSUE THREAD

**Issue by javadoffuad** [zyfra/Prizm#1735]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [x] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 125.0.6422.77 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v18.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 4.0.0
```

### Скрин / Видео проблемы

Было

![image](https://github.com/zyfra/Prizm/assets/7090093/5ffe1abe-3dde-4012-a371-13eb68e1aab5)

Стало

![image](https://github.com/zyfra/Prizm/assets/7090093/7fd124df-b856-4310-ac10-3de4649304ef)

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](https://prizm.site/components/icons/Old_Icons)

**Comment by ZurabDev** [comment]
@PrizmDS можешь скинуть эти иконки, в проекте их не нашел

**Comment by javadoffuad** [comment]
> @PrizmDS можешь скинуть эти иконки, в проекте их не нашел

![selection-checkbox-marked-circle-chanel](https://github.com/zyfra/Prizm/assets/7090093/a664e9c8-bfd4-4b91-ac65-a52095bce3ef)
![selection-checkbox-marked-circle](https://github.com/zyfra/Prizm/assets/7090093/3d18e6c9-c3ff-4e3d-ae74-3a39852a2319)

**Comment by PrizmDS** [comment]
![circle-check-empty](https://github.com/zyfra/Prizm/assets/131430040/d5e84669-7bbe-4ea1-bb13-022d9467412e)
![selection-unchoice](https://github.com/zyfra/Prizm/assets/131430040/4424a7a0-8da1-4c09-9c82-d615eb48e831)


@javadoffuad  Привет! Предлагаем использовать аналогичные иконки
