### ISSUE TITLE
[BUG] InputMultiSelect - Некорректное отображение списка выбранных значений при использовании асинхронных items

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#1754]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

InputMultiSelect 

### Версия

@prizm-ui/components 4.2.0

### Проект в котором используется Prizm

СОУ

### Скрин / Видео проблемы

https://github.com/zyfra/Prizm/assets/17219726/0249ae3e-8128-45f8-b793-10480bd8ba92

### Воспроизведение проблемы

[_Ссылка на stackblitz с минимальным воспроизведением_](https://stackblitz.com/edit/stackblitz-starters-sw4pp7?file=src%2Fapp%2Fapp.module.ts)

### Описание проблемы

Если использовать асинхронные items, то при частичном изменении значений в списке некорректно отображаются выбранные значения

**Comment by AsyaSokolova** [comment]
Обновила в примере версию prizm на 4.3.3 проблема осталась https://stackblitz.com/edit/stackblitz-starters-xjtksr?file=package.json

**Comment by AsyaSokolova** [comment]
https://github.com/zyfra/Prizm/assets/17219726/89d4ccad-aea2-49a7-839a-246d68b9080a

**Comment by ickisIckis** [comment]
Подтвердили воспроизведение проблемы на 4.3.3, берем в работу.

**Comment by ozknemoy** [comment]
похожая проблема при изменении ширины браузера. чипсы переносятся под инпут
[ЭЖКО-СУС.webm](https://github.com/user-attachments/assets/64340344-60b8-43f3-bf41-66a1e118af25)

**Comment by ozknemoy** [comment]
и второй кейс когда наводишь на инпут, появляется кнопка очистки и 1 чипс съезжает вниз

[ЭЖКО-СУС (1).webm](https://github.com/user-attachments/assets/727bae81-1516-495a-beaa-9c9ae79caee8)

**Comment by ozknemoy** [comment]
у  --prizm-chips-item-heigh не хватает t в конце
