### ISSUE TITLE
[BUG] @prizm-ui/components - Иконка ошибочного статуса появляется только после первой потери фокуса

### ISSUE THREAD

**Issue by nerrevar** [zyfra/Prizm#1756]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

`PrizmInput`

### Версия

Операционная ситема:

Manjaro linux

Браузер:

- Firefox 125.0.3
- Chromium 124.0.6367.155

NodeJS:

```
➜ node --version
v20.10.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

zui-app-reporteditor-sts@1.0.0
└─┬ @digital-plant/toolbar@5.0.2
  └── @prizm-ui/components@4.2.0
```

```
➜ npm ls @angular/core

zui-app-reporteditor-sts@1.0.0
├─┬ @angular/common@17.3.8
│ └── @angular/core@17.3.8 deduped
├─┬ @angular/compiler@17.3.8
│ └── @angular/core@17.3.8 deduped
├── @angular/core@17.3.8
├─┬ @angular/forms@17.3.8
│ └── @angular/core@17.3.8 deduped
├─┬ @angular/platform-browser-dynamic@17.3.8
│ └── @angular/core@17.3.8 deduped
├─┬ @angular/platform-browser@17.3.8
│ ├─┬ @angular/animations@17.3.8
│ │ └── @angular/core@17.3.8 deduped
│ └── @angular/core@17.3.8 deduped
├─┬ @angular/router@17.3.8
│ └── @angular/core@17.3.8 deduped
├─┬ @digital-plant/angular-srv-core@3.0.0
│ └── @angular/core@17.3.8 deduped
├─┬ @digital-plant/toolbar@5.0.2
│ ├─┬ @angular/cdk@17.3.8
│ │ └── @angular/core@17.3.8 deduped
│ ├── @angular/core@17.3.8 deduped
│ ├─┬ @digital-plant/zyfra-translate@3.0.0
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @ng-web-apis/common@3.0.6
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @ng-web-apis/intersection-observer@3.2.0
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @ng-web-apis/mutation-observer@3.1.0
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @ng-web-apis/resize-observer@3.0.6
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @prizm-ui/components@4.2.0
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @prizm-ui/core@4.2.0
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @prizm-ui/helpers@4.2.0
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @prizm-ui/i18n@4.2.0
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @prizm-ui/icons@4.2.0
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ @prizm-ui/theme@4.2.0
│ │ └── @angular/core@17.3.8 deduped
│ ├─┬ mobx-angular@4.7.2
│ │ └── @angular/core@17.3.8 deduped
│ └─┬ ngx-mask@17.0.4
│   └── @angular/core@17.3.8 deduped
└─┬ single-spa-angular@9.1.2
  └── @angular/core@17.3.8 deduped
```

### Проект в котором используется Prizm

`@digital-plant/zui-app-reporteditor-sts`

### Скрин / Видео проблемы

[Запись экрана_20240601_231639.webm](https://github.com/zyfra/Prizm/assets/4613403/9fb5a0d1-e4e9-4918-8da4-9794ee58bb70)

### Воспроизведение проблемы

Проблема Воспроизводится на [в LiveDemo компонента Input](https://prizm.site/components/input/Live_demo)

### Описание проблемы

Иконка ошибочного статуса появляется только после потери фокуса.

Шаги воспроизведения:

1. Зайти [в LiveDemo компонента Input](https://prizm.site/components/input/Live_demo)
2. Включить переключатель `[required]`
3. Стереть текст в поле ввода. Здесь не появляется иконка ошибочного статуса, при этом после первой потери фокуса иконка начинает появляться при полном удалении текста

**Comment by imonogarov** [comment]
@PrizmDS нужно понять является это багом или нет + в будущем ссылка на документацию

**Comment by PrizmDS** [comment]
Все работает корректно, система не может отправить ошибку на пустое, но активное поле, т.к. пользователь не совершил ошибку. Ошибка будет проявляться, если пользователь оставил поле пустым после взаимодействия с ним

**Comment by imonogarov** [comment]
Not a bug
