### ISSUE TITLE
[Question] tab-переходы между полями формы

### ISSUE THREAD

**Issue by if1t** [zyfra/Prizm#1759]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

prizm-input-layout-date-time

### Версия

"@prizm-ui/components": "^1.4.2",
"@prizm-ui/core": "^1.4.2",
"@prizm-ui/flag-icons": "^1.4.2",
"@prizm-ui/helpers": "^1.4.2",
"@prizm-ui/icons": "^1.4.2",
"@prizm-ui/theme": "^1.4.2",

### NodeJS:

➜ node --version
v18.16

### Вопрос

В полях с датой и временем нужно 3 раза нажимать на tab, чтобы перейти на следующее поле. Есть ли какой-то способ сделать так, чтобы пропускались кнопки стереть, календарь, время при ручном вводе в поле?

**Comment by imonogarov** [comment]
@PrizmDS просьба предоставить свое заключение

**Comment by PrizmDS** [comment]
Нет, навигация через клавиатуру всегда происходит линейно и построчно. Если в поле есть несколько кнопок, то их все необходимо пройти. 

Как вариант рассматривалась возможность сделать иерархию. Выделяются только сами поля, а при нажатии на Enter мы проваливаемся и взаимодействуем уже с внутренними элементами. Данное решение зависит от реализации в разработке и может быть реализовано не скоро
