### ISSUE TITLE
[BUG] @prizm-ui/components - PrizmPanelComponent extra border radius

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#1767]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_PrizmPanelComponent_

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/2631748/1bd5d364-c93e-4c1f-977d-c6914dc7e6a7)

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](https://prizm.site/components/panel)

Т.к. панель имеет только бордер снизу, нет необходимости задавать радиус (по умолчанию).
[Дизайн спек](https://www.figma.com/design/IEsKtY2w1cx6mvpy3hqB9O/%F0%9F%92%8E-Prizm.-Descriptions-v-1.0?node-id=6242-471939&t=Axg3UW0zGxFfXbBS-4)

P.S. Может, предусмотреть также использование Panel в футере, т.е. возможность "перекинуть" бордер на верх.

**Comment by imonogarov** [comment]
@AleksandrSibiakov  по поводу P.S. желательно завести отдельную задачу
