### ISSUE TITLE
[Question] Как задизейблить один объект из prizm-breadcrumbs?

### ISSUE THREAD

**Issue by if1t** [zyfra/Prizm#1771]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

prizm-breadcrumbs

### Вопрос

Как задизейблить один объект из prizm-breadcrumbs?

**Comment by ickisIckis** [comment]
Для этих целей вам подойдет вариант с проекцией контента. Пример на витрине: https://prizm.site/components/breadcrumbs#with-projection
