### ISSUE TITLE
[Feature] Реализовать календарь представление для данных

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#179]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

Представление произвольных объектов на календаре или таймлайне. Примеры интерфейсов ниже:

![image](https://user-images.githubusercontent.com/52266097/232465677-c6c90c2a-1e03-4841-90fb-990cb0aff820.png)
![image](https://user-images.githubusercontent.com/52266097/232465728-c6757464-da28-42db-abdb-9114f4fbbb6b.png)

**Comment by DenisBiktanov** [comment]
По данному запросу необходимо расписать функциональную спецификацию.

**Comment by ZurabDev** [comment]
Предлагаем использовать сторонние библиотеки типа fullcalendar

**Comment by dkshichkovskiy** [comment]
Решили, что будем использовать сторонние библиотеки.
