### ISSUE TITLE
[BUG] prizm/components - Появляются лишние символы, если при поиске по таблице ничего не найдено

### ISSUE THREAD

**Issue by javadoffuad** [zyfra/Prizm#182]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[Table](https://prizm.site/components/table#search)

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v14.15.0
```

Dependencies:

```
➜ npm ls @prizm-ui/zyfra-components

@prizm-ui/zyfra-components 1.0.0-beta.30
```

### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/7090093/232469146-568150f9-4360-48d2-87c5-92897bda3f09.png)

### Описание проблемы

Когда фильтруем таблицу, если список пустой, появляется лишние символы "--"

**Comment by alexhawkins94** [comment]
@javadoffuad предположу, что это от шаблона для empty table появляется (в примерах у таблиц есть два варианта - с прочерком и кастомным текстом)
если не так, @ZurabDev подскажет точнее
![chrome_P0r2qPYr8k](https://user-images.githubusercontent.com/122870313/232792221-740bbcdd-e1c8-4f5b-967f-bf02a1e4a933.png)

**Comment by ZurabDev** [comment]
можно передать empty свой вариант template для пустой таблицы
