### ISSUE TITLE
[BUG] prizm/hint - в некоторых случаях неправильно рассчитывается отступ подсказки от элемента

### ISSUE THREAD

**Issue by ZyfraOlgaPalkina** [zyfra/Prizm#183]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

HintComponent

### Версия

Операционная сиcтема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v18.15.0
```

Dependencies:

```
➜ npm ls @prizm-ui/zyfra-components

@prizm-ui/zyfra-components 1.0.0-beta.21
```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Проект в котором используется КБ

- Энергоконтроль

### Скрин / Видео проблемы

![hint_reposition](https://user-images.githubusercontent.com/130983761/232469691-dba41f4c-28c0-46b6-a133-684ca1738568.gif)

![hint_correct_position](https://user-images.githubusercontent.com/130983761/232469864-d96d8a27-71a9-4f3f-962a-0178b517c22d.png)
![hint_wrong_position](https://user-images.githubusercontent.com/130983761/232469882-38a96aa1-07fb-4e2a-8e35-faf2b9b13ae3.png)

### Описание проблемы

При использовании компонента PrizmHint в некоторых случаях неправильно рассчитывается отступ подсказки от элемента, на котором она всплывает. Это происходит, если у этого элемента небольшая ширина, при этом текст подсказки занимает несколько строк. При позиционировании размеры z-overlay-wrapper несколько раз пересчитываются, и итоговая позиция не учитывает его окончательную ширину-высоту (можно посмотреть процесс дебага в прикрепленном gif).

Также хотелось бы иметь возможность самостоятельно задавать prizm-hint-container нужный отступ от родительского элемента.

**Comment by ZurabDev** [comment]
Просьба проверить на последней версии и отписаться, если воспроизводиться просим по возможности сделать пример в stackblitz

**Comment by ZyfraOlgaPalkina** [comment]
Проблема больше не воспроизводится. Спасибо
