### ISSUE TITLE
[BUG] @prizm-ui/components - Съезжает иконка календаря в PrizmInputLayoutDateComponent на Safari

### ISSUE THREAD

**Issue by nu11try** [zyfra/Prizm#1831]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmInputLayoutDateComponent 

### Версия

Операционная система:

MacOS

Браузер:

`Safari 17.4.1 (19618.1.15.11.14)`

NodeJS:

```
➜ node --version
v16.16.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components@1.15.0
```

```
➜ npm ls @angular/core

+-- @angular-devkit/build-angular@14.2.13
| `-- @angular/service-worker@14.3.0
|   `-- @angular/core@14.3.0 deduped
+-- @angular/animations@14.3.0
| `-- @angular/core@14.3.0 deduped
+-- @angular/cdk@14.2.7
| `-- @angular/core@14.3.0 deduped
+-- @angular/common@14.3.0
| `-- @angular/core@14.3.0 deduped
+-- @angular/compiler@14.3.0
| `-- @angular/core@14.3.0 deduped
+-- @angular/core@14.3.0
+-- @angular/forms@14.3.0
| `-- @angular/core@14.3.0 deduped
+-- @angular/platform-browser-dynamic@14.3.0
| `-- @angular/core@14.3.0 deduped
+-- @angular/platform-browser@14.3.0
| `-- @angular/core@14.3.0 deduped
+-- @angular/router@14.3.0
| `-- @angular/core@14.3.0 deduped
+-- @prizm-ui/components@1.15.0
| +-- @angular/core@14.3.0 deduped
| +-- @ng-web-apis/common@2.0.0
| | `-- @angular/core@14.3.0 deduped
| +-- @ng-web-apis/intersection-observer@2.0.0
| | `-- @angular/core@14.3.0 deduped
| +-- @ng-web-apis/mutation-observer@2.0.0
| | `-- @angular/core@14.3.0 deduped
| +-- @ng-web-apis/resize-observer@2.0.0
| | `-- @angular/core@14.3.0 deduped
| `-- ngx-mask@14.2.4
|   `-- @angular/core@14.3.0 deduped
+-- @prizm-ui/core@1.15.0
| `-- @angular/core@14.3.0 deduped
+-- @prizm-ui/helpers@1.15.0
| `-- @angular/core@14.3.0 deduped
+-- @prizm-ui/i18n@1.15.0
| `-- @angular/core@14.3.0 deduped
+-- @prizm-ui/icons@1.15.0
| `-- @angular/core@14.3.0 deduped
+-- @prizm-ui/theme@1.15.0
| `-- @angular/core@14.3.0 deduped
`-- single-spa-angular@7.1.0
  `-- @angular/core@14.3.0 deduped


```

### Проект в котором используется Prizm

ZIIOT - Платформа

### Скрин / Видео проблемы

![56e395a9-8ac9-4b11-9874-a6700031e6f0](https://github.com/zyfra/Prizm/assets/45148694/1d25c1da-f6a7-40f0-a4b1-7df6a7757398)

### Описание проблемы

На Safari неправильно отображается иконка календаря - она съехала. При этом, на других браузерах все хорошо.

**Comment by ickisIckis** [comment]
Добрый день, не получается воспроизвести проблему в документации на актуальных версиях. Проверьте на последней версии, для Angular 14 это Prizm 1.18.1
 Если проблема сохранится - нужно будет добавить пример на stackblitz для понимания сценария воспроизведения.
