### ISSUE TITLE
[Feature] @prizm-ui/components - PrizmNavigationComponent. Не работает программное разворачивание ветви меню через `isExpanded`

### ISSUE THREAD

**Issue by sergeycher** [zyfra/Prizm#1838]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmNavigationComponent

### Версия Prizm

`^1.12.1`

### Проект в котором используется Prizm

- Энергоконтроль

### Описание проблемы

При программной навигации (не задействуя компонент PrizmNavigationComponent) нужный пункт в меню подсвечивается, но если он вложенный - то дерево к нему не разворачивается. Рекурсивная установка флага isExpanded ничего не дала. Судя по коду Prizm - фича вообще не реализована.

В идеале должно работать авторазворачивание дерева к активному элементу, но и поддержка `isExpanded` тоже сойдёт.

Связано с #1511 - там приведено неправильное описание бага.

**Comment by ickisIckis** [comment]
Добрый день, проблему исправляли c issue https://github.com/zyfra/Prizm/issues/1213
на Angular 14 это версии старше 1.15.1

**Comment by ickisIckis** [comment]
> Добрый день, проблему исправляли c issue #1213 на Angular 14 это версии старше 1.15.1

возникла путаница в компоненте, речь про https://prizm.site/components/navigation

в этом компоненте такой функционал не был предусмотрен заранее,  переквалифицирую в запрос на функционал.

**Comment by ickisIckis** [comment]
Добавим поддержку isExpanded, т.к. на данный момент нет описаний поведения при сочетании переданной конфигурации isExpanded + переданного активного элемента: могут быть конфликты, а конфигурация является более гибким инструментом и подходит как для кеширования состояния меню пользователя, так и для разворачивания к выбранному  элементу в зависимости от требований на конкретном проекте.
