### ISSUE TITLE
[BUG] prizm/components - Нельзя задать текст сообщения об ошибке для Select, MultiSelect

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#184]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[Select](https://doc.prizm.zyfra.com/components/dropdowns/select), [MultiSelect](https://doc.prizm.zyfra.com/components/dropdowns/multi-select).

### Описание проблемы

Нет возможности установить текст сообщения об ошибке для компонентов Select, MultiSelect при наведении на иконку иконку ошибки внутри контрола. Сейчас всегда отображется пустой чёрный квадрат:
![image](https://user-images.githubusercontent.com/52266097/232677941-51e682b3-e172-440a-863a-5c416736d579.png)

Хотелось бы иметь возможность задавать текст всплывающей подсказки так, как это делается, например, для компонента Input:
```html
<prizm-input-layout label="Заголовок" size="l" status="danger">
  <input prizmInput value="Введенный текст" placeholder="Введите текст" />
  <ng-template prizmInputStatusText>Danger text</ng-template>
</prizm-input-layout>
```

**Comment by TheSpaceHuman** [comment]
Подтверждаю проблему, мою работу так же блокирует

**Comment by ZurabDev** [comment]
В процессе. Отпишусь как зальем
