### ISSUE TITLE
[BUG] @prizm-ui/icons - Регистрация кастомных иконок в 4.3.4. версии Prizm

### ISSUE THREAD

**Issue by daniilkiselev97** [zyfra/Prizm#1841]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [x] `@prizm-ui/icons`

### Компонент

_Название компонента или группы компонентов_

PrizmIconsComponent

### Описание проблемы
В 4.3.4. версии Prizm отсутствует раздел для регистрации своих кастомных иконок , как это было в предыдущей версии;

Также не совсем понятно, когда выбирать PrizmIconsFullRegistry или PrizmIconsRegistry при регистрации Prizm icons.

**Comment by ZurabDev** [comment]
Можешь добавить плз информацию о том какие иконки и когда использовать @PrizmDS

**Comment by PrizmDS** [comment]
@ZurabDev постепенно пишется документация с описанием иконок стандартных действий. На что-то большее не стоит рассчитывать, т.к значения у одной иконки от проекта к проекту могут быть разными.

**Comment by PrizmDS** [comment]
https://prizmds.gitbook.io/deraft/
