### ISSUE TITLE
[FEATURE] @prizm-ui/components - Отсутствует возможность выполнить правый переход в PrizmTabsComponent

### ISSUE THREAD

**Issue by imagomadov95** [zyfra/Prizm#1846]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmTabsComponent

### Описание проблемы
Отсутствует возможность выполнить правый переход, когда вкладки не помещаются на экране, параметр canShowMenu установлен в значение false.
Необходимо настроить функционал так, чтобы правый переход работал так же, как и левый.

![2024-07-02_14-40-07](https://github.com/zyfra/Prizm/assets/88551177/cee2ecba-6c2f-4942-b88a-79dbcd2124f1)

1. Зайти по адресу [[prizm](https://doc.prizm.zyfra.com)](https://stackblitz.com/edit/angular-t4vwfj?file=src%2Fapp%2Fapp.component.html)
2. Уменьшить ширену так чтобы табы не вмешались

**Comment by ickisIckis** [comment]
@imagomadov95, просьба проверить на версии 4.3.6

**Comment by imagomadov95** [comment]
@ickisIckis все еще воспроизводиться
