### ISSUE TITLE
[BUG] prizm/components - Не отображается кастомное сообщение об ошибке в InputDateTime

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#185]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[InputDateTime](https://doc.prizm.zyfra.com/components/input-date-time)

### Описание проблемы

Если для компонента InputDateTime добавить валидатор обязательности заполнения (`Validators.required`), то при пустом значения поля, при наведении на иконку ошибки отображается текст "Ошибка! Неправильный формат". Отображать такой текст в случае не заполнения поля кажется не корректным. Более того, если установить кастомный текст сообщения, то он не отображается. Вместо него текст "Ошибка! Неправильный формат".

```html
<prizm-input-date-time
  size="m"
  [formControlName]="control"
  timeMode="HH:MM">
   <ng-template prizmInputStatusText>Текст ошибки</ng-template>
</prizm-input-date-time>
```

**Comment by dkshichkovskiy** [comment]
@ZurabDev Проверил на версии 1.0.0, проблема воспроизводится, теперь ни какая подсказка не отображается.

Перешёл на InputLayoutDateTime. Использую компонент таким образом:

```html
<prizm-input-layout
  i18nPrefix="ControlStartTimePlanned"
  [label]="'Label' | i18nPrefixTranslate"
  size="m">
  <prizm-input-layout-date-time
    [formControlName]="FORM_MEMBER.START_TIME_PLANNED">
    <ng-template prizmInputStatusText>Text</ng-template>
  </prizm-input-layout-date-time>
</prizm-input-layout>
```

**Comment by ZurabDev** [comment]
Попробуй добавить <ng-template prizmInputStatusText>Text</ng-template> в prizm-input-layout а не prizm-input-layout-date-time

**Comment by dkshichkovskiy** [comment]
@ZurabDev Аналогично, делаю так:

```html
 <prizm-input-layout
      i18nPrefix="ControlStartTimePlanned"
      [label]="'Label' | i18nPrefixTranslate"
      size="m">
      <prizm-input-layout-date-time
        [formControlName]="FORM_MEMBER.START_TIME_PLANNED">
      </prizm-input-layout-date-time>
      <ng-template prizmInputStatusText>Text</ng-template>
    </prizm-input-layout>
```

**Comment by dkshichkovskiy** [comment]
@ZurabDev Приоткроем issue?

**Comment by ickisIckis** [comment]
Компонент deprecated и будет удален в версии 4.0, рекомендуем использовать InputLayoutDateTime.

**Comment by ickisIckis** [comment]
так же требуется убрать статику в тексте, компонент InputLayoutDateTime

**Comment by alexhawkins94** [comment]
относится к input layout
