### ISSUE TITLE
[BUG] @prizm-ui/components - InputMultiSelect маленькая область нажатия

### ISSUE THREAD

**Issue by RoxVell** [zyfra/Prizm#1850]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

InputMultiSelect

### Версия

v4.3.4, но баг представлен и в 3ей версии

### Проект в котором используется Prizm

security-settings

### Скрин / Видео проблемы
![2024-06-07 16-34-26  CCkgwd](https://github.com/zyfra/Prizm/assets/17107421/202c924b-db5d-4ecb-9a2a-07f0e864ab6a)

### Воспроизведение проблемы

Перейти на сайт https://prizm.site/components/input-multi-select, потыкать на область инпута чуть от центра
Также возможно стоит заменить курсор на pointer

**Comment by PrizmDS** [comment]
@ickisIckis  Кликабельна должна быть вся область поля

**Comment by RoxVell** [comment]
UPD. QA также сообщают о неправильном курсоре InputSelect, который имеет курсор ввода текста вместо pointer.
