### ISSUE TITLE
[BUG] @prizm-ui/components - Контрол InputSelect сразу отображается как не валидный

### ISSUE THREAD

**Issue by stcoder** [zyfra/Prizm#1851]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputSelect

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 126.0.6478.127 (Официальная сборка), (64 бит)`

NodeJS:

```
➜ node --version
v22.1.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components@3.13.2
```

```
➜ npm ls @angular/core

+-- @angular/animations@16.2.12
| `-- @angular/core@16.2.12 deduped
+-- @angular/cdk@16.2.14
| `-- @angular/core@16.2.12 deduped
+-- @angular/common@16.2.12
| `-- @angular/core@16.2.12 deduped
+-- @angular/compiler@16.2.12
| `-- @angular/core@16.2.12 deduped
+-- @angular/core@16.2.12
+-- @angular/forms@16.2.12
| `-- @angular/core@16.2.12 deduped
+-- @angular/platform-browser-dynamic@16.2.12
| `-- @angular/core@16.2.12 deduped
+-- @angular/platform-browser@16.2.12
| `-- @angular/core@16.2.12 deduped
+-- @angular/router@16.2.12
| `-- @angular/core@16.2.12 deduped


```

### Проект в котором используется Prizm

- ZMEB

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/1697524/2b02fe8b-6246-48a5-b5ae-831be7f3a231)

### Описание проблемы

Нужно с бэка подгрузить список значений для контрола InputSelect и присвоить его в items, контрол обязателен для заполнений, при открытии формы контрол сразу отображается невалидным.

_Есть проблема следующего характера:_ У компонента InputSelect срабатывает валидация еще до того как я повзаимодействовал с этим полем.

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](https://prizm.site/components/input-select#validators)
2. Перейти в раздел Validators
3. У компонента InputSelect стоит валидатор required
4. Компонент отображается как не валидный

**Comment by digital-plant-guard** [comment]
Такая-же ошибка, ждем фикс =) 

![image](https://github.com/zyfra/Prizm/assets/126816006/e67f4e18-94bf-4cc1-9bea-4f36d83a69c4)
