### ISSUE TITLE
[BUG] @prizm-ui/components - Некорректно работает прокрутка табов при переполнении

### ISSUE THREAD

**Issue by AndreySZyfra** [zyfra/Prizm#1863]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`

-

### Компонент

prizm-tabs

### Версия

Операционная сиcтема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 126.0.6478.127`

### Проект в котором используется Prizm

- ZSPM

### Описание проблемы
на экране несколько табов (много). Есть переполнение, часть табов скрыты за стрелками прокрутки 
через activeTabIndex выставляем индекс скрытого таба
ОР - UI прокрутилось до выбранного таба
ФР - таб остался скрытым за стрелкой

**Comment by alexhawkins94** [comment]
при фиксе добавить в live demo большое кол-во табов чтоб можно было в будущем учитывать этот кейс при тестировании
![chrome_mngphRC7in](https://github.com/user-attachments/assets/ffef4ca4-73d5-48f9-8c3e-06c5393b885e)
