### ISSUE TITLE
[Feature] Изменение значение Cron без клика на кнопку "Применить"

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#187]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[Cron](https://doc.prizm.zyfra.com/components/cron)

### Предложение

Хотим использовать компонент Cron в контексте большой формы, у которой есть кнопка "Сохранить". Причём эта форма разбита на несколько вкладок (при переходе с одной вкладки на другую - компоненты предыдущей вкладки уничтожаются, новой - создаются).

В этом кейсе дополнительная кнопка "Применить" лишь сбивает с толку. Пользователю нужно кликать дважды. К тому же при смене вкладки будет потеряно ещё не применённое состояние крона (т.к. значение до клика по "Применить" хранится лишь внутри компонента и не вываливается в наружу через событие `periodChange`).

Предлагаю реализовать возможность инициации события `periodChange` на лету, без необходимости кликать по кнопке "Применить". Скорее всего это должен быть дополнительный "режим работы" компонента, при котором кнопка "Применить" не отображается.

**Comment by alexhawkins94** [comment]
реализованное свойство [autoSubmit]  не подходит для решения проблемы? @dkshichkovskiy
