### ISSUE TITLE
[BUG] @prizm-ui/components -InputLayoutDateRange - не открывается календарь

### ISSUE THREAD

**Issue by OlgaMerkulova** [zyfra/Prizm#1887]
### Библиотека
- [ ] `@prizm-ui/components`

### Компонент
InputLayoutDateRange

### Версия
4.3.6

### Описание проблемы
При нажатии на значок календаря ожидается, что откроется календарь для выбора периода. Первый раз открывается корректно, дальше если открыть-закрыть всплывающее окно несколько раз путем клика на иконку календаря, она открывается и через доли секунд схлапывается, выбрать период больше не представляется возможным. Воспроизводится на витрине.

**Comment by alexhawkins94** [comment]
known bug старый, скоро исправим https://github.com/zyfra/Prizm/issues/1289

**Comment by ickisIckis** [comment]
Ольга, добрый день, оставьте, пожалуйста ваши контакты по issue https://github.com/zyfra/Prizm/issues/1125
не можем воспроизвести проблему
