### ISSUE TITLE
[BUG] prizm-dropdown-host — this.overlay is undefined

### ISSUE THREAD

**Issue by elquid** [zyfra/Prizm#1889]
### Библиотека

- [x] `@prizm-ui/components`

### Компонент

`PrizmDropdownHostComponent`

### Версия

`@prizm-ui/components@4.3.6`

### Скрин / Видео проблемы

![image](https://github.com/user-attachments/assets/0ffe7d20-e0aa-4f53-945a-5f18f85a3668)

### Описание проблемы

Возникает ошибка в консоли, воспроизводится нестабильно.

https://github.com/zyfra/Prizm/blob/5f855ab84c39bece87df98eccb3f7206b100a530/libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts#L201

**Comment by ickisIckis** [comment]
Добрый день, не воспроизводится в документации, получится подготовить пример в стакблитц?
