### ISSUE TITLE
[Int] Multiselect. Чипс и шеврон (+интут через них) остаются интерактивными при disabled=true 

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1914]
prod: 3.15 4.3.7 
dev: 3.15.1 4.4

Шаги:
-перейти в демо multiselect
-выбрать айтем
-установить disabled=true
-навести курсор на чипс - появляется ховер
-сделать клик по чипсу - появляется фокус на инпуте и чипсе
-навести курсор на шеврон и сделать клик по нему - инпут получает фокус
ФР: Чипс и шеврон (+интут через них) остаются интерактивными при disabled=true 
ОР: все компоненты инпута должны быть disabled при disabled=true

**Comment by ickisIckis** [comment]
связано с #1917
