### ISSUE TITLE
[Feature] Сервис/функция отображения человеко-читаемого значения cron

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#1936]
### Библиотека

- [] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/icons-loader`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
- [x] `@prizm-ui/helpres`

### Предложение

В компоненте [Cron](https://prizm.site/components/cron) есть возможноcть отображать пользователю текущее значение человеко-читаемым текстом (опция `showHumanReadable`). Необходим отдельный инструмент (функция, сервис), который бы брал на вход cron значение и выдавал такое же человеко-читаемое значение.

**Comment by ickisIckis** [comment]
@dkshichkovskiy, возможно вот это подойдет:
https://prizm.site/components/cron-human-readable

**Comment by dkshichkovskiy** [comment]
> @dkshichkovskiy, возможно вот это подойдет: https://prizm.site/components/cron-human-readable

Да, это то что нужно, не видел. Спасибо!
