### ISSUE TITLE
[Feature] Предотвращение закрытия SideBar

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#194]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[SideBar](https://doc.prizm.zyfra.com/components/dialogs/sidebar)

### Предложение

Возникла потребность отслеживать попытку пользователя закрыть диалоговое окно и, в зависимости от некторого условия, отменять закрытие диалога.

_Пользовательский сценарий_

1. Пользователь октрывает окно дилаога
2. Вносит некоторые изменения, например в форму расположенную в области контента диалога
3. Не выполняет сохранение значений и пытается закрыть диалог
4. Отобразить диалог-подтверждения с выбором действий. Пока дейтсвие не выбрано, диалог не закрывается.

Хотелось бы иметь возможность:
1) Отслеживать событие backdropClick
2) Самоу реализовать логику, когда диалог должен быть закрыт или передавать некторый поток в качетсве опций sideBar , который не даст закрыть диалог пока не будет выпущенно значение этим потоком.

Подскажите, пожалуйста, возможно ли такое реализовать?

**Comment by ZurabDev** [comment]
<img width="1042" alt="CleanShot 2023-04-28 at 15 11 49@2x" src="https://user-images.githubusercontent.com/75216044/235144251-30f11292-314b-4a4a-a959-0a472ebca8ba.png">
Добавлено опционально возможность передачи cb
