### ISSUE TITLE
[Int] Tabs. Через дропдаун можно выбрать disabled табу.

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#1947]
4.3.8
3.15

-Развернуть дропдаун кликом на кебаб
-Выбрать disabled табу
ФР: происходит выбор disabled табы.
ОР: нельзя выбрать disabled таб

**Comment by alexhawkins94** [comment]
https://github.com/zyfra/Prizm/issues/1859

**Comment by ickisIckis** [comment]
Live demo => canOpen, выбрать опцию 2.
так же не должно позволять изменять
