### ISSUE TITLE
[Feature] Предотвращение перехода на вкладку в Tabs

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#195]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[Tabs](https://doc.prizm.zyfra.com/components/tabs)

### Предложение

Есть необходимость отслеживать переход на какую-либо вкладку и при определённых условиях предотвращать этот переход. Или даже иметь возможность вернуть какой-нибудь Observable<boolean>, в зависимости от значения которого переход может произойти или отмениться. То есть нужно что-то похожее на guards в роутинге Angular.

Пользовательский сценарий:
1. Пользователь находится во вкладке 1.
2. Содержимое вкладки - это некоторая форма, в которую пользователь вводит данные.
3. Далее, чтобы эти данные сохранились, пользователь должен нажать на кнопку сохранения. Однако он этого не делает.
4. Вместо этого пользователь кликает по заголовку вкладки 2.
5. Т.к. на вкладке 1 есть несохраненные изменения - переход на вкладку 2 не выполняется сразу же.
6. Вместо перехода отображается диалог с заголовком "У вас есть несохраненные изменения. Что изволите делать?" с кнопками:
  а) "Сохранить изменения и перейти на вкладку 2", 
  б) "Отменить изменения и перейти на вкладку 2", 
  в) "Остаться на вкладке 1"
7. При клике на какую-либо кнопку выполняется или не выполняется переход на вкладку 2.

**Comment by ZurabDev** [comment]
Есть возможность управления через disabled атрибут и пример в доках с этим. Речь идет об этом?

**Comment by AleksandrSibiakov** [comment]
![image](https://user-images.githubusercontent.com/2631748/235905077-3f80d835-dad3-4d70-8561-0131781454eb.png)
Я понял что об этом (аналог из ng-bootstrap). Т.е. при клике по табе для `$event` аргумента события смены табы доступен метод `preventDefault`, вызвав который мы предотвращаем стандартное поведение - перемещение активного таба (примерно как preventDefault работает для браузерных событий)

P.S. Это пример, реализация может быть другой, в том числе и с поддержкой асинхронной обработки перехода. Что то похожее недавно добавили [для закрытия Sidebar](https://github.com/zyfra/Prizm/issues/194).

**Comment by dkshichkovskiy** [comment]
Да, нужно похожее поведение на то как сделали в https://github.com/zyfra/Prizm/issues/194 . Через использование атрибута `disabled` кейс закрыть не можем.

**Comment by ZurabDev** [comment]
Добавим пример в доку как stopPropagination

**Comment by ZurabDev** [comment]
<img width="784" alt="CleanShot 2023-06-15 at 13 01 30@2x" src="https://github.com/zyfra/Prizm/assets/75216044/dbb2d1d0-07c9-4bf5-8b9c-a084375b6cf8">
Добавлено
