### ISSUE TITLE
[Feature] @prizm-ui/components - Support declarative creation `prizm-switcher-item` with [value] input

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#1965]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/icons-loader`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_PrizmSwitcher_

### Предложение

Работать с индексом в качестве value крайне не удобно, и редко когда имеет практическое применение.

Предлагаю расширить интерфейс айтемов инпутом value (с фоллбэком к индексу айтема в реализации, для обратной совместимости)

Также, считаю что будет удобна поддержка декларативного определения <prizm-switcher-item> ([по аналогии с material](https://material.angular.io/components/button-toggle/examples)). Это более удобное задание айтемов с поддержкой итераторов (trackBy) и возможностю применения `@Pipe` к значениям (например translate)

Пример использования: 
```
<prizm-switcher
  [(ngModel)]="selectedItem" <-- here value is used
  (selectedSwitcherIdxChange)="updateIdx($event)" <-- keep output for idx
>
 @for(item of items; track item) {
   <!--  note that item component already exists -->
   <prizm-switcher-item [value]="item.myValue">{{ item.label | translate }}</prizm-switcher-item>
 }
</prizm-switcher>
```

**Comment by AleksandrSibiakov** [comment]
You can contact me if interested in a PR

**Comment by AleksandrSibiakov** [comment]
@ZurabDev Задача помечена ready, но в связанном PR (https://github.com/zyfra/Prizm/pull/2043) не нашел реализации инпута `[value]` (или аналогичного)

**Comment by ZurabDev** [comment]
> @ZurabDev Задача помечена ready, но в связанном PR (#2043) не нашел реализации инпута `[value]` (или аналогичного) у `<prizm-switcher-item>`

Добавили специально примеры
<img width="576" alt="Screenshot 2024-09-20 at 10 59 08" src="https://github.com/user-attachments/assets/fc5e3844-74dc-4681-9996-44e1be6c675f">
