### ISSUE TITLE
[BUG] @prizm-ui/components - Чипсы выходят за рамки поля в prizm-input-multi-select

### ISSUE THREAD

**Issue by imagomadov95** [zyfra/Prizm#1975]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmMultiSelectInputComponent

### Скрин / Видео проблемы
![image-2024-08-14-13-53-43-844](https://github.com/user-attachments/assets/923e3134-ed0e-469c-acb1-8d4001c3209c)
![image-2024-08-14-13-59-21-080](https://github.com/user-attachments/assets/3c19b345-2fb4-4075-ad84-7ec708171994)

### Описание проблемы
Чипсы выходят за рамки поля если уменьшить размер области prizm-input-multi-select
Чипсы отображаются не на всю ширину поля при увелечения размер области prizm-input-multi-select

**Comment by imonogarov** [comment]
связано с https://github.com/zyfra/Prizm/issues/1754

**Comment by ickisIckis** [comment]
связано с #1754
