### ISSUE TITLE
[Feature] InputSelect, InputMultiSelect - Добавить возможность закреплять строку поиска и не скроллить вместе с контентом

### ISSUE THREAD

**Issue by RoxVell** [zyfra/Prizm#1981]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/icons-loader`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

InputSelect, InputMultiSelect

### Предложение

Сейчас при выставлении значения searchable=true, строка поиска скроллится вместе с основным контентом, что не очень удобно, предлагаю добавить возможность закреплять строку, чтобы она всегда была видимой или может даже имеет смысл сделать такое поведение по умолчанию.

**Comment by imonogarov** [comment]
@PrizmDS нужен дизайн

**Comment by PrizmDS** [comment]
@RoxVell @imonogarov Согласны с предложением
