### ISSUE TITLE
[Question] Управление позицей сролла для контента sidebar

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#199]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[SideBar](https://doc.prizm.zyfra.com/components/dialogs/sidebar)

### Вопрос

Возможно ли управлять скроллом комопнента prizm-scrollbar, который используется для отображения контента внутри sideBar? Например, есть потребность программно переместить скролл в верхнию/нижнюю точку блока конетна.

**Comment by dkshichkovskiy** [comment]
@ZurabDev Висит метка "need_more_information". Какая именно дополнительная информация нужна?

**Comment by ZurabDev** [comment]
Добавлен outerContent в котором не будет по дефолту скролбара, и Вы сами сможете добавить его в шаблон, соотвественно получив доступ к контролю
