### ISSUE TITLE
[BUG] @prizm-ui/components - Tabs: since it isn't a known property of 'prizm-tab'

### ISSUE THREAD

**Issue by dmitriy-sokolov** [zyfra/Prizm#1991]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

[Tabs](https://prizm.site/components/tabs/Setup)

### Версия

```
Angular CLI: 17.3.8
Node: 20.16.0
Package Manager: npm 10.8.1
OS: linux x64

Angular:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1703.8 (cli-only)
@angular-devkit/core         17.3.8 (cli-only)
@angular-devkit/schematics   17.3.8 (cli-only)
@schematics/angular          17.3.8 (cli-only)
```

### Проект в котором используется Prizm

- zui-app-datalink-editor

### Скрин / Видео проблемы

![изображение](https://github.com/user-attachments/assets/79838ea9-d9bf-4bc9-b13c-e348a2003884)

### Воспроизведение проблемы

Со страницы [Tabs](https://prizm.site/components/tabs) пытаемся реализовать пример **Base**. Собираем проект с нуля. Устанавливаем пакет `@prizm-ui/components` и `@prizm-ui/icons`. На вкладке `Setup` видимо не прописаны все зависимости для запуска примеров: компонент `prizm-tab` приложение не видит. 

### Описание проблемы

Шаги воспроизведения:

1. Создаем тестовый проект: `ng new tesrrr` 
2. Устанавливаем пакеты: `npm i @prizm-ui/components  @prizm-ui/icons`
3. `app.component` настраиваем как в примере [Base](https://prizm.site/components/tabs)
4. Запускаем: `ng s`
5. Переходим в браузер: `localhost:4200`

**Comment by imonogarov** [comment]
Дубль https://github.com/zyfra/Prizm/issues/1989
