### ISSUE TITLE
[BUG] prizm/components - Появляется черный квадрат при наведении на иконку на компоненте select

### ISSUE THREAD

**Issue by NikoStV** [zyfra/Prizm#200]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

prizm-select

### Версия

Операционная сиcтема:

`Windows 11, etc`

Браузер:

`Google Chrome Версия 112.0.5615.138 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.0.0-beta.32
```

### Проект в котором используется КБ

https://prizm.site/

### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/20378994/233939485-c1f49559-f0b0-4917-9b5c-81d9642d3e03.png)

### Описание проблемы

1. зайти на https://prizm.site/components/dropdowns/select
2. стереть значение из компонента select нажав на кнопку(стереть)
3. Навести курсор на иконку(красный кружок)

Результат: Отображается черный квадратик правее от иконки(см. скриншот)

**Comment by alexhawkins94** [comment]
это пустой хинт всплывает вроде как, в примерах не делали ему наполнение какое-либо

**Comment by NikoStV** [comment]
Он всплывает и не в примерах и в рабочем проекте то же.
