### ISSUE TITLE
[BUG] @prizm-ui/components - PrizmTabsComponent. Cannot read properties of undefined (reading 'disconnect')

### ISSUE THREAD

**Issue by digital-plant-guard** [zyfra/Prizm#2013]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmTabsComponent

### Версия
"@prizm-ui/components": "4.3.5",
"@prizm-ui/core": "4.3.5",

### Скрин / Видео проблемы
<img width="508" alt="image" src="https://github.com/user-attachments/assets/5c8c8dde-78a4-4e08-a432-c3abb2864733">
 
 
<img width="520" alt="image" src="https://github.com/user-attachments/assets/d1b2e724-2476-45f7-bc1f-db0982d77f57">

### Описание проблемы
Самые быстрые QA на диком западе, переключаясь по элементам меню, и расстреливая страницы с табами в пух и прах, заметили, что в предсмертной агонии, те умудряются кидать ошибку  `TypeError: Cannot read properties of undefined (reading 'disconnect')`

**Comment by VeronikaRpn** [comment]
![tabs issue](https://github.com/user-attachments/assets/14d8dea5-187d-49e8-8935-d97dda6022fb)
Скринкаст ошибки от автора
