### ISSUE TITLE
[BUG] @prizm-ui/components - Убрать пустой <span> рядом с кнопкой сортировки в таблице Prizm

### ISSUE THREAD

**Issue by imagomadov95** [zyfra/Prizm#2021]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmTableModule

### Скрин / Видео проблемы
![Снимок экрана 2024-08-27 в 13 49 23](https://github.com/user-attachments/assets/d5fc7892-7e41-4800-a53a-977506eb7189)
<img width="1503" alt="Снимок экрана 2024-08-27 в 13 37 09" src="https://github.com/user-attachments/assets/cb582908-74f2-4f0b-a9b3-41dc7828fa2a">
![Снимок экрана 2024-08-27 в 13 41 00](https://github.com/user-attachments/assets/9efe3a3f-30af-447b-a523-18ccb3f80198)

### Воспроизведение проблемы

_Ссылка на stackblitz с минимальным воспроизведением_
Пример:

https://prizm.site/components/table/Live_demo?tuiMode=null

### Описание проблемы

В таблице Prizm, если включить сортировку, рядом с кнопкой сортировки появляется пустой ```<span _ngcontent-ng-c4089245806="" class="sorter__number" style="visibility: hidden;">0</span>``` . Его нужно убрать, так как из-за него бывает слишком большое расстояние между кнопками, если включить кнопку фильтрации

**Comment by ickisIckis** [comment]
связано с https://github.com/zyfra/Prizm/issues/1986
