### ISSUE TITLE
[BUG] @prizm-ui/components - Focused `PrizmSwitcherItem` has border radius

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#2032]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_Switcher_

### Скрин / Видео проблемы

![image](https://github.com/user-attachments/assets/46a00924-21cf-4e4a-b6da-29c364a11c64)

### Воспроизведение проблемы

https://prizm.site/components/switcher

**Comment by ickisIckis** [comment]
@PrizmDS, такое поведение добавлялось специально, нужно уточнить, как должны вести себя кнопки с фокусом.

**Comment by AleksandrSibiakov** [comment]
@ickisIckis возможно, что проблема тогда в том что border-radius есть, но нет тени (который в роли аутлайна именно при фокусе) 
![image](https://github.com/user-attachments/assets/b9fa3379-0c8c-4ede-b2a5-5ddbeb330b27)

вероятно надо разделять :active & :focused-visible состояния

**Comment by ickisIckis** [comment]
> @ickisIckis возможно, что проблема тогда в том что border-radius есть, но нет тени (который в роли аутлайна именно при фокусе) ![image](https://private-user-images.githubusercontent.com/2631748/366430197-b9fa3379-0c8c-4ede-b2a5-5ddbeb330b27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjM3MzMsIm5iZiI6MTcyNjEyMzQzMywicGF0aCI6Ii8yNjMxNzQ4LzM2NjQzMDE5Ny1iOWZhMzM3OS0wYzhjLTRlZGUtYjJhNS01ZGRiZWIzMzBiMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDY0MzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTExNzQ3YTk3ZDU4YzllNjE2YjZhYzFmZjQyZjc1Y2UwYjg2NTI0MGExYzk0ZjljZTMyMjdmMzZmNzdhMzA1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r6Hur7xp_KsZG68qqQ70iJdfsznr-8ETnGMtW9CDpIU)
> 
> вероятно надо разделять :active & :focused-visible состояния (делать радиус только если есть обводка)
> 
> Но даже в этом случае остаются проблемы 1) с небольшими незакрашенными уголками - на скриншоте в описании видно (вложенные радиусы надо уменьшать на ширину границы), 2) с отсутствием правой границы у кнопки (радиус заканчивается без вертикальной линии) ![image](https://private-user-images.githubusercontent.com/2631748/366434823-f7105de1-e26f-4a25-91bf-931978d7dd2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjM3MzMsIm5iZiI6MTcyNjEyMzQzMywicGF0aCI6Ii8yNjMxNzQ4LzM2NjQzNDgyMy1mNzEwNWRlMS1lMjZmLTRhMjUtOTFiZi05MzE5NzhkN2RkMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDY0MzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNlNjhiYTgwNTJkZjU1ZmVlNGNkNTBkYmNmNzVhNmY5M2JiN2NiYzdiY2YxZTQ0NTk5Mjk0YmJiMWEyMGVhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hy0GxVip7zzdOq7C9yv-ZWkq1qUlCgHnD1sau-NN4Fg)
> 
> Я бы рекомендовал пересмотреть стили - тут можно неплохой baseline - [Bootstrap button-group](https://github.com/twbs/bootstrap/blob/dcec1df61f107e2b449486aafefbb1d14abe0333/scss/_button-group.scss#L36) с использованием margin-left: -1px для решения проблемы двойных границ и z-index:1 для "поднятия" элемента при фокусировке для корректного отображения границ поверх соседей)

незакрашенные уголки точно будем решать, спасибо за идеи с решением. Сейчас необходимо еще раз уточнить поведение и возьмем в работу.

**Comment by ickisIckis** [comment]
![image](https://github.com/user-attachments/assets/bc94de05-dd56-4f46-aff7-5260a4e5d243)

**Comment by PrizmDS** [comment]
Принято
