### ISSUE TITLE
[Feature] @prizm-ui/components - `PrizmQueryBuilder` component

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#2041]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/icons-loader`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

Разработка компонента _PrizmQueryBuilder_ в соответствии с [дизайн документом](https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-4.0?node-id=22432-251786)

**Comment by ickisIckis** [comment]
закрываю как дубликат https://github.com/zyfra/Prizm/issues/402
