### ISSUE TITLE
[Feature] table: Дизайн контрола выбора алгоритма фильтрации для столбца таблицы

### ISSUE THREAD

**Issue by elquid** [zyfra/Prizm#2050]
@PrizmDS @ifmalex, прошу рассмотреть возможность проработки дизайна контрола выбора алгоритма фильтрации для столбца таблицы.

Перечень доступных вариантов выбора должен зависеть от типа данных.
У разработчиков должна быть возможность задавать свои произвольные алгоритмы фильтрации.

Отображение выбранного варианта в виде иконки было бы плюсом.

![image](https://github.com/user-attachments/assets/8c9c907a-5004-4045-a524-b9256d4478b9)

**Comment by PrizmDS** [comment]
Макеты готовы. Ожидают разработки.

**Comment by imonogarov** [comment]
@PrizmDS просьба приложить ссылку

**Comment by PrizmDS** [comment]
https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-5.0?m=auto&node-id=39289-80811&t=qAflR26vgDLLtjLH-1

**Comment by ifmalex** [comment]
Сделали дизайн. Не пролезает в 5.4, пробуем в 5.5. 
@elquid насколько это срочно?

**Comment by elquid** [comment]
> Сделали дизайн. Не пролезает в 5.4, пробуем в 5.5. @elquid насколько это срочно?

Запрос касался только дизайна.
