### ISSUE TITLE
[Feature] Уменьшение бойлерплейта при выборе строк таблицы

### ISSUE THREAD

**Issue by alevya** [zyfra/Prizm#207]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/cb3-to-prizm`
-

### Компонент

[Table](https://prizm.site/components/table)

### Предложение
На данный момент при реализации выбора строк в таблице (single/multi) приходится писать однотипный код.  
Это трудозатратно в случае наличия множества таблиц в приложении.  

Хотелось бы иметь возможность не писать самостоятельно такой код благодаря наличию каких-либо директив, компонентов и прочего.

Например, в нашем случае пришлось реализовывать однотипное поведение для: 
 1. Актуализация состояний родительских узлов выбранного узла
 2. Хранение выбранных узлов внутри компонента
 
При необходимости могу показать на примере проекта, где столкнулись с подобными проблемами.

**Comment by alexhawkins94** [comment]
будет реализовано в датагридах
