### ISSUE TITLE
[BUG] @prizm-ui/theme - Could not resolve "Inter-italic.var.woff2"

### ISSUE THREAD

**Issue by juelruu** [zyfra/Prizm#2086]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [+] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

@prizm-ui/theme/src/styles/styles.less

### Версия

Операционная ситема: Windows 10 WSL: 2.2.4.0

Браузер:

Microsoft Edge 129.0.2792.65

NodeJS: 20.15.1

Dependencies:

➜ npm ls @prizm-ui/theme
@prizm-ui/theme@5.0.0 extraneous
└─┬ lib@0.9.159 -> ./projects/lib
  ├─┬ @prizm-ui/components@5.0.0
  │ └── @prizm-ui/theme@5.0.0 deduped
  └── @prizm-ui/theme@5.0.0

➜ npm ls @angular/core
@prizm-ui/components@0.0.2
├─┬ @angular/animations@18.2.6
│ └── @angular/core@18.2.6 deduped
├─┬ @angular/cdk@18.2.6
│ └── @angular/core@18.2.6 deduped
├─┬ @angular/common@18.2.6
│ └── @angular/core@18.2.6 deduped
├─┬ @angular/compiler@18.2.6
│ └── @angular/core@18.2.6 deduped
├── @angular/core@18.2.6
├─┬ @angular/forms@18.2.6
│ └── @angular/core@18.2.6 deduped
├─┬ @angular/platform-browser-dynamic@18.2.6
│ └── @angular/core@18.2.6 deduped
├─┬ @angular/platform-browser@18.2.6
│ └── @angular/core@18.2.6 deduped
├─┬ @angular/router@18.2.6
│ └── @angular/core@18.2.6 deduped
├─┬ @ng-web-apis/common@3.2.3
│ └── @angular/core@18.2.6 deduped
├─┬ @ng-web-apis/intersection-observer@3.2.3
│ └── @angular/core@18.2.6 deduped
├─┬ @ng-web-apis/mutation-observer@3.2.3
│ └── @angular/core@18.2.6 deduped
├─┬ @ng-web-apis/resize-observer@3.2.3
│ └── @angular/core@18.2.6 deduped
├─┬ @ngneat/until-destroy@10.0.0 extraneous
│ └── @angular/core@18.2.6 deduped
├─┬ @ngx-translate/core@15.0.0
│ └── @angular/core@18.2.6 deduped
├─┬ @ngx-translate/http-loader@8.0.0
│ └── @angular/core@18.2.6 deduped
├─┬ @prizm-ui/core@5.0.0 extraneous
│ └── @angular/core@18.2.6 deduped
├─┬ @prizm-ui/flag-icons@5.0.0 extraneous
│ └── @angular/core@18.2.6 deduped
├─┬ @prizm-ui/helpers@5.0.0 extraneous
│ └── @angular/core@18.2.6 deduped
├─┬ @prizm-ui/i18n@5.0.0 extraneous
│ └── @angular/core@18.2.6 deduped
├─┬ @prizm-ui/icons-loader@5.0.0 extraneous
│ └── @angular/core@18.2.6 deduped
├─┬ @prizm-ui/icons@5.0.0 extraneous
│ └── @angular/core@18.2.6 deduped
├─┬ @prizm-ui/theme@5.0.0 extraneous
│ └── @angular/core@18.2.6 deduped
├─┬ @storybook/angular@8.3.4
│ └── @angular/core@18.2.6 deduped
└─┬ lib@0.9.159 -> ./projects/lib
  ├─┬ @angular/cdk@18.2.6
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @angular/common@18.2.6
  │ └── @angular/core@18.2.6 deduped
  ├── @angular/core@18.2.6
  ├─┬ @angular/material@18.2.6
  │ ├─┬ @angular/animations@18.2.6
  │ │ └── @angular/core@18.2.6 deduped
  │ ├── @angular/core@18.2.6 deduped
  │ ├─┬ @angular/forms@18.2.6
  │ │ └── @angular/core@18.2.6 deduped
  │ └─┬ @angular/platform-browser@18.2.6
  │   └── @angular/core@18.2.6 deduped
  ├─┬ @ng-web-apis/common@3.2.3
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @ng-web-apis/intersection-observer@3.2.3
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @ng-web-apis/mutation-observer@3.2.3
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @ng-web-apis/resize-observer@3.2.3
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @ngneat/until-destroy@10.0.0
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @ngx-translate/core@15.0.0
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @prizm-ui/components@5.0.0
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @prizm-ui/core@5.0.0
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @prizm-ui/flag-icons@5.0.0
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @prizm-ui/helpers@5.0.0
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @prizm-ui/i18n@5.0.0
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @prizm-ui/icons-loader@5.0.0
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @prizm-ui/icons@5.0.0
  │ └── @angular/core@18.2.6 deduped
  ├─┬ @prizm-ui/theme@5.0.0
  │ └── @angular/core@18.2.6 deduped
  └─┬ ngx-mask@17.0.4
    └── @angular/core@18.2.6 deduped

```

### Проект в котором используется Prizm

- Local project

### Скрин / Видео проблемы

Could not resolve "Inter-italic.var.woff2" [plugin angular-css-resource]

    projects/lib/app/src/theme/theme.less:969:11:
      969 │   src: url('Inter-italic.var.woff2') format('woff2');

### Воспроизведение проблемы

1. В angular библиотеке project/lib/theme/src/theme/theme.component.ts создать компонент;
2. Подключить стили ./theme.component.less;
3. Добавить в ./theme.component.less строку @import "node_modules/@prizm-ui/theme/src/styles/styles.less";
4. Фиксировать ошибку

### Описание проблемы

Ошибка подключения шрифтов.

### Решение 
url('@{path-fonts}Inter-italic.var.woff2') format('woff2'),

**Comment by ZurabDev** [comment]
Есть файл theme/src/styles/styles_.less без указания месторасположение шрифтов, используйте его вместо styles.less после сможете подключить шрифты указавай на путь вашего ресурса
