### ISSUE TITLE
[Feature] ФТ. Форматы параметров ввода Даты-Времени без клавиатуры

### ISSUE THREAD

**Issue by IrinaArt901** [zyfra/Prizm#2103]
Компонент: datepicker and timepicker

### Доработать текущие компоненты согласно макетам https://www.figma.com/design/qWuEVFTWZBREHIwnn9XmTM/DataLink-Prizm?node-id=2128-163016&t=Jj33854N5bXUMsA3-4

 Работаю в рамках задачи  https://jira.zyfra.com/browse/PLATFORM01-45372

**Comment by PrizmDS** [comment]
Макеты готовы. Ожидают начала разработки.

**Comment by PrizmDS** [comment]
https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-5.0?m=auto&node-id=39720-253591&t=BheQL5h80GeGtMZ9-1

**Comment by alexhawkins94** [comment]
Приняли решение использовать "клеточный вариант".

1. @PrizmDS нужны макеты и описания для варианта таймпикера как в макетах Даталинка https://www.figma.com/design/qWuEVFTWZBREHIwnn9XmTM/DataLink-Prizm?node-id=2128-163016&t=Jj33854N5bXUMsA3-4 

2. Задачу декомпозируем на этапы:
-сперва реализовать timepicker отдельно (по аналогии как с calendar) 
-затем внедряем в дейтпикеры, начиная с  ? - уточнить приоритет внедрения в дейтпикеры @IrinaArt901 и завести соотв. задачу

3. Вынести отдельной задачей реализацию футера для дропдаунов дейтпикера и таймпикера (с кнопками "закрыть", "сохранить/отменить")

**Comment by PrizmDS** [comment]
Макеты:
https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-5.0?m=auto&node-id=39851-136374&t=IXsi7geJk77GkSmC-1

**Comment by PrizmDS** [comment]
Описания:
https://prizmds.gitbook.io/documentation/components/time-picker
