### ISSUE TITLE
[Feature]Обновление зависимостей

### ISSUE THREAD

**Issue by vladikKBR85** [zyfra/Prizm#2125]
### Библиотека

- [x] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [x] `@prizm-ui/install`
- [x] `@prizm-ui/icons`
- [x] `@prizm-ui/icons-loader`
- [x] `@prizm-ui/flag-icons`
- [x] `@prizm-ui/theme`
- [x] `@prizm-ui/charts`
- [x] `@prizm-ui/ast`
- [x] `@prizm-ui/nx-plugin`
-

### Предложение

Добрый день, коллеги. 

Мы крайне заинтересованы в использовании PrizmUI версии 4.5. 

Но, к сожалению, имеются уязвимости в зависимостях. 
Соответственно при внедрении, наше ПО будет забраковано отделами ИБ.
Результат выборки из отчета SCA во вложении.

Возможно ли обновить эти пакеты? Если да, то можно ли сориентировать по срокам?
[prizm_0.4.0.json](https://github.com/user-attachments/files/17378677/prizm_0.4.0.json)

**Comment by ZurabDev** [comment]
Дорый день. Приняли задачу, происледуем, и ответим тут.

**Comment by ickisIckis** [comment]
@vladikKBR85, добрый день. Мы исследовали проблему и не нашли инофрмации об уязвимостях в упомянутых пакетах. Не могли бы вы связаться с командой для уточнения вопроса?
Нас можно найти, например, в тг - @prizmcom

**Comment by vladikKBR85** [comment]
> @vladikKBR85, добрый день. Мы исследовали проблему и не нашли инофрмации об уязвимостях в упомянутых пакетах. Не могли бы вы связаться с командой для уточнения вопроса? Нас можно найти, например, в тг - prizmcom

Добрый день. Спасибо, свяжемся!

**Comment by vladikKBR85** [comment]
> @vladikKBR85, добрый день. Мы исследовали проблему и не нашли инофрмации об уязвимостях в упомянутых пакетах. Не могли бы вы связаться с командой для уточнения вопроса? Нас можно найти, например, в тг - prizmcom

Не могли бы вы написать на этот e-mail: Anatem@mail.ru ? Чтобы не переводить вопрос в публичную плоскость

**Comment by ickisIckis** [comment]
@imonogarov, обрати внимание, пожалуйста

**Comment by vladikKBR85** [comment]
> @imonogarov, обрати внимание, пожалуйста

Добрый день. Не удалось связаться? Или может вы нам контакт оставите?

**Comment by imonogarov** [comment]
@vladikKBR85 Добрый день. Написал на почту.
