### ISSUE TITLE
[BUG] @prizm-ui/components - переопределение data-prizm-theme на 'light'

### ISSUE THREAD

**Issue by bumalai** [zyfra/Prizm#2201]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [x] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [x] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Theme

### Версия

Prizm v4, Prizm v5

### Проект в котором используется Prizm

Платформа

### Скрин / Видео проблемы

<img width="239" alt="image" src="https://github.com/user-attachments/assets/25e5d6e4-8baf-418a-81ca-2d6f257d4a9c">

### Описание проблемы

При уже установленной теме в платформе и уже существующем атрибуте data-prizm-theme, при старте приложения в микрофронте, тема заменяется по умолчанию на light,

Необходимо чтобы тема не переопределялась, если уже установлен данный атрибут. А брала существующую тему

**Comment by ickisIckis** [comment]
Данный фикс нет возможности проверить на стороне призм, скорее всего потребуется выпуск next сборки и проверка на стороне проектов.
