### ISSUE TITLE
[BUG] Select - Для false-like значения не вызывается stringify

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#228]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_SelectComponent_

### Версия

latest

### Скрин / Видео проблемы

_![select_stringify](https://user-images.githubusercontent.com/2631748/235185610-887ef304-9217-498a-8e75-f039be3735c0.gif)_

### Описание проблемы

При установке false-like значений (false, null, undefined, '', 0),  stringify не отрабатывает

В примере выше: Вручную и Автоматически транслируются в false/true значения formControl
По итогу строковое представление не отображается как для начального так и при смене значения.

https://github.com/zyfra/Prizm/blob/dd97d0d5780980395a9427ba3f37d77b72aedab6/libs/components/src/lib/components/dropdowns/select/select.component.ts#L267

P.S. заметил [дублирующий вызов `updateValue`](https://github.com/zyfra/Prizm/blob/dd97d0d5780980395a9427ba3f37d77b72aedab6/libs/components/src/lib/components/dropdowns/select/select.component.ts#L238)

**Comment by AleksandrSibiakov** [comment]
В версии 1.0.0-rc.1 все еще воспроизводится.

**Comment by AleksandrSibiakov** [comment]
Посмотрел чуть дальше. Вызов `stringify` делается, но для самого контрола `this.select(value);` срабатывает второй раз из `refreshLocalValue` со значением `FormControl`-а. А не айтема! `item` != `formControl.value` и stringify проваливается.
У нас например селекты так устроены:
`items: [{id: T; name: string}]`
`stringify = (item) => item.name`
`valueTransformer : { toControlValue(componentValue) {
                return componentValue?.id;
            }`

**Comment by alexhawkins94** [comment]
@AleksandrSibiakov актуально ?

**Comment by AleksandrSibiakov** [comment]
Насчет последнего комментария - не знаю. Мы изменили имплементацию в приложениях, так что если проблема и осталась, нашли обходной путь.
Если наткнемся, заведем еще раз, все равно версии уже ушли вперед, да и сам контрол deprecated стал
