### ISSUE TITLE
[BUG] @prizm-ui/components - Не корректно отображается хинт около границы вьюпорта

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#229]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Hint](https://doc.prizm.zyfra.com/components/hint)

### Описание проблемы

На элемент вешается хинт с опцией `prizmHintDirection="b"`. В этом случае подсказка при наведении отображается снизу элемента. Но если элемент расположен около вьюпорта страницы (граница вьюпорта справа от элемента), то подсказка отображается сверху. А если задать  `prizmHintDirection="t"`, то всё ровно наоборот.

Необходимости в таком поведении не видится, скорее всего это баг.

**Comment by AleksandrSibiakov** [comment]
За ре-позиционирование отвечает параметр `autoReposition` (`prizmAutoReposition`). По-умолчанию он `auto` и как раз отвечает за то, чтобы контент дропадауна (хинта, поповера и т.п.) "вписывался" во вьюпорт.
Если это поведение не нужно, попробуй передать в инпут `false`.
@dkshichkovskiy
