### ISSUE TITLE
[BUG] @prizm-ui/components - Не отрабатывает событие изменения в prizm-toggle

### ISSUE THREAD

**Issue by zerodi** [zyfra/Prizm#234]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

prizm-toggle

### Версия

```
@prizm-ui/components 1.0.0-beta.35
```

### Описание проблемы

При изменении значения prizm-toggle без использования formControl не отрабатывают события изменения значения.

**Comment by zerodi** [comment]
Должна, но она так же не срабатывает.

**Comment by alexhawkins94** [comment]
@zerodi  @AleksandrSibiakov  актуально или ?

**Comment by AleksandrSibiakov** [comment]
Да вроде закрыли уже давно - видимо не актуально.
