### ISSUE TITLE
[BUG] @prizm-ui/components - Select сбрасывает значение formControl, если options приходят с опозданием

### ISSUE THREAD

**Issue by AntonGrekov** [zyfra/Prizm#245]
### Библиотека
- [x ] `@prizm-ui/components`

### Компонент
PrizmSelectComponent

### Проект в котором используется КБ
IDP

### Описание проблемы
В случае если **items** для PrizmSelectComponent приходят с запозданием, как в моем случае(они приходят из селекта ngrx), то предварительно заданное значение для formControl/ngModel сбрасывается в undefined. И когда уже options в итоге задаются, то значение formControl так и остаётся undefined 😞. 

```html
<prizm-select 
      [items]="policies"
      forceClear]="false"
      [(ngModel)]="formValue"
      ...
></prizm-select>
````

Решается небольшим костылём  добавляя такой ngIf:
```html
<zss-search-select
        *ngIf="policies && policies.length"
        [items]="policies"
        ....
></zss-search-select>
````

_Шаги воспроизведения_:

1. Добавить prizmSelect
2. Определить для него пустой массив items изначально
3. Задать значение по умолчанию - ngModel/FormControl
4. С небольшой задержкой задать массив items

ОР:
Заданное на шаге 3 значение выбралось в селекте

ФР:
Заданное значение не выбралось. В селекте отображается не выбранное значение. Если правильно помню, то оно вроде только визуально не отображается, у FormControl значение остаётся заданным в шаге 3.

**Comment by bumalai** [comment]
А ты пробовал вызывать changeDetectRef.detectChanges?
