### ISSUE TITLE
[BUG] @prizm-ui/components - Не отображается содержимое страницы с компонентом если выполнен переход из To Observable

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#247]
### Скрин / Видео проблемы

![chrome_ZZyi0rGIqN](https://github.com/zyfra/Prizm/assets/122870313/7f2f0713-1227-4041-a534-7d4c88118a50)

### Описание проблемы

_Шаги воспроизведения_:

1. Перейти в Tools/To observable
2. Затем перейти в любой компонент или график
Фактический результат: содержимое страницы не отображается, в консоли Error

**Comment by ZurabDev** [comment]
Не возможно воспроизвести, если воспроизводиться просьба отписаться
