### ISSUE TITLE
[BUG] @prizm-ui/components - Для кнопок PrizmSidebarService нельзя установить disabled state

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#261]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

[SideBar](https://doc.prizm.zyfra.com/components/dialogs/sidebar)

### Версия

1.0.0-rc.1

### Описание проблемы

При прокидывании кнопок в вызов метода `sidebarService.open` нельзя задать условия, при которых блокируются эти кнопки. В настоящий момент типизация позволяет задать поле `disabled` (с типом `boolean`), но его значение по факту игнорируется.

```javascript
this.sidebarService
  .open(new PolymorphComponent(SomeComponent, this.injector), {
    ...
    confirmButton: {
      text: 'Button'
      disabled: true,
    },
  });
```

Хотелось бы иметь возможность определять условия блокировки таких кнопок: чтобы поле `disabled` не игнорировалось и в качестве его значения можно было бы указать `Observable<boolean>`.

**Comment by dkshichkovskiy** [comment]
@ZurabDev Свойство `disabled` заработало, спасибо. 

В описании issue так же идёт речь про тип Observable<boolean> для этого свойства. Можно ли такую возможность добавить?

**Comment by ZurabDev** [comment]
@dkshichkovskiy списобо @skkonstantin это он делал. А по поводу Observable можешь создать с этими issues плиз
