### ISSUE TITLE
[Feature] Добавить возможность переопределять padding у prizm-accordion

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#262]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Accordion](https://doc.prizm.zyfra.com/components/accordion)

### Предложение

Сейчас у содержимого prizm-accordion (`.accordion__content`) есть статично заданный `padding: 16px`. Возникают кейсы, когда этот padding нужно изменить, в частности установить в `0`. Например, если в содержимое accordion вставляется таблица. 

Предлагаю добавить такую возможность через css custom property, как это сделано, например, в prizm-widget (` --prizm-widget-content-padding`).

**Comment by bumalai** [comment]
А быть может что так и задумывалось что будет всегда 16px даже для табличного случая?

**Comment by dkshichkovskiy** [comment]
Если у компонента prizm-widget есть такая настройка, то и здесь она по идее должна быть. Т.к. ситуация одна и та же. Для табличного случая наличие padding выглядит не уместным + противоречит макетам проекта, сделанным на Prizm.
