### ISSUE TITLE
[BUG] @prizm-ui/components - В prizm-tab в [content] нельзя передать PolymorphComponent 

### ISSUE THREAD

**Issue by MalkovaTE** [zyfra/Prizm#265]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

PrizmTabs, PolymorphComponent, PolymorphOutletDirective

### Версия

Операционная система:

Windows 11

Браузер:

Версия 113.0.5672.93 (Официальная сборка), (64 бит)

NodeJS:

v16.14.0

Dependencies:
@prizm-ui/components 1.0.0-rc.1

### Скрин

![image](https://github.com/zyfra/Prizm/assets/27860995/ec9ac9f8-dbe9-47bd-8961-36c00d1fad33)

### Описание проблемы

В документации content принимает PolymorhContent
При передаче в prizm-tab в [content] PolymorphComponent происходит ошибка (скриншот).
При этом работает передача в  [content] элемента ng-template. 

Шаги воспроизведения:

```
 public component= new PolymorphComponent(SomeComponentType);

<prizm-tabs [(activeTabIndex)]="activeTabIndex">
        <prizm-tab [content]="component" type="line"></prizm-tab>
</prizm-tabs>

```

**Comment by ZurabDev** [comment]
Добавим пример в доку и проверим

**Comment by ZurabDev** [comment]
<img width="791" alt="CleanShot 2023-06-15 at 13 16 50@2x" src="https://github.com/zyfra/Prizm/assets/75216044/3f7b64fa-be3c-477f-a273-7f445e86a3ec">
Готово. Добавлен пример
