### ISSUE TITLE
[BUG] prizm/components - Ширина выпадашки InputDate не соответствует размеру календаря

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#27]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/theme`

### Компонент

Inputs, InputDate

### Версия

Операционная система:

`Windows 10,`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Проект в котором используется КБ

- _СОУ_
- https://ziiot-dev-11.kube01.yc.ziiot.ru/components/input-date

### Скрин / Видео проблемы

Актуальное поведение:
![image](https://user-images.githubusercontent.com/26089012/215953325-c8317bda-0c33-47f5-825a-379444fff051.png)
![image](https://user-images.githubusercontent.com/26089012/215953459-65b48f4a-0cbe-4538-a91b-b9290bb4b292.png)

Ожидаемое поведение:
![image](https://user-images.githubusercontent.com/26089012/215956362-5686175e-1758-41dd-9527-f7f12d17903a.png)

### Описание проблемы

_Есть проблема следующего характера:_

Выпадашка календаря стала 100% соответствовать ширине инпута. Из-за этого происходит 2 дефекта, проиллюстрированные скриншотами. Воспроизводится на публичном стенде, вижу только на InputDate, остальные корректно отображаются.

_Шаги воспроизведения_:

1. Зайти по адресу https://ziiot-dev-11.kube01.yc.ziiot.ru/components/input-date
2. Выбрать дату через picker

Проблема появилась после коммита `feat(doc): small changes` cb61f3d2e320fdf885cfdb40c15dde384754f9a7
![image](https://user-images.githubusercontent.com/26089012/215954772-f684a2bb-a3b9-447c-8804-9e4611aeec44.png)

В changelog также не отмечено зачем необходимо изменение, поэтому не знаю можно ли просто вернуть назад.

**Comment by ZurabDev** [comment]
Выясняем причину добавления

**Comment by bree7e** [comment]
Удалось выяснить причину?

**Comment by ZurabDev** [comment]
<img width="680" alt="CleanShot 2023-02-16 at 09 53 23@2x" src="https://user-images.githubusercontent.com/75216044/219290244-67b7f694-e35b-45c5-9469-84fb02c86344.png">
https://prizmui--pr50-release-1-0-0-beta-2-e40i5pvy.web.app/components/input-date

готово
