### ISSUE TITLE
[BUG] @prizm-ui/components - prizm-overlay-dropdown-host открывается вне рабочей области

### ISSUE THREAD

**Issue by dezisque** [zyfra/Prizm#270]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Prizm Tabs, prizm-overlay-dropdown-host 

### Версия
    "@prizm-ui/components": "^1.0.0-beta.26",
    "@prizm-ui/core": "^1.0.0-beta.26",
    "@prizm-ui/helpers": "^1.0.0-beta.26",
    "@prizm-ui/i18n": "^1.0.0-beta.27",
    "@prizm-ui/icons": "^1.0.0-beta.26",
    "@prizm-ui/theme": "^1.0.0-beta.26",

Операционная ситема:

MacOS, Windows

Браузер:

`Google Chrome Версия 113.0.5672.92 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.15.1

```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components@1.0.0-beta.28

```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Проект в котором используется КБ

- Stream 

### Скрин / Видео проблемы

<img width="351" alt="image" src="https://github.com/zyfra/Prizm/assets/35841155/29189bf5-c542-4b58-8ef7-bd032e92bd2a">

### Описание проблемы

при открытии дропдауна вкладок в компоненте Prizm Tabs всплывающее окно появляется справа от кнопки открытия данного окна. В случае, если кнопка находится близко к правому краю рабочей области, дропдаун открывается вов не рабочей области.

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](https://doc.prizm.zyfra.com)
2. ...

**Comment by ZurabDev** [comment]
<img width="758" alt="CleanShot 2023-05-19 at 11 48 53@2x" src="https://github.com/zyfra/Prizm/assets/75216044/8b7d445d-0dfd-4c77-b062-7751884b0024">


не можем воспроизвести

**Comment by dezisque** [comment]
попробуйте на этой странице убрать марджины и паддинги, чтобы компонент был прижат к правому краю страницы
<img width="537" alt="image" src="https://github.com/zyfra/Prizm/assets/35841155/316b8fc1-0cf5-43dd-8c19-8ded84db3093">
