### ISSUE TITLE
[BUG] @prizm-ui/components - Проблемы с layout в Widget

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#273]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

[Widget](https://prizm.site/components/widget)

### Версия

1.0.0-rc.1

### Описание проблемы

Если поместить prizm-widget в сплиттер и сокращать область через контрол сплитера, то шапка prizm-widget (элемент `.header`) начнёт сжиматься.

Проблема фиксится через следующие стили:
```css
prizm-widget > prizm-card > .header {
  flex-shrink: 0;
}
```

**Comment by ZurabDev** [comment]
Можете прислать скриншот или детальнее описать что ожидается
