### ISSUE TITLE
[BUG] @prizm-ui/components - Не работает size='s' в Select, MultiSelect

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#275]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Select](https://prizm.site/components/dropdowns/select), [MultiSelect](https://prizm.site/components/dropdowns/multi-select)

### Версия

1.0.0-rc.1

### Описание проблемы

Если установить у prizm-select, multi-prizm-select размер `s` (а это допустимое значение), то контрол ведёт себя аналогично значению `l`. Возможно, такая же проблема имеется у других полей формы, не проверяли. 

Контрол формы с таким размером нужен для встраивания в ячейки таблиц.

**Comment by alexhawkins94** [comment]
а используется inner или outer?

**Comment by dkshichkovskiy** [comment]
> а используется inner или outer?
Inner. Не знал про опцию outer=boolean. Сделал outer, заработало. Спасибо!
