### ISSUE TITLE
[Feature] Адаптация стилей контролов формы при встраивании в таблицу

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#276]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

Контролы формы. Например, Select

### Предложение

Возникла необходимость встроить Select в ячейку таблицы. Если это сейчас сделать, получаем следующее отображение:

![image](https://github.com/zyfra/Prizm/assets/52266097/d699749d-5fa1-4cce-8b1f-05f076322559)

Предлагается сделать так, чтобы при встраивании для контрола устанавливались такие стили, чтобы отсутствовали рамка, фон, outline, тени. Возможно, имеет смысл использовать значение `transparent`. Чтобы результат был, например, таким:

![image](https://github.com/zyfra/Prizm/assets/52266097/87d6dace-2476-46c5-977c-f6ba714cbf20)

С проблемой столкнулись только у Select. Но вероятно это касается и других контролов.

**Comment by alexhawkins94** [comment]
В работе у дизайнеров, ждем итогов.
Пока концептуальная идея такая:
-добавим возможность скрывать фон у инпута

-использовать border = false
-outer = true
-label = null

**Comment by javadoffuad** [comment]
@ZurabDev @alexhawkins94 есть еще проблема с внешними и внутренними отступами контрола
![image](https://github.com/zyfra/Prizm/assets/7090093/e93842f7-0605-4549-8656-17e9950b2c38)

**Comment by PrizmDS** [comment]
В таблицы будет добавлена отдельная ячейка Select и другие. Будет добавлена возможность отключать стили Input для встраивания в таблицу

**Comment by ickisIckis** [comment]
#408
