### ISSUE TITLE
[BUG] @prizm-ui/components - Меняется цвет навигации при скрытии бокового меню.

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#278]
### Скрин / Видео проблемы

![chrome_KShZCuTfBl](https://github.com/zyfra/Prizm/assets/122870313/4406c61f-70e8-47a4-8090-6c0b61d6af6f)

### Описание проблемы

_Шаги воспроизведения_:

1. Перейти в components/navigation
2. Нажать на "гамбургер" рядом с эмблемой нефтеконтроля (либо прям на нее)
Фактический результат: происходит переключение цвета

**Comment by ZurabDev** [comment]
https://app.replay.io/recording/prizm-ui-navigation--ac96f990-ba9f-4c59-aa8e-f34fd1c9f5b8
