### ISSUE TITLE
[BUG] @prizm-ui/components - Switcher. Убрать рамку фокуса

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#279]
### Скрин / Видео проблемы

![photo_2023-05-17_16-43-13](https://github.com/zyfra/Prizm/assets/122870313/0dd7b5ef-beee-4b08-998e-af7ede209dfb)

### Описание проблемы
В текущей реализации у свичтера есть рамка фокуса. 
Выглядит это не очень красиво, решили что нужно убрать эту рамку.

д.б так 
![photo_2023-05-17_16-42-36](https://github.com/zyfra/Prizm/assets/122870313/62b03dce-93db-4ae9-a8ee-c0fecaa47df0)

**Comment by alexhawkins94** [comment]
Denis Avksentev
--
  | Ответ простой. Совпадает цвет фокуса и цвет заливки пункта свичера. Чтобы этого избежать, фокус должен появляться за контуром контейнера, тогда серая обводка будет видна и сливаться не будет. Возможно это пофикшено на данный момент, ибо описания делались очень давно

**Comment by ZurabDev** [comment]
<img width="509" alt="CleanShot 2023-07-13 at 12 58 06@2x" src="https://github.com/zyfra/Prizm/assets/75216044/f0f68538-2522-4c4f-85b2-3a419273f519">
Готово
