### ISSUE TITLE
[BUG] @prizm-ui/components - InputMask. В live demo не получается ввести текст в инпут с маской

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#281]
### Описание проблемы
-Перейти к live demo компонента input mask
-Отображается маска вида _:_
-Ввести текст в инпут с маской (например, цифры)
Фактический результат: удается ввести цифры только до двоеточия. в секции после двоеточия ввод невозможен

**Comment by ZurabDev** [comment]
<img width="579" alt="CleanShot 2023-06-15 at 11 16 06@2x" src="https://github.com/zyfra/Prizm/assets/75216044/ac9dcafc-cdb7-4591-b960-dd3b7feeba0c">
Готово
