### ISSUE TITLE
[Feature] prizm/components - Возможность поиска в prizm-select

### ISSUE THREAD

**Issue by codeagent** [zyfra/Prizm#29]
### Библиотека

- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/theme`

### Компонент

``prizm-select``

### Предложение

Нужно выбрать одно значения из большого списка. С-но ``prizm-select`` используется с флагом ``searchable: true``.
Но так компонент работает в режиме autocomplete (можно вводить произвольный текст что может сбить с толку).

Есть ли возможность добавить поиск в саму выпадашку, чтобы он был подобно ``prizm-multi-select`` но выбрать можно было строго один элемент?
Можно ли добавить какой-либо механизм для ленивой подгрузки списка?

![image](https://user-images.githubusercontent.com/6485588/216088508-68c6a353-25cf-4587-820a-ada95eb838fb.png)

**Comment by ifmalex** [comment]
«_Но так компонент работает в режиме autocomplete (можно вводить произвольный текст что может сбить с толку)._» – нужны метрики, что это сбивает с толку. Сейчас это гипотеза. При разработке мы ориентировались именно на 1 быстрое действие при заполнении больших данных.
На research возьмём. Работу это не блокирует.
По ленивой догрузке @ZurabDev
