### ISSUE TITLE
Есть возможность кликнуть по неактивному tab

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#3]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Tabs

### Проект в котором используется КБ

- Конфигуратор
- https://gitlab.idp.yc.ziiot.ru/digital-plant/stream/zui-app-om-configurator
- https://stream-dev-01.kube02.yc.ziiot.ru/zui-app-om-configurator

### Описание проблемы

Есть возможность кликнуть по неактивному табу, хотя установлен атрибут disabled=true

**Comment by ZurabDev** [comment]
Готово
