### ISSUE TITLE
[BUG] @prizm-ui/components - PrizmInputStatusSubtextComponent - Визуально заметен даже если нет ошибок

### ISSUE THREAD

**Issue by stepandr** [zyfra/Prizm#300]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

prizm-input-status-subtext -> PrizmInputStatusSubtextComponent

### Версия

Операционная система:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.0.0-rc.2
```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Проект в котором используется КБ

--

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/11865854/c8719997-f482-4e46-a509-507d1c49dc0a)

### Описание проблемы

<prizm-input-status-subtext prizm-input-subtext [control]="input"></prizm-input-status-subtext>

При отсутствии ошибок все равно занимает место и по сути остается пустая строка, которая портит дизайн, если дальше идут еще input

_Есть проблема следующего характера:_

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](https://doc.prizm.zyfra.com)
2. https://doc.prizm.zyfra.com/components/input
3. Открыть отладчик и увидеть в dom

Предлагаю при отсутствии ошибок не показывать данный элемент визуально

**Comment by bumalai** [comment]
Из документации:
> При наведении на иконку статуса появляется всплывающее сообщение (hint) об ошибке / рекомендациях по исправлению. Используйте этот способ для оптимизации полезного пространства рабочей области. 2. Подсказка снизу.
Такой способ наиболее эффективен в плане скорости сообщения пользователю, но “съедает” пространство, которое мы закладываем под подсказку. !!! Место под подсказку должно быть заложено на этапе проектирования - не допустимо смещение контента под вывод сообщения.

https://prizm.site/components/input#icon-buttons

то есть если два и более, то нужно убрать subtext на вашей стороне,
