### ISSUE TITLE
[BUG] @prizm-ui/components - CalendarMonth. Отсутствует ховер при наведении на месяц

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#301]
### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/122870313/35e000de-4dcc-4a74-ab25-e49ea1779b47)

### Описание проблемы

-Навести курсор на месяц
Фактический результат: Отсутствует ховер при наведении на месяц

**Comment by ZurabDev** [comment]
<img width="342" alt="CleanShot 2023-06-16 at 01 11 08@2x" src="https://github.com/zyfra/Prizm/assets/75216044/3dd92e1f-ecab-4260-a50a-faacc7e4ebc2">
Готово
