### ISSUE TITLE
[BUG] @prizm-ui/components - Tabs. Не отоброжаются некоторые иконки в табах

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#306]
## Описание проблемы

-Перейти в live demo табов
-В атрибуте [icon]выбрать иконку account-group или arrows-autorenew
Фактический результат: иконка отображается как битая/не отображается корректно. Если проверить эту иконку в Icons, то там она отображается нормально

![image](https://github.com/zyfra/Prizm/assets/122870313/701f40f8-aeb2-4fab-a865-eb60b0a2730c)

**Comment by ickisIckis** [comment]
Нужно проверить в 4.0 вместе с иконками
