### ISSUE TITLE
При вызове confirmDialog возникают ошибки в консоли

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#31]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Confirm Dialog

### Проект в котором используется КБ

- Конфигуратор
- https://gitlab.idp.yc.ziiot.ru/digital-plant/stream/zui-app-om-configurator/-/tree/dev-v2

### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/17219726/216235849-6f5db0b0-c328-4983-9746-f63d61c2251d.png)

### Описание проблемы

При вызове confirmDialog возникают ошибки в консоли. На сайте с документацией проблема также воспроизводится:

![image](https://user-images.githubusercontent.com/17219726/216235972-902a0aef-2830-46f2-a041-78d2ac96c999.png)

**Comment by ZurabDev** [comment]
Это не бага, сделаем их warning, означает что не переданы все значения и поэтому будут использоваться дефолтные

**Comment by ZurabDev** [comment]
Просьба проверить 23 версии
