### ISSUE TITLE
[BUG] @prizm-ui/components - Неправильно выводится значение в поле InputSelect

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#314]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[InputSelect](https://prizm.site/components/input-select)

### Версия

1.0.0-rc.2

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/48792714/66c12a7b-18d4-4d13-bd19-2aebfab95739)

### Описание проблемы

При использовании компонента InputSelect с реактивной формой, в случае, когда  items это массив объектов, а FormControl объект содержащий только ключ (id) обхекта из items, то занчение в контроле выводится неправильно, отображается пустая строка. Ошибка также воспроизводится в примере на витрине https://prizm.site/components/input-select (см. скрин)

**Comment by ZurabDev** [comment]
<img width="739" alt="CleanShot 2023-05-24 at 05 27 01@2x" src="https://github.com/zyfra/Prizm/assets/75216044/bdf28043-ef7c-468b-8564-1e9cb76dfe07">
Готово

**Comment by ZurabDev** [comment]
Видео https://app.replay.io/recording/prizm-ui-input-select--c578e31c-dc03-48b8-9eaf-8b12a141e6d4
