### ISSUE TITLE
[BUG] @prizm-ui/components - Краткое описание проблемы

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#315]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Input](https://prizm.site/components/input)
[InputSelect](https://prizm.site/components/input-select)

### Версия

1.0.0-rc.2

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/48792714/6e5f404b-ebac-4fe2-b882-2374a684c654)

### Описание проблемы

Не отображается текст подсказки для Input, InputSelect содержащие ошибки валидации. Воспроизводится на сайте витрины https://prizm.site/components/input (см. скрин)

**Comment by ZurabDev** [comment]
Не можем воспроизвести. Записи во вложении
https://app.replay.io/recording/prizm-ui-dropdownhost--92cc5890-9fda-4d6d-a709-ef6c5d15feb8
https://app.replay.io/recording/prizm-ui-input-select--ec9c8f76-49e5-4f5d-a32b-1e99af64e38a

**Comment by ZurabDev** [comment]
https://app.replay.io/recording/prizm-ui-input-select--844addbf-b367-43fb-a0d1-952f9800d9ac
Готово
