### ISSUE TITLE
[BUG] @prizm-ui/components - DropdownHost не реагирует на изменение [isOpen]

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#316]
### Библиотека

`@prizm-ui/components@1.0.0-rc.2`

### Компонент

_DropdownHost_ (директива используется в широком спектре компонентов)

### Описание проблемы

После апдейта до rc.2 контролы с дропдауном (_новый_ селект, календари и т.д.) перестали открываться (точнее "моргает" открыть\закрыть).

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](https://prizm.site/components/dropdowns/dropdown-host/Live_demo)
2. открыть\закрыть дропдаун кликом по элементу
3. попытаться открыть дропдаун через инпут [isOpen] (используя переключатель)

Видим, что срабатывает два евента - `openChange: true` + `openChange: false`
В некоторых случаях никакие евенты не триггерятся (четкой зависимости не выявлено)

NOTE: с выключенным [closeOnOutsideClick] все работает ОК

**Comment by ZurabDev** [comment]
https://app.replay.io/recording/prizm-ui-dropdownhost--d0c5dc16-fe17-4f00-855b-9d34caa3beb4
Готово

**Comment by AleksandrSibiakov** [comment]
@ZurabDev обновились до 1.0.0 - продолжаем наблюдать проблему ( Дропдаун открывается и тут же закрывается.

**Comment by ZurabDev** [comment]
воспроизвести не получается у меня, можешь как то шаги воспроизведения скинуть

**Comment by AleksandrSibiakov** [comment]
Upd: перепроверил билд в production - похоже в первый раз было совпадение, что все открывалось, со второго раза - открывается "иногда", но чаще нет. Продолжаю проверку теорий...

**Comment by AleksandrSibiakov** [comment]
![image](https://github.com/zyfra/Prizm/assets/2631748/2eb84b09-1e4a-4821-9a8b-e66576b785b9)
+
![image](https://github.com/zyfra/Prizm/assets/2631748/0940662c-4f38-4e17-8c17-d4cf3466555d)

Точно причина `outside$.next` (по стек трейсу). 
Вижу, что один из соурсов `this.inside$$`, он и вызывает заход в обработчик, но как видно из скриншота, время обработки клика до захода в обработчик больше чем FPS!
Видимо, проблема в том что приложение тяжелее чем микро демо...
