### ISSUE TITLE
[Feature] - Помечать deprecated компоненты в основном меню витрины

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#339]
### Предложение

На текущий момент у нас есть множество deprecated компонентов. Они все отображаются в основном меню витрины и заранее невозможно узнать какой из этих компонентов deprecated.
То что компонент устарел отображется только в описании самого компонента и это можно увидеть только если перейти на страничку компонента. Это не удобно.

Предлагаю либо явно помечать эти компоненты в основном меню, либо сделать новый раздел меню и перенести туда все deprecated legacy штуки

**Comment by ZurabDev** [comment]
deprecated будут в 2.1.0 удалены
