### ISSUE TITLE
[BUG] @prizm-ui/components - Select Проблема с отображением hint

### ISSUE THREAD

**Issue by RoxVell** [zyfra/Prizm#343]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

Select

### Версия

MacOs Ventura 13.3.1

Браузер:

`Версия 113.0.5672.126 (Официальная сборка), (arm64)`

NodeJS:

```
➜ node --version
v16.19.0
```

### Скрин / Видео проблемы

<img width="357" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/2938849e-17b6-453c-b22f-5fb7bfd0003a">

### Описание проблемы

Неправильно отображется хинт "Обязательное поле" при наведении на контрол с пустым значением

Шаги воспроизведения:

1. Зайти по адресу [prizm/select](https://doc.prizm.zyfra.com/components/dropdowns/select)
2. В секции base нажать на кнопку очищения поля (крестик) и навести курсор на иконку с информацией об ошибке 
<img width="34" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/cbdd5858-4417-4092-aefb-cbd17952777f">

**Comment by alexhawkins94** [comment]
@RoxVell там старая версия по ссылке + старая версия селекта
актуальное можно посмотреть тут https://prizm.site/components/input-select

**Comment by badeevdm** [comment]
@ZurabDev, а можно реализовать отображение кастомного текста аналогично как было сделано для компонента input?
```html
    <prizm-input-layout>
      <input prizmInput [formControlName]="control" />
      <ng-template prizmInputStatusText>{{
        'ErrorRequired'
      }}</ng-template>
    </prizm-input-layout>
```

**Comment by ZurabDev** [comment]
@RoxVell все должно будет работать вот issue https://github.com/zyfra/Prizm/issues/346 сегодня будет next версия с этими а во вторник основной релиз
