### ISSUE TITLE
[BUG] @prizm-ui/components Sidebar.Не применяется свойство closeWorld.

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#352]
### Описание проблемы

-Перейти в live demo для sidebar
-Задать новое значение для closeWord
-Не задавать футер (null)
-Вызвать sidebar
Фактический результат: не отображается заданное значение в кнопках сайдбара

**Comment by ZurabDev** [comment]
свойство не поддерживалось, убрали из доки и обновили пример base
