### ISSUE TITLE
[BUG] @prizm-ui/components - Input Layout, markAsTouched() не срабатывает для обязательного поля с пустым значением.

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#353]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[InputSelect](https://prizm.site/components/input-select)
[Input](https://prizm.site/components/input)

### Версия

1.0.0

### Воспроизведение проблемы

Пример:

https://stackblitz.com/edit/ngx-14-title-demo-lj197j?file=src%2Fapp%2Fapp.component.html

### Описание проблемы

Попытка провалидировать обязательные поля формы, которые не были введены пользователем, через вызов form.markAsTouched() не валидирует поля, не появляется красная обводка.

**Comment by AleksandrSibiakov** [comment]
```
this.requiredInputControl.markAsTouched();
this.requiredInputControl.updateValueAndValidity();
```
does the job 

Проверил на stackblitz выше. 

Проблема изначально в том что `markAsTouched` не вызывает никаких реактивных изменений. Надо вручную вызывать циклы CD либо (как сделал я) - перезапустить проверки что приводит к триггеру `statusChange`, который основной источник проверки изменений input-layout

**Comment by badeevdm** [comment]
@AleksandrSibiakov, спасибо решение мне подходит.

**Comment by badeevdm** [comment]
@AleksandrSibiakov, @ZurabDev прошу прощения, поторопился с закрытием. Попробовал вызов updateValueAndValidity для input, работает как ожидается. А вот если вызвать тот же методя для компонента select, валидация не срабатывает.
