### ISSUE TITLE
[FEATURE] @prizm-ui/components - Отображение placeholder для textarea 

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#357]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Textarea](https://prizm.site/components/textarea)

### Версия

1.0.0

### Воспроизведение проблемы

Пример:

https://stackblitz.com/edit/ngx-14-title-demo-nn7h4l?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

### Описание проблемы

Если определить placeholder для textarea, он будет видет только, когда фокус устанвлен на сам textarea. Возможно ли отображать placeholder всегда, кроме случаев, когда значение введено?

**Comment by alexhawkins94** [comment]
Будет решено в https://github.com/zyfra/Prizm/issues/384
