### ISSUE TITLE
[Feature] @prizm-ui/components - NavigationMenu Добавить возможность скрывать кнопку "иерархичный" вид

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#358]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_NavigationMenu, NavigationMenuToolbar_

### Предложение

https://github.com/zyfra/Prizm/blob/e8608c17739d80c75c1b355a623c2c5927298f0d/libs/components/src/lib/components/navigation-menu/interfaces/prizm-navigation-menu-configuration.interfaces.ts#L22-L30

Сейчас есть возможность отобразить кнопки переключения дополнительных видов меню - рубрики и _папки_. 

_Предлагаю сделать ..._

Добавить возможность отключения отображения кнопки иерархичного представления.

![image](https://github.com/zyfra/Prizm/assets/2631748/36a963cc-b203-4627-94e3-a2883b756176)

Это может пригодиться в следующих случаях:
* это единственный требуемый режим и приложение не хочет оставлять кнопку на панели инструментов
* приложение не хочет использовать иерархичное представление (только вид _папки_ или _рубрика_)

**Comment by ZurabDev** [comment]
<img width="798" alt="CleanShot 2023-06-15 at 16 28 53@2x" src="https://github.com/zyfra/Prizm/assets/75216044/26c1a7dc-674c-4951-ab4c-fb7a55b4a925">
Готово. Добавлен пример
