### ISSUE TITLE
Добавить возможность работы с реактивными формами

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#36]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Select, InputText

### Предложение

Добавить возможность работы с formControlName

**Comment by ZurabDev** [comment]
Они работают с formControl, есть примеры значит работают и с formControlName, нужно описать что именно не получается

**Comment by AsyaSokolova** [comment]
> Они работают с formControl, есть примеры значит работают и с formControlName, нужно описать что именно не получается

Не срабатывает setValue при пред заполнение формы. На данные момент используется primeng dropdown, там setValue срабатывает. Ссылка с подробным описанием проблемы: 
https://gitlab.idp.yc.ziiot.ru/public-group/zui-sdk/-/issues/240

**Comment by ZurabDev** [comment]
Просьба скинуть mock файл всеми параметрами которые передаются в select компонент

**Comment by ZurabDev** [comment]
Невозможно воспроизвести, просьба проверить актуальна ли проблема и скинуть снимок данных которые передаются в компонент

**Comment by ZurabDev** [comment]
Просьба проверит в 27 версии и закрыть тикет
