### ISSUE TITLE
[BUG] @prizm-ui/components - InputSelect NG01350: ngModel cannot be used to register form controls with a parent formGroup directive.

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#360]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputSelect 

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.0.0
```

### Проект в котором используется Prizm

- СОУ

### Описание проблемы

Select кидает ошибку, если он находится в шаблоне, который динамически создаётся, например в диалоге.

```
Error: NG01350: ngModel cannot be used to register form controls with a parent formGroup directive.  Try using
    formGroup's partner directive "formControlName" instead.  Example:

    
  <div [formGroup]="myGroup">
    <input formControlName="firstName">
  </div>

  In your class:

  this.myGroup = new FormGroup({
      firstName: new FormControl()
  });

    Or, if you'd like to avoid registering this form control, indicate that it's standalone in ngModelOptions:

    Example:

    
  <div [formGroup]="myGroup">
      <input formControlName="firstName">
      <input [(ngModel)]="showMoreControls" [ngModelOptions]="{standalone: true}">
  </div>
    at modelParentException (forms.mjs:3784:12)
    at NgModel._checkParentType (forms.mjs:4124:23)
    at NgModel._checkForErrors (forms.mjs:4113:18)
    at NgModel.ngOnChanges (forms.mjs:4042:14)
    at NgModel.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1526:14)
    at callHook (core.mjs:2508:18)
    at callHooks (core.mjs:2467:17)
    at executeCheckHooks (core.mjs:2399:5)
    at refreshView (core.mjs:12020:21)
    at refreshComponent (core.mjs:13085:13)
ёёё

**Comment by AleksandrSibiakov** [comment]
А можно ли stackblitz с воспроизведением?
В нашем приложении все контролы создаются динамически и все формы реактивные (formGroup), но данной проблемы не наблюдается. 
Так же, судя по PR выше фикс касается контрола внутри селекта, но [как видно из исходников NgModel](https://github.com/angular/angular/blob/6f5dabe0d25a5660b7c3001041449b4622dd8924/packages/forms/src/directives/ng_model.ts#L207), парент берется только в скоупе `@Host`, т.е. не выходит за рамки самого `<input-select>`, а в нем не используется `[formGroup]`... 🤔

**Comment by bree7e** [comment]
> А можно ли stackblitz с воспроизведением? В нашем приложении все контролы создаются динамически и все формы реактивные (formGroup), но данной проблемы не наблюдается. Так же, судя по PR выше фикс касается контрола внутри селекта, но [как видно из исходников NgModel](https://github.com/angular/angular/blob/6f5dabe0d25a5660b7c3001041449b4622dd8924/packages/forms/src/directives/ng_model.ts#L207), парент берется только в скоупе `@Host`, т.е. не выходит за рамки самого `<input-select>`, а в нем не используется `[formGroup]`... 🤔

В связанном PR есть пример https://github.com/zyfra/Prizm/pull/361

**Comment by bree7e** [comment]
@ZurabDev почему issue закрыто? Изменений input-select нет в https://github.com/zyfra/Prizm/pull/351 и соответственно в 1.0.1 они не попали. Проверил в проекте, ошибка осталась.

**Comment by ZurabDev** [comment]
@bree7e Добрый день, с версии 1.2.3 проблема решена
