### ISSUE TITLE
[Feature] Человекочитаемый результат в Cron

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#365]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Cron

### Предложение

Возникла необходимость выводить результат крона в одном месте т.к. ходить по вкладкам крона и в голове собирать итоговый вариант - не удобно. Для этого в компоненте уже есть текстовое read-only поле со значением в cron формате. Но такое отображение чтобы его понимать требует технической подкованности, чего может не быть у пользователя приложения.

Отсюда вопрос - возможно ли на уровне компонента реализовать какое-нибудь "человекочитаемое" отображение выбранных параметров компонента?

**Comment by alexhawkins94** [comment]
Макет от дизайнеров нужен.

Идея - инпут с результатом перенести на строку вниз, растянуть на всю ширину крона.
Добавить переключалку в инпуте - показывать формулу или человеко читаемое значение.  
если hideresult = true то в этом инпуте отображать только человеко читаемое значение.
если текст слищком длинный, то полная его версия отображать в хинте при наведении на инпут

**Comment by ZurabDev** [comment]
<img width="799" alt="CleanShot 2023-06-16 at 04 40 48@2x" src="https://github.com/zyfra/Prizm/assets/75216044/1e992a5d-3b3a-47b6-88fc-0432766310bf">

<img width="968" alt="CleanShot 2023-06-16 at 04 42 44@2x" src="https://github.com/zyfra/Prizm/assets/75216044/a1d20ec5-3e32-491b-bad3-622c8811fdfe">

Готово
