### ISSUE TITLE
[Feature][Table] Добавить возможность программно управлять раскрытием таблицы с деревом

### ISSUE THREAD

**Issue by ickisIckis** [zyfra/Prizm#366]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Table

### Предложение
Сейчас управление видимостью дочерними элементами доступно через кнопку  prizm-tree-button, которая работает с внутренним состоянием таблицы.
Было бы очень полезно иметь возможность управлять состоянием дерева и отдельных его частей по принципу свернуто/развернуто программно снаружи.
Например, это пригодилось бы для случая с поиском по вложенным элементам, когда надо показать что-то в скрытых узлах или для ситуаций, когда пользователь хочет одним кликом развернуть всю таблицу.

![image](https://github.com/zyfra/Prizm/assets/18642277/1942023b-8925-4fb2-a7f5-767f3b0f1138)

**Comment by ZurabDev** [comment]
Добавим

**Comment by ZurabDev** [comment]
![CleanShot 2023-07-27 at 13 36 21](https://github.com/zyfra/Prizm/assets/75216044/e9e76caf-992c-4460-ae40-46bffadeda0e)
Готово
Обновлен пример
