### ISSUE TITLE
[BUG] prizm/components - Неверно рассчитывается высота IconButton в DropdownHost

### ISSUE THREAD

**Issue by zerodi** [zyfra/Prizm#37]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/theme`

### Компонент

PrizmDropdownHost, PrizmIconButton

### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/1549303/216631168-9fa9ec2a-0b75-4e3e-9a6b-799a260cfd34.png)
![image](https://user-images.githubusercontent.com/1549303/216631332-72b4a819-8c24-4b64-9905-91b0dbc7cffd.png)
![image](https://user-images.githubusercontent.com/1549303/216631470-40bdb9a7-0d9c-406a-abf3-397decedfc80.png)

### Описание проблемы

IconButton внутри DropdownHost неправильно рассчитывает высоту. При выводе кнопки вне DropdownHost высота кнопки 32px.

**Comment by ZurabDev** [comment]
Пробывали добавить кнопку в div блок?

**Comment by zerodi** [comment]
> Пробывали добавить кнопку в div блок?

Да. button отстраивается верно по высоте блока, prizm-wrapper уже рассчитывается неверно.

**Comment by ZurabDev** [comment]
Пока что можете тогда использовать для решения таких кейсов добавление родительского блока

**Comment by zerodi** [comment]
> > Пробывали добавить кнопку в div блок?
> > Да. button отстраивается верно по высоте блока, prizm-wrapper уже рассчитывается неверно.

"Да", но это не помогает. :) В этом смысле.

**Comment by ZurabDev** [comment]
Просьба проверить в 24 версии и закрыть issue

**Comment by zerodi** [comment]
Исправлено
