### ISSUE TITLE
[Feature] Overlay- темный и прозрачный фон

### ISSUE THREAD

**Issue by DenisBiktanov** [zyfra/Prizm#373]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_Название компонента или группы компонентов_

### Требуется затемнить фон

_Работаю в рамках задачи по ГПН_

![Screenshot_103](https://github.com/zyfra/Prizm/assets/122870017/c5d9a2eb-a593-4ff8-b96c-8db3ab95f199)

**Comment by ZurabDev** [comment]
50% прозрачность будет по дефолту, пользователь сможет менять дальше как решит

**Comment by ZurabDev** [comment]
Перенести возможности перетаскивания (убрал из названия) в отдельный issue
