### ISSUE TITLE
[FEATURE] @prizm-ui/components Изменение размера после изменения размера окна браузера (Sidebar)

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#374]
### Скрин / Видео проблемы

![chrome_0VDUH4ZooZ](https://github.com/zyfra/Prizm/assets/122870313/73af3533-b170-4f44-ae07-50d833c9620b)

### Описание проблемы
-Браузер открыт на полный размер экрана
-Вызвать сайдбар (сайдбар отображается на всю высоту страницы)
-Уменьшить окно браузера по двум измерениям - по горизонту и вертикали
-Развернуть окно браузера на весь экран
Фактический результат: сайдбар не восстановил исходный размер

**Comment by ZurabDev** [comment]
![CleanShot 2023-06-23 at 08 54 33](https://github.com/zyfra/Prizm/assets/75216044/4927755a-c2ed-4b72-b8de-cb612e8238aa)
Готово
