### ISSUE TITLE
Добавить стили для Table

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#38]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Table

### Предложение

Добавить возможность для разработчика скрыть/показать курсор pointer при наведении на сроку в таблице, также добавить стиль для таблицы без "зебры" пример:
![image](https://user-images.githubusercontent.com/17219726/216931206-44aba38e-e5b5-4e96-8a52-5fcb8f78a22e.png)

**Comment by AsyaSokolova** [comment]
> Кажется такое поведение должны согласовать дизайнеры

Согласуйте пожалуйста.

**Comment by ifmalex** [comment]
Передать в Дискавери Дмитрию О.
Без зебры – ок. Оне всем нужна.

**Comment by ZurabDev** [comment]
@AsyaSokolova 

<img width="693" alt="CleanShot 2023-03-13 at 12 33 33@2x" src="https://user-images.githubusercontent.com/75216044/224662496-52a7a611-af7d-4c6f-ba8d-7c92caeacc71.png">

В 25 версии появилось возможность через переменные стилей переопределить

https://ziiot-dev-11.kube01.yc.ziiot.ru/components/table/Live_demo?tuiMode=null

Просьба проверить и закрыть тикет если все ок

**Comment by ZurabDev** [comment]
Закрываем этот тикет
