### ISSUE TITLE
[BUG] @prizm-ui/components - Наименование дней на английском во вкладке "Дни" комопонета Cron 

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#383]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

[Cron](https://prizm.site/components/cron)

### Версия

@prizm-ui/components: 1.0.1

### Воспроизведение проблемы

Пример:

https://stackblitz.com/edit/ngx-14-title-demo-enp5ng?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ngx-14-title-demo-aqrqrg?file=package.json,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.less,src%2Fapp%2Fapp.component.html)

### Описание проблемы

При использовании комопннета Cron в приложении, все вкладки на русском языке, кроме вкладки "Дни". На вкладке "Дни" наименовании дней недели на английском языке.

**Comment by ZurabDev** [comment]
для вывода дней недели используются ангяровский пайп для работы с датов, попробуйте установить 
`@NgModule({
  providers: [
    { provide: LOCALE_ID, useValue: "ru-RU" },
    //otherProviders...
  ]
})`
