### ISSUE TITLE
[Feature] - Валидация выбранных значений в компоненте Cron

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#385]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Cron](https://prizm.site/components/cron)

### Предложение

Сейчас при работе с компонентом Cron возможно выбрать следующие значения:

- **Минуты**

_Каждая минута с [i-й] до [n-й], причем n<i._

- **Часы**

_Каждый час с [i-го] до [n-го], причем n<i._

- **Дни**

_Каждый день с [i-го] по [n-ый], причем n<i._

- **Месяцы**

_Каждый месяц с <наименование месяца> до <наименование месяца>, причем n<i._

- **Год**

_Каждый год с i-го до n-го, причем  n<i._

Также при работе в области периода ("Начало работы", "Конец работы") можно указать начало поздее даты конца.

Возможно ли, на уровне компонента поддрежать валидацию значений? Например, поля со значениями из описанных кейсов подсвечивать красной рамкой, а снаружи компонента иметь вохможность отслеживать валидность занчений, выбранных в компоненте.

**Comment by imonogarov** [comment]
в 4.6.0 нужно написать rfc по этому компоненту

**Comment by ickisIckis** [comment]
@badeevdm, сейчас невозможно ввести некорреткное знаечние, тк в инпуты дат прокидыввается минимальное и максимальное допустимое значение, так же дотспуна такая работа и с нативным датами. 
работает с весрии 1.0.1, решено с  #364
кажется, задача уже не актуальна.
