### ISSUE TITLE
[Feature] MultiSelect резиновые чипсы

### ISSUE THREAD

**Issue by AntonGrekov** [zyfra/Prizm#386]
### Библиотека

- [x] `@prizm-ui/components`

### Компонент

PrizmInputMultiSelectComponent

### Предложение

_Работаю в рамках задачи_

https://jira.zyfra.com/browse/PLATFORM01-26859

_Предлагаю сделать ..._

Чтобы пустое место заполнялось выбранными чипсами резиново - когда есть свободное место туда добавляются чипсы, когда нет - отображаются ...

Сейчас это частично работает, свободное пространство заполняется чипсами в строку если компонент при создании имеет много свободного пространства, но если размер компонента меняется в моменте(при ресайзе), то ничего не меняется. А так же не заполняется свободное пространство вертикально. Такие нестандартные размеры компонента согласованы с дизайнером на проекте.

![изображение](https://github.com/zyfra/Prizm/assets/44285258/c0d97011-9ff9-4877-896d-fbe14bb0c38f)

**Comment by ZurabDev** [comment]
А так же не заполняется свободное пространство вертикально. 
 >> Что имеется ввиду под заполнение пространство вертикально? @AntonGrekov

**Comment by AntonGrekov** [comment]
Конечно хорошо бы ФТ какое-то иметь или иное описание. Не могу никуда опираться. Но мне так понимается, что заполняется просто всё пустое пространство чипсами как в обычном flex-контейнере слева направо и с переносом на новую строку

![image](https://github.com/zyfra/Prizm/assets/44285258/6ab32d1f-6c1b-4f52-b24c-40c8f03bfd4b)

@ZurabDev

**Comment by PrizmDS** [comment]
В дизайне появился такой функционал, Макеты отрисованы, затронуты стили чипсов, и инпута.

**Comment by PrizmDS** [comment]
[Ссылка на макет](https://www.figma.com/file/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8E-Prizm.-%D0%A1omponent-base-4.0?type=design&node-id=23878%3A35158&mode=design&t=kaz3Upkj3a5VevU5-1)
![image](https://github.com/zyfra/Prizm/assets/131430040/702dc0a7-d340-46f7-ae43-364317b34bb6)

**Comment by ZurabDev** [comment]
![CleanShot 2023-10-13 at 17 09 22@2x](https://github.com/zyfra/Prizm/assets/75216044/5530945c-00f4-4f35-8eb4-d6d24ee48818)
![CleanShot 2023-10-13 at 17 09 41@2x](https://github.com/zyfra/Prizm/assets/75216044/ce6a183c-7983-4e65-b36f-ae011f62c2c4)
https://prizm.site/components/input-multi-select/Live_demo?tuiMode=null

Используйте multi-select
