### ISSUE TITLE
[BUG] MultiSelectComponent - изначальное позиционирование списка не происходит

### ISSUE THREAD

**Issue by AntonGrekov** [zyfra/Prizm#387]
### Библиотека

- [х] `@prizm-ui/components`

### Компонент

MultiSelectComponent

### Проект в котором используется Prizm

IDP
https://jira.zyfra.com/browse/PLATFORM01-27044

### Скрин / Видео проблемы
![изображение](https://github.com/zyfra/Prizm/assets/44285258/d8d2f4f6-60aa-4ba1-b522-73ba45c84879)

### Описание проблемы

Если компонент мультиселетка находится в нижней части экрана, то при открытии не происходит корректное позиционирование выпадающего списка. Только если произвести изменение ширины окна браузера происходит подстройка и список отображается сверху

**Comment by AntonGrekov** [comment]
Затерялся этот баг видимо ((( Можно включить его в какой-нибудь майлстоун будущий ? @ZurabDev

**Comment by ZurabDev** [comment]
Затерялся. Ща поднимем срочность

**Comment by AntonGrekov** [comment]
Благодарствую, @ZurabDev
