### ISSUE TITLE
[BUG] @prizm-ui/components - Поправить цвета ховеров и выделенных айтемов в дропдаунах дейтпикеров

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#388]
### Скрин / Видео проблемы
 
Сейчас так - выделенный айтем и ховер - оба серого цвета. В dateRelative - ховер и выбранный айтем - оба синие.

![image](https://github.com/zyfra/Prizm/assets/122870313/cf1a8b9c-7190-4abe-9808-da081fc46dc9)
![image](https://github.com/zyfra/Prizm/assets/122870313/2ba0a8ac-7335-415c-a32e-96af6dedf4c8)

Надо сделать как в фигме - активный элемент синим должен быть, ховер серый
![image](https://github.com/zyfra/Prizm/assets/122870313/1dece02f-feff-4202-9df2-478b3793a352)
![image](https://github.com/zyfra/Prizm/assets/122870313/3fca3fb7-4e10-4ae1-82c1-6407b1769bdd)

**Comment by alexhawkins94** [comment]
синий #D6E5FF;  серый#F4F6FB;

**Comment by ZurabDev** [comment]
<img width="483" alt="CleanShot 2023-06-15 at 15 51 22@2x" src="https://github.com/zyfra/Prizm/assets/75216044/6989e601-d29e-46c9-abee-1082f880a5e7">

**Comment by ZurabDev** [comment]
<img width="360" alt="CleanShot 2023-06-15 at 15 58 31@2x" src="https://github.com/zyfra/Prizm/assets/75216044/fe4a7011-6f71-47af-a1f3-6b23ac9952a8">
