### ISSUE TITLE
Как в зависимости от условия передавать данные для таблицы с разными интерфейсами? 

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#39]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

table

### Проект в котором используется Prizm

- Конфигуратор
- https://gitlab.idp.yc.ziiot.ru/digital-plant/stream/zui-app-om-configurator/-/tree/dev-v2
- https://stream-dev-01.kube02.yc.ziiot.ru/zui-app-om-configurator/library

### Вопрос

Как передать данные с разными интерфейсами в таблицу, которые меняются в зависимости от условия? 
HTML-шаблон:
![image](https://user-images.githubusercontent.com/17219726/217149279-984c1568-f1f2-4fdd-a220-4e3ea1b66da4.png)
pipe:
![image](https://user-images.githubusercontent.com/17219726/217149712-9777e917-f71e-4a54-826c-046de590ce43.png)
Ошибка:
![image](https://user-images.githubusercontent.com/17219726/217149852-dc6d4dd7-dae9-4e08-9a8b-5f158a3d98c8.png)

На данный момент таблица отображается с помощью primeng, ошибок с такими значениями нет.
Пример можно посмотреть на тестовом стенде в разделе "Конструктор", выбрать схему "0 оп"
![image](https://user-images.githubusercontent.com/17219726/217150388-5dbd14ab-4500-4b85-9225-7e26be7003f2.png)

нажать клавишу ctrl и кликнуть по объекту "тестовый процесс для добавления парента"
![image](https://user-images.githubusercontent.com/17219726/217150343-6ccc09a8-bbff-48eb-9a2d-2f7f22734529.png)

Перейти в раздел "Спецификация"
![image](https://user-images.githubusercontent.com/17219726/217150472-18214515-d674-4990-ac71-a90e295f41b5.png)

**Comment by ZurabDev** [comment]
проверьте с $any() в шаблоне
