### ISSUE TITLE
[FEATURE] @prizm-ui/components - нет события переключения между абсолютным и относительным режимами prizm-input-date-multi

### ISSUE THREAD

**Issue by petrik1991** [zyfra/Prizm#393]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_PrizmInputDateMultiComponent_

### 1.0.0-beta.35

Операционная сиcтема:

`MacOs 13.0.1 (22A400)`

Браузер:

`Google Chrome Версия 112.0.5615.137 (Официальная сборка), (arm64)`

NodeJS:

```
➜ node --version
v14.16.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components@1.0.0-beta.35 
```

```
➜ npm ls @angular/core

@angular/core@12.2.17 


```

### Проект в котором используется Prizm

- _zui-app-datalinkeditor_

### Воспроизведение проблемы

Пример:

https://prizm.site/components/input-date-multi

### Описание проблемы

_Есть проблема следующего характера:_

1. Отсутствует событие переключения пользователем типа даты

**Comment by ZurabDev** [comment]
<img width="889" alt="CleanShot 2023-06-15 at 10 50 01@2x" src="https://github.com/zyfra/Prizm/assets/75216044/86d8672c-32c9-4c52-984c-29eb72e44361">
Добавлен event currentIdxChange
