### ISSUE TITLE
[BUG] @prizm-ui/components - prizm-dropdown-host неправильно позиционируется

### ISSUE THREAD

**Issue by RoxVell** [zyfra/Prizm#394]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

prizm-dropdown-host

### Проект в котором используется Prizm

AppShell

### Скрин / Видео проблемы

<img width="609" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/e384e913-82e4-4c86-8f50-fcd953332a04">

### Воспроизведение проблемы

https://stackblitz.com/edit/ngx-14-title-demo-cokfqw?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,package.json

### Описание проблемы

Делаю задачу по переходу апшела на призм, при нажатии на кнопку, прижатую к правой части экрана происходит неправильное раскрытие выпадающего окна, он должен располагаться снизу справа (placement="br"), но в результате расчетов раскрывается слева, хотя размеры позволяют раскрыться в правильном положении.

Шаги воспроизведения:

1. Зайти по адресу [stackblitz](https://stackblitz.com/edit/ngx-14-title-demo-cokfqw?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,package.json)
2. Нажать на кнопку "Button"

При этом, если сделать так, чтобы выпадающее окно не могло раскрыться слева из-за слишком большой высоты контейнера (этого можно добиться закоментировав 2 параграфа сверху), то всё позиционируется правильно. Скриншот:
<img width="1121" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/a7614415-a7cf-4550-8da4-bb5da56f638a">

P.S. если выпадашка не открывается нужно обновить страницу внутри stackblitz
<img width="243" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/8fc12e1c-b154-42d3-bf6c-dd392ecc5c3c">

**Comment by if1t** [comment]
@ZurabDev на версии 1.4.2 также воспроизводится эта проблема.
