### ISSUE TITLE
[Feature] PrizmPaginatorComponent First/Last Page

### ISSUE THREAD

**Issue by AntonGrekov** [zyfra/Prizm#399]
### Библиотека

- [x] `@prizm-ui/components`

### Компонент
PrizmPaginatorComponent

### Предложение
![изображение](https://github.com/zyfra/Prizm/assets/44285258/2bd05f49-f84c-4d98-9023-badf5ec5ad19)
![изображение](https://github.com/zyfra/Prizm/assets/44285258/920b80bc-103f-4944-b23e-5bd2f0593c1d)

_Работаю в рамках задачи_
IDP, PLATFORM01-27067

_Предлагаю сделать ..._
Добавить возможность моментально переходить на первую/последнюю страницу пагинации по кнопке, как было в предыдущей версии кб

**Comment by PrizmDS** [comment]
@AntonGrekov 
Упустили этот функционал, добавим

**Comment by ZurabDev** [comment]
<img width="795" alt="CleanShot 2023-06-16 at 03 38 00@2x" src="https://github.com/zyfra/Prizm/assets/75216044/dd72a79a-2457-4b22-86e2-674f7814f89d">
Готово. Добавили пример
