### ISSUE TITLE
Добавить выпадающий список для Split Button

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#40]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Split Button

### Предложение

На данные момент в Split Button можно добавлять template, который не совсем подходит для реализации выпадающего списка и соответствующей обработки событий. Поэтому прошу добавить выпадающий список в Split Button. Пример можно посмотреть здесь: https://primeng.org/splitbutton

**Comment by ZurabDev** [comment]
Добавили в доку ранее
Вот ссылка http://doc.prizm.zyfra.com/components/split-button#with-dropdwon

**Comment by AsyaSokolova** [comment]
> Добавили в доку ранее Вот ссылка http://doc.prizm.zyfra.com/components/split-button#with-dropdwon

У меня задача реализовать вот такой выпадающий список:
![image](https://user-images.githubusercontent.com/17219726/217488812-b4f74bf8-3197-411c-b437-762351f5246f.png)
Как это сделать с помощью компонента Split Button?

**Comment by ZurabDev** [comment]
У нас такого компонента нет, пока придется вам в template передавать вашу реализацию в шаблон
