### ISSUE TITLE
[BUG] @prizm-ui/components - Стилизация компонента Tabs

### ISSUE THREAD

**Issue by RoxVell** [zyfra/Prizm#401]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

Tabs

### Проект в котором используется Prizm

zui-app-marketplace

### Скрин / Видео проблемы

<img width="754" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/c66bb217-180b-4e3b-8329-80103c7e3f6a">

https://doc.prizm.zyfra.com/components/tabs

### Описание проблемы

Есть 2 недочета:
1. Цвет текста выделенного таба не должен быть синим
2. Счетчик на неактивных вкладках - должен быть синим
3. Форма фона количества тегов должна быть круглой при одном символе
Комментарий от дизайнера:
<img width="591" alt="image" src="https://github.com/zyfra/Prizm/assets/17107421/dd4ef0a9-3d11-44e8-b49a-40216ce8f4eb">

**Comment by PrizmDS** [comment]
@RoxVell @ZurabDev 

1. Это поправится после обновления цветовых стилей, в дизайне сейчас обновленная версия, в коде еще не реализовали
2. Счетчик может быть любым из доступных статусных цветов. Если нет необходимости акцентировать на счетчике внимания, можно оставить серым
3. @ZurabDev в дизайне счетчик с одним символом действительно круглый
