### ISSUE TITLE
[Feature] Query builder

### ISSUE THREAD

**Issue by bumalai** [zyfra/Prizm#402]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
- [x] `@prizm-ui/addon-querybuilder` ? 

### Компонент

QueryBuilder

### Предложение

Необходимо предоставить компонент который будет добавлять функционал QueryBuilder на базе Prizm
![image](https://github.com/zyfra/Prizm/assets/131881448/5a4bc741-03d5-4c3d-a1c6-8951f602869e)

Разработка компонента _PrizmQueryBuilder_ в соответствии с [дизайн документом](https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-4.0?node-id=22432-251786)

**Comment by PrizmDS** [comment]
@bumalai @alexhawkins94
Взяли в анализ

**Comment by PrizmDS** [comment]
Макеты:
https://www.figma.com/design/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8EPrizm.-%D0%A1omponent-base-5.0?m=auto&node-id=39763-205650&t=CuZzXORYagALh0tD-1
