### ISSUE TITLE
[BUG] @prizm-ui/components - Ошибка при сборке проекта с @prizm-ui/components

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#406]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Версия

"@prizm-ui/components": "1.2.0-rc.1",
 "rxjs": "6.6.7",

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/48792714/262caa10-a477-440a-ae11-b8b6cbe2f649)

### Описание проблемы

После установки версии 1.2.0-rc.1, приложение перестало собираться, ошибка в консоли (см. скриншот).

**Comment by ZurabDev** [comment]
Привет, странно, стараемся воспроизвести, отпишемся

**Comment by ZurabDev** [comment]
Проверьте версии 1.2.1

**Comment by badeevdm** [comment]
@ZurabDev, привет, поставил 1.2.1. Ошибка воспроизводится, пробоал удалять и ставить заново node_modules, к сожалению, не помагает.

**Comment by ZurabDev** [comment]
@badeevdm ставили в стороннем проекте 
<img width="639" alt="CleanShot 2023-06-23 at 09 22 08@2x" src="https://github.com/zyfra/Prizm/assets/75216044/659a2b68-1b93-489b-a63b-5863c4dde873">

пробывали build, serve 

<img width="973" alt="CleanShot 2023-06-23 at 09 22 30@2x" src="https://github.com/zyfra/Prizm/assets/75216044/af823091-30bb-4095-888d-66351a9a2288">


никак не можем воспроизвести

**Comment by ZurabDev** [comment]
@badeevdm какая версия rxjs стоит?

**Comment by badeevdm** [comment]
6.6.7
