### ISSUE TITLE
[BUG] InputDateMulti - Не вызывается событие изменения значений

### ISSUE THREAD

**Issue by petrik1991** [zyfra/Prizm#407]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_InputDateMulti_

### Версия

Операционная система:

`MacOS Ventura 13.4 (22F66)`

Браузер:

`Google Chrome Версия 114.0.5735.106 (Официальная сборка), (arm64)`

NodeJS:

```
➜ node --version
v14.16.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components@1.0.0-beta.35 
```

```
➜ npm ls @angular/core

@angular/core@12.2.17 

```

### Проект в котором используется Prizm

- _DatalinkEditor_

### Описание проблемы

_При изменении абсолютной даты с клавиатуры не вызывается событие изменения значений контрола_

**Comment by ZurabDev** [comment]
Используйте версию 1.2.1
