### ISSUE TITLE
[Feature][Table] @prizm-ui/components - добавить стили для inline редактирование таблицы

### ISSUE THREAD

**Issue by dmitriy-sokolov** [zyfra/Prizm#408]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Table](https://prizm.site/components/table)

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

### Проект в котором используется Prizm

- Редактор даталинк

### Скрин / Видео проблемы

![изображение](https://github.com/zyfra/Prizm/assets/25181659/de5c3b56-10fe-416e-8a60-e27980948fbb)

![image](https://github.com/zyfra/Prizm/assets/25181659/52798e3f-77a5-47fb-8cf5-701562e9a225)

### Описание проблемы

Для [задачи](https://jira.zyfra.com/browse/PLATFORM01-24097) дизайнеры спроектировали [макеты](https://www.figma.com/file/7uicz9j3xYYTgTLacb4J5n/Zif-Datalink.-%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%BE%D0%B2-%D0%BE%D1%82%D1%87%D0%B5%D1%82%D0%BE%D0%B2?type=design&node-id=3807-223408&t=4mLHIjeXshz8bM7N-0) 
![изображение](https://github.com/zyfra/Prizm/assets/25181659/ab723b9e-5c2e-4a23-b28a-b76550c08bec)
в соответствии с [описанными возможностями компонента prizm](https://www.figma.com/file/IEsKtY2w1cx6mvpy3hqB9O/%F0%9F%92%8E-Prizm.-Descriptions-v-1.0?type=design&node-id=1408-193429&t=iVLFVjuxaxHYSCPj-0). 

Реализованны ли данные возможности (в песочнице нет примеров)?

Хорошо бы добавить примеры для редактирования таблицы в режиме inline для компонентов  [InputDate](https://prizm.site/components/input-date), [InputDateMulty](https://prizm.site/components/input-date-multi), [InputDateTimeRange](https://prizm.site/components/input-date-time-range), [Select](https://prizm.site/components/dropdowns/select), а не только для обычного [Input](https://prizm.site/components/input). 
Вход в редактирование по двойному клику и выход, при потере фокуса строки.

**Comment by ickisIckis** [comment]
Связано с #276

**Comment by PrizmDS** [comment]
https://www.figma.com/file/2KJZq6hHEdxQmFMRVTJWKT/%F0%9F%92%8E-Prizm.-%D0%A1omponent-base-4.0?type=design&node-id=21447%3A292388&mode=design&t=rDfnSdSRYCZwEm5P-1
