### ISSUE TITLE
[Feature] Задать диапазон с неустановленной одной или обеих границ диапазона Calendar Range

### ISSUE THREAD

**Issue by PrizmDS** [zyfra/Prizm#409]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

Calendar Range

### Предложение

Zif-datalink

**Критично!**

В текущей реализации компонента CalenarRange отсутствует возможность задать диапазон с неустановленной одной или обеих границ диапазона. Это требуется, например, для задания периодов длящихся неограниченно.

Предлагаю реализовать с помощью дефолтного значения календаря "∞", которое будет означать неопределенность границы. Пользователь, выбирая дату в календаре или вводя значение даты вручную, заменяет его. Сброс к дефолтному значению, происходит по клику на очистке ввода внутри инпута даты.

Альтернативное решение — использовать тогглер "не определено" для каждой границы, который будет блокировать как сам календарь на соответствующей границе, так и инпут с датой

**Comment by ifmalex** [comment]
Это для Визуализации/Приложения

**Comment by imonogarov** [comment]
Пример реализации можно посмотреть тут: https://prizm.site/components/dropdowns/dropdown-host#nested

**Comment by imonogarov** [comment]
Close
