### ISSUE TITLE
При локальной смене темы, изменяются другие компоненты присутствующие в шаблоне

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#41]
### Библиотека

- [ ] `@prizm-ui/theme`

### Компонент

theme

### Проект в котором используется КБ

- Конфигуратор
- https://gitlab.idp.yc.ziiot.ru/digital-plant/stream/zui-app-om-configurator

### Скрин / Видео проблемы

https://user-images.githubusercontent.com/17219726/217194275-00d33dbe-399a-4d78-8d9a-56c316970bb6.mp4

### Описание проблемы

HTML-шаблон:
![image](https://user-images.githubusercontent.com/17219726/217195111-a8c3774e-e49c-4536-a821-7a5871c6c66d.png)
![image](https://user-images.githubusercontent.com/17219726/217195184-3d98cb48-04a7-455a-b205-1d04ccd81580.png)

Компонент:
![image](https://user-images.githubusercontent.com/17219726/217195356-6505a57b-2a05-43d8-84db-fefb1419dd70.png)
Импорты:
![image](https://user-images.githubusercontent.com/17219726/217195441-aed0e65a-4fa2-457b-8455-a59849a18407.png)

**Comment by ZurabDev** [comment]
Проверьте в 1.0.0-beta.23

**Comment by AsyaSokolova** [comment]
> Проверьте в 1.0.0-beta.23

Проверила, не помогло

**Comment by ZurabDev** [comment]
Установить глобально нужно значение темы
И только потом меняйте локальные данные

**Comment by AsyaSokolova** [comment]
> 

У меня глобально установлена темная тема

**Comment by ZurabDev** [comment]
Проверьте в 23 версии пожалуйста

**Comment by ZurabDev** [comment]
Просьба проверить и закрыть issue
