### ISSUE TITLE
[FEATURE] @prizm-ui/overlay Детекция события из динамических элементов (исчезают из дом)

### ISSUE THREAD

**Issue by skkonstantin** [zyfra/Prizm#411]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Overlay

### Воспроизведение проблемы

https://stackblitz.com/edit/ngx-14-title-demo-kwfpjv

### Описание проблемы

В overlay  вложен компонент tree с иерархией , при попытке свернуть группу внутри tree overlay закрывается

**Comment by ZurabDev** [comment]
![CleanShot 2023-07-25 at 14 17 54](https://github.com/zyfra/Prizm/assets/75216044/587e5086-432c-45ce-a266-08e08dc85aa8)
Готово
