### ISSUE TITLE
File upload в "вечном" ожидании загрузки 

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#42]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/components`

### Компонент

File upload

### Проект в котором используется КБ

- Конфигуратор
- https://gitlab.idp.yc.ziiot.ru/digital-plant/stream/zui-app-om-configurator

### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/17219726/217441173-d844e008-197b-49c0-b0eb-957d5be9db75.png)

![image](https://user-images.githubusercontent.com/17219726/217441242-04ccc163-ff04-4adc-95ba-cd90076d3829.png)

### Описание проблемы

При попытке имплементировать компонент File upload, статус файла всегда в "ожидании загрузки", в документации ошибка повторяется.

**Comment by alexhawkins94** [comment]
@AsyaSokolova  
В документации в Base примере для выполнения загрузки файла нужно нажать кнопку "Отправить". До этого момента висит статус "ожидание загрузки". 

Если нужно загружать сразу файл после выбора, то посмотрите второй пример в доке - Auto upload
