### ISSUE TITLE
[BUG] @prizm-ui/components - Zoom.Control. Перестали работать некоторые контролы в примере

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#421]
Zoom control
-перстали работать масштаб 100, 150
-Контролы уменьшить/увеличить, переключение на 50 и 200 масштаб и остальные контролы в примере работают с сильной задержкой

**Comment by ZurabDev** [comment]
![CleanShot 2023-06-23 at 08 11 11](https://github.com/zyfra/Prizm/assets/75216044/3f3384f1-3ece-4e85-8cc8-f2dcee80b5ab)
Готово
