### ISSUE TITLE
[BUG] @prizm-ui/components - Toast. В примере "шаблон в хедере" не умещается контент в тосте

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#422]
Toast
При вызове примера "шаблон в хедере" - ссылка в шаблоне не умещается и обрезается

![image](https://github.com/zyfra/Prizm/assets/122870313/768fedf0-cac4-49c9-b12f-fa8c22c566a3)

**Comment by ZurabDev** [comment]
<img width="541" alt="CleanShot 2023-06-22 at 18 11 51@2x" src="https://github.com/zyfra/Prizm/assets/75216044/1f704369-3a03-4c8c-8ed6-51bedbf9e65b">
 Готово
