### ISSUE TITLE
[BUG] @prizm-ui/components - Toasts. Двойная нижняя граница в примерах

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#423]
У toasts появилась двойная нижняя граница во всех примерах
![image](https://github.com/zyfra/Prizm/assets/122870313/3bda4543-d19d-4e4e-9dd3-cd45346ee667)

**Comment by ZurabDev** [comment]
<img width="399" alt="CleanShot 2023-06-22 at 18 01 18@2x" src="https://github.com/zyfra/Prizm/assets/75216044/00ce6aae-25a8-406f-9569-017be0296bb7">
Не можем воспроизвести
