### ISSUE TITLE
[BUG] @prizm-ui/components - Table. Не работает соритровка

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#424]
Table
Не отрабатывает сортировка по нажатию на кнопку сортировки столбца
![chrome_gXQ7knicBs](https://github.com/zyfra/Prizm/assets/122870313/161c5e72-bc94-47b2-be9b-e4792dabb111)

**Comment by ZurabDev** [comment]
![Uploading CleanShot 2023-06-23 at 06.30.20.gif…]()
Готово
