### ISSUE TITLE
[BUG] @prizm-ui/components -Table. Поиск работает некорректно

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#425]
Table. 
Поиск стал работать некорректно.

Шаги:
-перейти к примеру с поиском
-ввести в поиск "Пропант" - этот айтем заведомо существует в таблице
Фактический результат: пропант отсутсвтует в результатах поиска, отображается "углекислый газ"
Ожидаемый результат: в результатах поиска должны быть данные, удовлетворяющие поисковому запросу
![image](https://github.com/zyfra/Prizm/assets/122870313/db8e3ac7-a071-4a9a-a600-248185f66868)

![image](https://github.com/zyfra/Prizm/assets/122870313/5bfc0c04-7e8c-4901-b441-647e4a52813a)

**Comment by ZurabDev** [comment]
<img width="641" alt="CleanShot 2023-06-22 at 17 34 45@2x" src="https://github.com/zyfra/Prizm/assets/75216044/a12a9c4b-56ec-4813-bd81-65923c786452">

**Comment by ZurabDev** [comment]
не можем воспроизвести
