### ISSUE TITLE
Добавить json формат для File upload

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#43]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

File upload

### Предложение

Добавить возможность присваивать [accept] json-формат. На данный момент доступны только такие форматы:
![image](https://user-images.githubusercontent.com/17219726/217442856-a5c7fcca-e0f0-4c78-9494-c0e93c2a4b3d.png)

**Comment by skkonstantin** [comment]
Это просто для примера сделано, если указать все варианты будет огромный список. можно в accept указать .json или application/json

**Comment by AsyaSokolova** [comment]
> Это просто для примера сделано, если указать все варианты будет огромный список. можно в accept указать .json или application/json

Хорошо, спасибо, думала в документации описаны доступные форматы
