### ISSUE TITLE
[BUG] @prizm-ui/components - PrizmInputLayoutDateTime NG01350: ngModel cannot be used to register form controls with a parent formGroup directive.

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#445]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmInputLayoutDateTime 

### Версия

Операционная система:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.2.1
```

### Проект в котором используется Prizm

СОУ

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/26089012/5845741a-9cb3-480c-a884-038f860b0b32)

![image](https://github.com/zyfra/Prizm/assets/26089012/a3c4a6c3-a272-4f99-8702-f89148d72400)

### Воспроизведение проблемы

https://stackblitz.com/edit/ngx-14-title-demo-7tgvlh

### Описание проблемы

PrizmInputLayoutDateTime кидает ошибку, если он находится в шаблоне, который динамически создаётся в диалогах. Из-за этого визуально не отображается выбранное значение.

**Comment by ZurabDev** [comment]
Готово. Можно проверить версиях 1.2.3-next.1
