### ISSUE TITLE
[BUG] @prizm-ui/components - В инпутах используется Arial (sans-serif) вместо Inter

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#460]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

Все Input*

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

Смотрел на 2.0.0 и на 1.2.4

### Проект в котором используется Prizm

- СОУ

### Скрин / Видео проблемы

На компонентах Input чего-нибудь дата (где есть ограничения по ширине вида `width: calc(var(--prizm-input-in-zone-max-size, 2) * 0.5em + 2px); `) на шрифте Inter будет переполнение в троеточние. Не все даты обрезаются, на условную `11.11.1111 11:11` не распространяется, т.к. единица - узкий глиф.

![image](https://github.com/zyfra/Prizm/assets/26089012/a30df58d-929f-4234-a778-741e2e0efc0a)

### Описание проблемы

_Шаги воспроизведения_:

1. Зайти по адресу https://prizm.site/components/input-layout-date-time
2. Выбрать дату 26.06.2022 время 23:00
3. Все будет отображаться корректно, т.к. по-умолчанию на Windows в input рендериться Arial
4. Добавить стиль

```css
* {
    font-family: 'Inter';
}
```

**Comment by alexhawkins94** [comment]
известная проблема 
https://github.com/zyfra/Prizm/issues/280

**Comment by bree7e** [comment]
Меня скорей волнует момент c тем, что даты не видно

**Comment by bree7e** [comment]
И в качестве решения сделан костылик, который явно прописывает Arial для инпутов, чтобы дату/время гарантировано было видно без раскрытия календаря/выбора времени.
