### ISSUE TITLE
[FEATURE][Breadcrumbs] @prizm-ui/components - Возможность контроля перехода по крошкам

### ISSUE THREAD

**Issue by dmitriy-sokolov** [zyfra/Prizm#464]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Breadcrumbs

### Проект в котором используется Prizm

- Редактор даталинк

### Воспроизведение проблемы

[Пример в песочнице](https://prizm.site/components/breadcrumbs/Live_demo?tuiMode=null):

### Описание проблемы

[Автоматически сгенерированные отчеты](https://jira.zyfra.com/browse/PLATFORM01-20090). При решении задачи, хлебные крошки используются как контекст экрана, на котором находится пользователь. 
![изображение](https://github.com/zyfra/Prizm/assets/25181659/f05eb648-9a99-4e9e-9374-ab47d1777cf1)

Проблемы:
1. Хлебные крошки не участвуют в навигации. Не должен происходить переход или изменение хлебных крошек по клику. 
2. Если даже делать навигацию, то с текущей реализацией нельзя предусмотреть валидацию формы и отменить действия по навигации. 

В качестве решения предлагаю обработчик `breadcrumbChange` заменить на что-то вроде `selectPath`, чтобы можно было подписаться на выбор пользователя, но дальнейшие решения по изменению модели [breadcrumbs] должен принимать разработчик, который использует компонент.

**Comment by ZurabDev** [comment]
Готово. Добавлено возможность работы с проекцией.
![CleanShot 2023-07-25 at 15 36 20](https://github.com/zyfra/Prizm/assets/75216044/94fe64e2-35eb-4b9b-90f2-4fa262f69137)
