### ISSUE TITLE
[Feature] Возможность редактирования [testid]

### ISSUE THREAD

**Issue by TheSpaceHuman** [zyfra/Prizm#465]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

ALL

### Проект в котором используется Prizm

- App-shell

### Описание проблемы

Делаю задачу [#27888](https://jira.zyfra.com/browse/PLATFORM01-27888) часть для app-shell

Есть проблема следующего характера:

Для ароматизаторов необходимо больше уникальность по [data-testid]. Например, кнопку сохранения необходимо идентифицировать не, как `ui_icon_button`, а `ui_icon_button--save`  т.к. кнопом несколько, а нужна конкретная. То же самое касается inputs необходимо конкретизации самих названий полей.

### Предложение

В данный момент testid readonly, необходимо дать возможность или переопределять или добавлять postfix (postfix=save, testid=ui_icon_button--save).

**Comment by ZurabDev** [comment]
Теперь можно редактировать 
<img width="782" alt="CleanShot 2023-07-18 at 15 17 33@2x" src="https://github.com/zyfra/Prizm/assets/75216044/e1044953-80be-4231-a31f-14e10ed0380c">
