### ISSUE TITLE
[BUG] @prizm-ui/components - Наименование дней и месяцев на английском во вкладке "Дни", "Месяцы" комопонета Cron

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#466]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

[Сron](https://prizmui-next.web.app/components/cron)

### Версия

    "@prizm-ui/components": "1.2.4",
    "@prizm-ui/core": "1.2.4",
    "@prizm-ui/helpers": "1.2.4",
    "@prizm-ui/i18n": "1.2.4",
    "@prizm-ui/icons": "1.2.4",
    "@prizm-ui/theme": "1.2.4",

### Скрин / Видео проблемы
(Скриншот 1)
![image](https://github.com/zyfra/Prizm/assets/48792714/e69debb6-f21a-4207-badd-3bdd75d9ebfb)
(Скриншот 2)
![image](https://github.com/zyfra/Prizm/assets/48792714/e030a835-6fee-433e-b066-44dc98f6d97c)
(Скриншот 3)
![image](https://github.com/zyfra/Prizm/assets/48792714/c21fdc3c-9721-487f-a54b-8d038d2ad782)

### Воспроизведение проблемы

https://stackblitz.com/edit/ngx-14-title-demo-ka9wd2?file=package.json,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts

### Описание проблемы

При использовании комопннета Cron в приложении, все вкладки на русском языке, кроме вкладок "Дни" и  "Месяцы". На вкладках "Дни" и "Месяцы" наименовании дней недели , месяцев на английском языке.

В https://github.com/zyfra/Prizm/issues/383 предлагалось добавить '{ provide: LOCALE_ID, useValue: "ru-RU" }'. После добавления при работе с компонентом наблюдаю ошибки в консоли (см. скриншот 3).

**Comment by alexhawkins94** [comment]
на витрине у нас не воспроизводится в примерах, спасибо за пример на stackblitz

(скрины с витрины)
![chrome_O50i30vY4Q](https://github.com/zyfra/Prizm/assets/122870313/2edbd47c-1548-429d-9c54-aacfc20b1155)
![chrome_ufYBg4BsS0](https://github.com/zyfra/Prizm/assets/122870313/19068433-91df-443d-8ec6-4ccef979af71)

@ZurabDev

**Comment by badeevdm** [comment]
@alexhawkins94 проблема решена добавлением '{ provide: LOCALE_ID, useValue: "ru-RU" }'. Была ошибка на нашей стороне, issue закрываю, спасибо!
