### ISSUE TITLE
[BUG] @prizm-ui/components - Обрезается текст даты в области ввода периода Cron компонента

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#467]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

[Cron](https://prizmui-next.web.app/components/cron)

### Версия

    "@prizm-ui/components": "1.2.4",
    "@prizm-ui/core": "1.2.4",
    "@prizm-ui/helpers": "1.2.4",
    "@prizm-ui/i18n": "1.2.4",
    "@prizm-ui/icons": "1.2.4",
    "@prizm-ui/theme": "1.2.4",

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/48792714/49ca797b-b23a-4dce-b434-dd5c9b5bdbd2)

### Воспроизведение проблемы

https://stackblitz.com/edit/ngx-14-title-demo-lt8qkq?file=src%2Fstyles.css

_Шаги_

Выбрать дату в контроле "Начало работы"

### Описание проблемы

Использую в проекте шрифт "Inter', при вводе даты в контрол периода у Cron компонента последние цифры года и времени не влезают в область отображения и обрезаются. Можно ли настроить размер данных областей или сделать их просто больше?

**Comment by alexhawkins94** [comment]
проблема про Inter известная, а так же известно что мы до сих пор сами на Inter не перешли  https://github.com/zyfra/Prizm/issues/280 

https://github.com/zyfra/Prizm/issues/460 - тут уже приходили коллеги с аналогичной проблемой, предложили костылик кстати

т.к. пока на Inter не перешли у себя, то к сожалению большому, описанная в текущем issue проблема нами была не обнаружена (
