### ISSUE TITLE
[Feature] Переопределение текстов компонента в зависимости от его расположения

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#468]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Cron](http://v1-2-4.prizm.site/components/cron), i18n

### Предложение

Нужна возможность иметь разные тексты для одного и того же компонента в зависимости от места его использования.

Например, сейчас если определить provider с переводами в `providers` компонента, это не работает.
```js
{
  provide: PRIZM_LANGUAGE,
  useValue: of({
    ...PRIZM_RUSSIAN_LANGUAGE,
    cron: {
      ...PRIZM_RUSSIAN_LANGUAGE.cron,
      title: '',
      startDateLabel: 'Дата начала события',
      endDateLabel: 'Дата окончания события',
    },
  }),
},
```
Такое переопределение срабатывает только при помещении в AppModule providers. 

Потребность возникла на примере крона, но видится что это скорее имеет отношение к механизму i18n и было бы полезно и для прочих компонентов.

**Comment by ZurabDev** [comment]
<img width="781" alt="CleanShot 2023-07-19 at 18 41 28@2x" src="https://github.com/zyfra/Prizm/assets/75216044/4ad35d0c-67d3-4426-9696-7c640d95c8c8">
Готово
