### ISSUE TITLE
[BUG] @prizm-ui/components - Проблемы сборки

### ISSUE THREAD

**Issue by dmitriy-sokolov** [zyfra/Prizm#471]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

input-layout-date-range.component.d.ts
input-layout-date-time-range.component.d.ts

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
@prizm-ui/components
```

```
@angular/core@14.3.0
```

### Проект в котором используется Prizm

- _Название проекта_

### Скрин / Видео проблемы

![изображение](https://github.com/zyfra/Prizm/assets/25181659/e65f8aed-c63d-428c-99b9-6fbef776d771)

### Воспроизведение проблемы

конфигурация `tsconfig.json`:
```json
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "paths": {
      "@digital-plant/toolbar": [
        "dist/digital-plant/toolbar/digital-plant-toolbar",
        "dist/digital-plant/toolbar"
      ]
    },
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "noUnusedParameters": true,
    "noPropertyAccessFromIndexSignature": true,
    "skipLibCheck": false,
    "skipDefaultLibCheck": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2020",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

### Описание проблемы

В проекте есть пакет , в который подключен **PrizmButtonModule, PrizmHintModule, PrizmTooltipModule**. При попытке собрать пакет возникает ошибка указанная на скриншоте.

**Comment by ZurabDev** [comment]
Используйте skipLibCheck: true

**Comment by dmitriy-sokolov** [comment]
> Используйте skipLibCheck: true

в качестве временного решения можно рассматривать данный флаг. Но проблема в библиотека с типами остается.
