### ISSUE TITLE
[BUG] @prizm-ui/components - Не адаптируется хинт ошибки при заполненном поле

### ISSUE THREAD

**Issue by zerodi** [zyfra/Prizm#472]
### Библиотека

- [ ] `@prizm-ui/core`
- [X] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Input

### Версия

```
@prizm-ui/components 1.2.4
```

### Скрин / Видео проблемы

https://github.com/zyfra/Prizm/assets/1549303/be9e5905-38c2-474f-b48d-4e8e011652e4

### Описание проблемы

В случае, если инпут прижат к правому краю, хинт с ошибкой обрезается.

**Comment by ZurabDev** [comment]
Просим прислать ссылку на пример в песочнице

**Comment by imonogarov** [comment]
Закрыто по согласованию с @zerodi
