### ISSUE TITLE
[Feature] Не хватает компонента статичного уведомления

### ISSUE THREAD

**Issue by TheSpaceHuman** [zyfra/Prizm#475]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Предложение

В рамках перехода на prizm в app-shell, появилась необходимость в компоненте статичного уведомление, как например: alerts (https://getbootstrap.com/docs/5.0/components/alerts/). Планируем его использовать для уведомления пользователя в ограничении прав доступа. А то сейчас используется Toast, а он немного не уместен.

Поэтому предлагая добавить компонент статичного уведомление с акцентными цветами.

**Comment by bumalai** [comment]
> а он немного не уместен.
а в каком кейсе это необходимо? это элемент формы? нужно больше контекста,

**Comment by bree7e** [comment]
Мне кажется этот кейс следует сопроводить скриншотом как это будет использоваться

**Comment by PrizmDS** [comment]
@TheSpaceHuman ждем скрин, Дальше будем думать

**Comment by TheSpaceHuman** [comment]
Идея алертов заключалась в этом http://joxi.ru/1A5NkglCw9DvWr
Но пока, это все на этапе обсуждений, поэтому закрою issues.
