### ISSUE TITLE
[BUG] Toast. У тоста появилась двойная нижняя граница.

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#481]
-Перейти в примеры компонента тост
-Вызвать любой тост
ФР: у тоста нижняя граница стала двойной
![chrome_Xvx3iOmf60](https://github.com/zyfra/Prizm/assets/122870313/2a844b59-0fff-48bf-af7b-f75972c132b8)

**Comment by ZurabDev** [comment]
<img width="425" alt="CleanShot 2023-07-10 at 11 29 45@2x" src="https://github.com/zyfra/Prizm/assets/75216044/643acd0b-8d89-4999-9570-09e8816485ed">
Была похожая таска, не можем воспроизвести, просьба прислать алгоритм воспроизведения если проблема актуальна

**Comment by RoxVell** [comment]
@ZurabDev
1. перейти на любую страницу с документации призма, кроме тоастов, например: https://prizm.site/components/tabs
2. перейти на страницу Toast
3. нажать на кнопку с любым тоастом

Итог: граница двойная, в инспекторе элементов создано 2 одинаковых оверлея (создаются они всегда, даже если не проворачивать трюк с переходами между страницами).
