### ISSUE TITLE
[BUG] Tabs. Ошибка в консоли TypeError при клике на единственный таб, оставшийся после закрытия остальных.

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#483]
Ошибка в консоли TypeError при клике на единственный таб, оставшийся после закрытия остальных.

-Перейти к примеру closeable tabs
-Закрыть все табы, нажатием на крестик
-Сделать клик на последний оставшийся таб в списке
ФР: в консоли возникает ошибка TypeError: Cannot read properties of undefined (reading 'offsetLeft')

![chrome_CECJJkxjra](https://github.com/zyfra/Prizm/assets/122870313/d55c12ff-fbce-4784-a54a-a34bcaac4780)

**Comment by ZurabDev** [comment]
Не возможно воспроизвести
