### ISSUE TITLE
[BUG] InputLayoutDateTimeRange. Ошибка в консоли при выборе дат начала и конца интервала

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#489]
-Перейти к InputLayoutDateTimeRange
-Сделать клик и раскрыть календарь
-Выбрать дату начала и конца
ФР: в консоли ошибка Cannot read properties of undefined (reading 'daySame')
![chrome_GuFjXtq0Lt](https://github.com/zyfra/Prizm/assets/122870313/297b5ab8-940c-424b-8198-56fb995758d4)

Если затем выбрать время, то даты начала и конца автоматически изменяются и начинают совпадать, т.е. игнорируется сделанный выбор и выбирается текущий день.
![image](https://github.com/zyfra/Prizm/assets/122870313/be5f3115-86c6-46c6-92b6-6a6c4f8e25df)

**Comment by bree7e** [comment]
Столкнулись с этой проблемой на СОУ
