### ISSUE TITLE
[BUG] @prizm-ui/components - Слишком длинный заголовок в компонентах группы Input перекрывают "звездочку"

### ISSUE THREAD

**Issue by kolynchick** [zyfra/Prizm#493]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [ x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_Название компонента или группы компонентов_

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v18.14.1
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 2.0.0
```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Проект в котором используется Prizm

ОМ

### Скрин / Видео проблемы

Когда длина элемента больше заголовка:
![image](https://github.com/zyfra/Prizm/assets/12861107/beaecb16-2a8a-4951-b420-311b62cf13d9)

Когда заголовок не вмещается в контент:
![image](https://github.com/zyfra/Prizm/assets/12861107/3ecc84c6-7d9b-40c7-972e-cf2d49d41c0d)

**Comment by ZurabDev** [comment]
<img width="415" alt="CleanShot 2023-07-20 at 17 39 23@2x" src="https://github.com/zyfra/Prizm/assets/75216044/a3b9c5c3-f6f1-4911-9fac-cff6aae80a4c">
Готово
