### ISSUE TITLE
[BUG] @prizm-ui/icons - Missing add-plus-drop-down-list иконка

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#494]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [x] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_@prizm-ui/icons_

### Скрин / Видео проблемы

_![image](https://github.com/zyfra/Prizm/assets/2631748/73a4c9cd-0eac-40c3-af92-52b83e38e9e4)_

### Воспроизведение проблемы

https://prizm.site/components/icon

### Описание проблемы

Нужна SVG иконка `+` с выпадающим списком (шеврон). Данная иконка представлена в наборе Old Icon под именем `add-plus-drop-down-list`. В наборе SVG есть только `settings_tools_plus`

**Comment by PrizmDS** [comment]
@ZurabDev Есть ли возможность интегрировать шеврончик в виде проперти к некоторым иконкам?

**Comment by ZurabDev** [comment]
> @ZurabDev Есть ли возможность интегрировать шеврончик в виде проперти к некоторым иконкам?

Что имеется ввиду?

**Comment by ickisIckis** [comment]
Нужно проверить в 4.0
@alexhawkins94

**Comment by PrizmDS** [comment]
Иконка была интегрирована в набор для релиза в 4.0. 

Название: _plus-triangle-down_
