### ISSUE TITLE
[Feature] Заменить font иконки в компонентах на релизацию svg

### ISSUE THREAD

**Issue by bumalai** [zyfra/Prizm#496]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [x] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Icons, All

### Предложение

Заменить font иконки в компонентах на релизацию svg

**Comment by ZurabDev** [comment]
Блокирует https://github.com/zyfra/Prizm/issues/803
