### ISSUE TITLE
[Feature] Для кнопок PrizmSidebarService и PrizmConfirmDialogService добавить disabled state как Observable

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#497]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[SideBar](http://v1-2-4.prizm.site/components/dialogs/sidebar), [ConfirmDialog](http://v1-2-4.prizm.site/components/dialogs/confirm-dialog)

### Предложение

При прокидывании кнопок в вызов метода `sidebarService.open` или `confirmDialogService.open` нельзя задать условия, при которых блокируются эти кнопки. В настоящий момент типизация позволяет задать поле `disabled` (с типом `boolean`), но этого не достаточно.

```javascript
this.sidebarService
  .open(new PolymorphComponent(SomeComponent, this.injector), {
    ...
    confirmButton: {
      text: 'Button'
      disabled: true,
    },
  });
```

Хотелось бы иметь возможность определять условия блокировки таких кнопок, чтобы в качестве значения `disabled` можно было указать `Observable<boolean>`.

**Comment by ZurabDev** [comment]
<img width="450" alt="CleanShot 2023-07-18 at 14 57 25@2x" src="https://github.com/zyfra/Prizm/assets/75216044/2bba1e67-8057-452d-9e31-f242f782c966">
Добавлен пример
