### ISSUE TITLE
[BUG] @prizm-ui/components - InputNumber не блокируются до конца контролы

### ISSUE THREAD

**Issue by zerodi** [zyfra/Prizm#502]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

InputNumber

### Версия

Dependencies:

```
@prizm-ui/components 2.0.0
```

### Описание проблемы

При блокировании поля InputNumber контрол <prizm-input-number-auxiliary-controls/> продолжает отображаться как функционирующий.

**Comment by ZurabDev** [comment]
Если имелось ввиду отображение при disabled состоянии, готово
<img width="748" alt="CleanShot 2023-07-17 at 08 06 32@2x" src="https://github.com/zyfra/Prizm/assets/75216044/77884215-9f26-45f4-b61c-5a268de59ad0">
