### ISSUE TITLE
[Feature] Switcher, добавить ControlValueAccessor

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#508]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_Switcher_

https://prizm.site/components/switcher

### Предложение

Предлагаю добавить ControlValueAccessor. Сейчас DX страдает, контор часто используется в форме. Совершенно не удобно использовать в реактивных формах.

**Comment by ZurabDev** [comment]
Добавлено 
<img width="740" alt="CleanShot 2023-07-21 at 15 01 00@2x" src="https://github.com/zyfra/Prizm/assets/75216044/8f3fcba6-839a-477d-868a-6b06451f2f2d">
