### ISSUE TITLE
[Feature] InputSelect возможность получить значение из объекта

### ISSUE THREAD

**Issue by zerodi** [zyfra/Prizm#514]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputSelect

### Предложение

Добавить возможность указать атрибут объекта, который будет возвращаться в качестве значения формы.

**Comment by ZurabDev** [comment]
имется ввиду получить сам объект?

**Comment by zerodi** [comment]
Сейчас, если мы передаем массив объектов в InputSelect, в качестве value у Formcontrol возвращается объект из массива. Нужна возможность указать атрибут, который будет возвращаться вместо всего объекта.

**Comment by ZurabDev** [comment]
<img width="699" alt="CleanShot 2023-07-21 at 11 29 42@2x" src="https://github.com/zyfra/Prizm/assets/75216044/8347d02d-d4a2-4d40-94d9-9e7a51bac219">

Добавлен пример, готово
