### ISSUE TITLE
[Question] Stepper, Slider - когда должны быть эвенты?

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#531]
В степпере на данный момент есть эвент при переходе по шагам только при клике на номер шага?
Если жать на кнопку "следующий шаг", "предыдущий шаг" - то эвента нет, это точно ок?

В слайдере при изменении положения ползунка эвент отсутствует, это точно ок? Не должно ли быть аналогично сплиттеру ? 

![chrome_1mZwE72RUo](https://github.com/zyfra/Prizm/assets/122870313/8fdaf9ea-025b-4d56-b6aa-74cc6675f585)
![chrome_rPSXJH30FK](https://github.com/zyfra/Prizm/assets/122870313/9bd8c258-fd75-4e6f-ae0b-a76e4211f9ec)

**Comment by alexhawkins94** [comment]
починить в степпере

**Comment by ickisIckis** [comment]
Slider имплементирует интерфейс ControlvalueAccessor и должен работать не с событиями Output, а с formControl. Добавим в Live Demo
