### ISSUE TITLE
[Feature] Добавить возможность навешивания пользовательского класса на DropdownHost при раскрытии мультиселекта

### ISSUE THREAD

**Issue by OlgaMerkulova** [zyfra/Prizm#536]
### Библиотека
- [ ] `@prizm-ui/components`

### Компонент
InputMultiSelect, InputLayout, DropdownHost

### Предложение
При раскрытии InputMultiSelect возникает необходимость навесить пользовательский класс на DropdownHost, который выскакивает при открытии мультиселекта. Прошу добавить эту возможность - передать свой css класс через входной параметр на InputMultiSelect или InputLayout

**Comment by ZurabDev** [comment]
<img width="553" alt="CleanShot 2023-07-27 at 14 36 59@2x" src="https://github.com/zyfra/Prizm/assets/75216044/50a03f7d-6101-4a58-b822-bd82d16341d3">
Готово
