### ISSUE TITLE
[Question] Как использовать lazy loading в компоненте дерева без сервиса PrizmTreeService? 

### ISSUE THREAD

**Issue by dezisque** [zyfra/Prizm#538]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

prizm-tree

_Название компонента или группы компонентов_

### Версия
1.4.0

NodeJS:

v16.15.1

Dependencies:

"@prizm-ui/components": "^1.4.0",

Операционная ситема:

`MacOs`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Проект в котором используется Prizm

Stream

### Вопрос

Как использовать lazy loading в компоненте дерева без сервиса PrizmTreeService? 
Нам необходимо вывести структуру вида - 
-parent1
  -- child1
  -- child2
    --- child3
    ....
-parent2
  ....
-parent3
  ....
-parent4
  ....

На данный момент, как я понимаю, при использовании PrizmTreeService, указывается первый уровень вложенности. Нам нужен массив.
Т.к. документации на такой случай нет, был бы рад получить пример использования prizm-tree со сторонним сервисом.

**Comment by imonogarov** [comment]
Ответили в ЛС
