### ISSUE TITLE
[Feature] - Добавить возможность autoResize в компонент textarea

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#544]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Textarea

### Предложение

Добавить возможность autoResize в компонент textarea - когда autoResize включен, текстовое поле увеличивается вместо отображения полосы прокрутки.

**Comment by ZurabDev** [comment]
<img width="766" alt="CleanShot 2023-07-28 at 11 01 34@2x" src="https://github.com/zyfra/Prizm/assets/75216044/c69a7642-8235-45e9-84b9-f1810b30bf11">
Готово
