### ISSUE TITLE
[BUG] @prizm-ui/components - PrizmSelect не эмиттит change формы

### ISSUE THREAD

**Issue by dezisque** [zyfra/Prizm#546]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/components`

### Компонент

prizm-select

### Версия

Операционная ситема:

`MacOs`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.4.0
```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Проект в котором используется Prizm

Stream

### Скрин / Видео проблемы

1) Существует FormArray arrayForm;
2) в arrayForm находится массив formGroup'ов;
3) В шаблоне запись вида 
<div class="property" *ngFor="let item of arrayForm.controls">
  <prizm-select
    formControlName="name"
  ></prizm-select>
</div>
4) При подписке на this.arrayForm.valueChanges события с prizmSelect не приходят. С input'ов, чекбоксов и т.д. - приходят.

**Comment by ZurabDev** [comment]
@dezisque Вы использовали PrizmInputSelect?

**Comment by dezisque** [comment]
> @dezisque Вы использовали PrizmInputSelect?

Нет, PrizmSelect. Он deprecated?

**Comment by ZurabDev** [comment]
Да. Используйте PrizmInputSelect

Для автоматической замены всех депрекейтед компонентов
```nx generate @prizm-ui/nx-plugin:remove-prizm-deprecated-v1-2 --project=[YOU PROJECT NAME] ```
Подробнее
https://prizm.site/forZIIoT/migration
