### ISSUE TITLE
[BUG] @prizm-ui/components - InputMultiSelect - исчезает "..." при сбросе значения к "Все"

### ISSUE THREAD

**Issue by OlgaMerkulova** [zyfra/Prizm#547]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент
InputMultiSelect

### Описание проблемы
Использую мультиселект для выбора значений. По умолчанию выбираю все значения, они не помещаются, появляется "..."
 
![1](https://github.com/zyfra/Prizm/assets/52113470/02f315eb-5859-4423-a926-76373464c0c8)

Далее требуется сброс значений, значение по умолчанию - это весь список. В patchValue отправляю весь массив, и в случае, если до этого были выбраны все элементы, "..." пропадает, кажется, что выбрано только 2 элемента:
![2](https://github.com/zyfra/Prizm/assets/52113470/e83e635d-357b-421f-a82c-620fb653fa1e)

Однако когда раскрываю список, видно, что выбраны все 3:
![3](https://github.com/zyfra/Prizm/assets/52113470/e13247ee-e2fe-45b2-8072-2f94cf62fecf)

При этом, если до patchValue со всем массивом были выбраны не все элементы, то такой проблемы не наблюдается. С setValue то же самое

**Comment by ZurabDev** [comment]
https://app.replay.io/recording/prizm-ui-input-date--2320eac6-c2ef-4161-a647-07439711a9fb

Воспроизвести не смогли.
Какую версию исопльзуйте?

**Comment by ZurabDev** [comment]
Просьба обновить до последней версии. Проверить. Если проблема сохраняется воспроизвести на starblitz и переоткрыть issues
