### ISSUE TITLE
[BUG] @prizm-ui/components - testid атрибуты для <prizm-input-layout>

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#553]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

prizm-input-layout

### Описание проблемы

1) При использовании компонента `<prizm-input-layout>` в разметке через dev tools видно атрибут `data-testid="ui_input_layout"`. Наличие этого атрибута бессмысленно т.к. сейчас нельзя задать модификатор. Необходимо добавить возможность задавать модификатор через `testId` input property.

2) Кнопки внутри  `<prizm-input-layout>` имеют атрибут `data-testid="ui_input_icon_button"`, без модификатора. Это мешает использованию этих атрибутов т.к. нельзя определить где какая кнопка. Предлагается для каждой кнопки, которая не добавляется явно разработчиком, проставлять модификатор. Например, для кнопки сброса `data-testid="ui_input_icon_button--clear"` или для кнопки календаря `data-testid="ui_input_icon_button--date"`,

**Comment by ZurabDev** [comment]
<img width="623" alt="CleanShot 2023-07-30 at 23 42 26@2x" src="https://github.com/zyfra/Prizm/assets/75216044/61c7a789-1ad5-4d1c-ad8b-d0c39e9434e7">
<img width="491" alt="CleanShot 2023-07-30 at 23 42 23@2x" src="https://github.com/zyfra/Prizm/assets/75216044/afe1ce25-56dd-4454-a3f1-0f89cd5ff897">

Вы можете задать через testId постфикс для любого элемента с testId
Доступно по ссылке https://prizm.site/components/input/Live_demo?tuiMode=null&PrizmInputLayout.testId=2222

Используйте последние версии

**Comment by dkshichkovskiy** [comment]
Да, сори, не заметил, что есть такая возможность. Тогда пункт 1 не актуален.

Но есть ещё пункт 2. @ZurabDev Это можно поправить?
