### ISSUE TITLE
[Feature] возможность изменять длину линии под заголовками табов

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#558]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Tabs

### Предложение

Добавить возможность изменять длину линии под заголовками табов. 
Пример:
![image](https://github.com/zyfra/Prizm/assets/17219726/bedfc1b2-6214-4319-9b76-deb39e0015fe)

**Comment by ZurabDev** [comment]
@AsyaSokolova Для чего этого нужно? Вы хотите что бы линии были только под самими табами (их текстами - Информация, Свойства)?

**Comment by bumalai** [comment]
Кажется это не по гайду тогда будет

**Comment by AsyaSokolova** [comment]
> Кажется это не по гайду тогда будет

Попробую согласовать с заказчиком текущую реализацию

**Comment by ZurabDev** [comment]
Если будет актуальна таска, просьба переоткрыть.
