### ISSUE TITLE
[FEATURE] @prizm-ui/components - добавить возможность вручную расстягивать texrarea

### ISSUE THREAD

**Issue by gustav2775** [zyfra/Prizm#559]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент
prizmInput Texarea

### Версия

1.2.4
2.1.3

### Проект в котором используется Prizm

- _Название проекта_

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/71187404/a6a6451c-0f0b-491c-8276-92a172d28621)

На дизайне Prizm
![image](https://github.com/zyfra/Prizm/assets/71187404/1f24ecb6-dedd-4a55-98c8-875090313543)

![image](https://github.com/zyfra/Prizm/assets/71187404/a177692a-349c-46a5-9399-049ae9ed2d78)

### Описание проблемы

Во всех версиях:
1. отсутствует возможность вручную расстягивать texrarea
2. отстутствует захват в правом нижнем углу textarea

По дизайну данная возможность есть.

Требуется  добавить для версий 1.2.x и 2.1.х

**Comment by alexhawkins94** [comment]
не реализовывали эту фичу for some reason 
@ZurabDev  не помнишь почему не делали в принципе это?

**Comment by AleksandrSibiakov** [comment]
Прошу прощения, а что решение дает поверх нативного CSS https://developer.mozilla.org/en-US/docs/Web/CSS/resize ?
(которое отлично работает для textarea и дает возможность настройки растягивания по одной или обоим осям)
Ведь доступ к контролу есть у разработчика:
```html
<prizm-input-layout label="label">
    <textarea style="resize: vertical;"></textarea>
</prizm-input-layout>
```

**Comment by ZurabDev** [comment]
Да теперь использование стилей будет работать норм, раньше можно было накткнуться на такой кейс
<img width="446" alt="CleanShot 2023-08-14 at 17 11 56@2x" src="https://github.com/zyfra/Prizm/assets/75216044/c5a1a28f-0a7d-4c9e-b4ab-91402da480e9">
