### ISSUE TITLE
[BUG] Не работает forceClear в InputSelect

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#562]
### Библиотека
- [ ] `@prizm-ui/components`

### Компонент

InputSelect

### Проект в котором используется Prizm

- Конфигуратор

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/17219726/f1d98cf3-be10-43aa-abc6-19e259b580ed)

### Воспроизведение проблемы

![image](https://github.com/zyfra/Prizm/assets/17219726/243e3d17-92dc-4346-a8cf-411b7372c326)

### Описание проблемы

При добавлении свойства forceClear для InputSelect возникает ошибка. В документации это свойство в списке присутствует
![image](https://github.com/zyfra/Prizm/assets/17219726/d5e2f619-6e29-439a-b05a-77dc48c15021)

**Comment by ZurabDev** [comment]
<img width="471" alt="CleanShot 2023-08-02 at 10 35 30@2x" src="https://github.com/zyfra/Prizm/assets/75216044/1f711c1c-0ed0-41ab-9247-61116dcf3950">

Его  должны установить у input-layout а не у самого prizm-input-select

**Comment by ZurabDev** [comment]
`nx generate @prizm-ui/nx-plugin:remove-prizm-deprecated-v1-2 --project=[YOU PROJECT NAME] `
также для авто замены можно использовать мигратор
https://prizm.site/forZIIoT/migration
