### ISSUE TITLE
[Feature] Добавить возможность менять template выбранного значения в InputSelect

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#564]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

InputSelect

### Предложение

Добавить возможность кастомизации темплейта для выбранного элемента в списке. Пример:
![image](https://github.com/zyfra/Prizm/assets/17219726/81c199ad-3508-4ef9-a2e2-fdac500bce4a)

На данный момент компонент не предоставляет такой возможности:
![image](https://github.com/zyfra/Prizm/assets/17219726/891a4bb4-23e3-4c5a-b561-ad78e032d30a)

**Comment by ZurabDev** [comment]
<img width="581" alt="CleanShot 2023-08-03 at 16 28 26@2x" src="https://github.com/zyfra/Prizm/assets/75216044/dbe07fb1-77ee-4b16-b769-f9a96b563181">
Обновили пример
