### ISSUE TITLE
[BUG][InputLayoutDateTimeRange] @prizm-ui/components - Не работает с реактивными формами

### ISSUE THREAD

**Issue by dmitriy-sokolov** [zyfra/Prizm#565]
### Библиотека
- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputLayoutDateTimeRange

### Версия

Dependencies:
```
@prizm-ui/components 1.4.1
```

### Проект в котором используется Prizm

- Редактор даталинк

### Скрин / Видео проблемы

![изображение](https://github.com/zyfra/Prizm/assets/25181659/31189c3e-60b3-45d4-929a-e1e794d6cbce)

### Воспроизведение проблемы

Прикрепил файл с проектом

### Описание проблемы

Проект собирается. В консоли ошибки.

[example_range.zip](https://github.com/zyfra/Prizm/files/12251547/example_range.zip)

**Comment by ZurabDev** [comment]
Ошибка в пример вы вместо prizm-input-layout-date-time-range использовали prizm-input-layout-date-range
