### ISSUE TITLE
[Feature] PrizmArea - добавить возможность поворота лейблов по оси х

### ISSUE THREAD

**Issue by dezisque** [zyfra/Prizm#573]
### Библиотека

- [ ] `@prizm-ui/charts`

### Компонент

PrizmArea

### Предложение

Возможность поворота подписей значений по оси x на 45 и 90 градусов

<img width="663" alt="image" src="https://github.com/zyfra/Prizm/assets/35841155/9c6d7b02-ef48-429d-9411-22f99b7b8485">

**Comment by ickisIckis** [comment]
Такая функция присутствует в antV g2plot, на которых сделаны графики. 
Для того, чтобы повернуть лейбл необходимо передать конфигурацию для оси с заданным свойством rotate. Например:
` 
xAxis: {
  rotate: 45
},
` 

 Значения передаются в числовом формате, указывается угол поворота в радианах по часовой стрелке.
 Информация из документации:
  | rotate | number | Text rotation angle, unit is radian, clockwise rotation |

https://g2plot.antv.antgroup.com/en/api/components/label
