### ISSUE TITLE
[Feature][Sidebar] Добавить возможность ограничения области отображения сайдбаров / оверлеев

### ISSUE THREAD

**Issue by MisterWind** [zyfra/Prizm#576]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Sidebar, Overlay

### Предложение

Занимаюсь задачей по выводу некоторого контента в сайдбаре.
Сейчас сайдбар отображается на весь экран. Задача отобразить сайдбар в ограниченной области (в пределах встроенного приложения).

AS_IS:
![image](https://github.com/zyfra/Prizm/assets/23579119/1d2600de-b9c2-4b82-ae5a-107ffb13f791)

TO_DO:
![image](https://github.com/zyfra/Prizm/assets/23579119/4d8264a7-eb2b-4882-926e-e2acb9bbc6e8)

1. Предлагаю добавить возможность при открытии сайдбара указывать parentContainer.
2. Расчет размера сайдбара должен ограничиваться размерами parentContainer.
3. Область отображения backdrop-а должна ограничиваться размерами parentContainer.
4. При включенном флаге dismissable должна выполняться проверка на попадание клика в область parentContainer.

Поэкспериментировал локально, желаемый результат в приложенном видео.

https://github.com/zyfra/Prizm/assets/23579119/602fa994-9bf7-4c65-ab05-f5fee775a134

Если в текущем решении есть способ ограничить область отображения сайдбара по другому, просьба добавить такой способ в примеры в документации.

**Comment by alexhawkins94** [comment]
приложите макеты дизайна пожалуйста 
и для каких оверлеев вы хотите данную доработку помимо сайдбара? для диалогов и тд нужно?

**Comment by MisterWind** [comment]
Сайдбар:
![image](https://github.com/zyfra/Prizm/assets/23579119/7a2213ef-0223-4ae3-b283-887b546f5fe0)
Диалог:
![image](https://github.com/zyfra/Prizm/assets/23579119/b428a6ef-ad82-43be-bc77-982803ef7857)
На обоих макетах backdrop не перекрывает шапку и боковик, так что хотелось бы для всех оверлеев.

**Comment by ZurabDev** [comment]
Понял

**Comment by ZurabDev** [comment]
Добавим

**Comment by stepandr** [comment]
Специально повышали z-index в оболочке чтобы приложения не перекрывали) предлагаю лучше сделать возможность указать его где нужно перекроет, где нет, там нет.

**Comment by MisterWind** [comment]
@stepandr а у оверлеев сейчас z-index по-умолчанию 9999
Тут задача скорее в том, чтобы сайдбар ориентировался относительно приложения, и оболочку не затрагивал (сейчас prizm-overlay встраивается в body).
+ думаю будет кому-то полезно, если диалоговое окно будет открываться в конкретной компоненте в том числе и внутри приложения.

Допустим, пример:
Оболочка, внутри приложения, внутри которого еще 2 компоненты, одна с таблицей, вторая с редактором выбранного элемента.
Нам дали дизайн, что диалоговое окно должно вылазить только в рамках компонента "Редактора".

Если оперировать флагом "перекроет"/"нет" то у нас не получится гибко определять пространство, в котором будет существовать оверлей и его бакдроп.
