### ISSUE TITLE
[Feature][Cron] Предоставить инструмент для преобразования текста в формате Cron как в компоненте

### ISSUE THREAD

**Issue by MisterWind** [zyfra/Prizm#577]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Cron

### Предложение

Работаю в рамках задачи редактирования расписания в формате cron.
Нужен инструмент (функция или pipe) для преобразования полученного из Cron компоненты текста в human-readable формат.
![image](https://github.com/zyfra/Prizm/assets/23579119/b98a3f28-0346-4925-8545-a2f931cf4b47)

Предлагаю добавить функцию prizmCronHRToString на экспорт.
Реализовать pipe PrizmCronHRToStringPipe и добавить на экспорт.
Предусмотреть локализацию.

**Comment by ZurabDev** [comment]
![CleanShot 2023-08-18 at 13 22 54@2x](https://github.com/zyfra/Prizm/assets/75216044/4f9410e7-7427-4a46-b4d1-d224091ea920)
Готово
