### ISSUE TITLE
[BUG][Cron] @prizm-ui/components - Изменение во вкладке "День" ломает дальнейшее редактирование

### ISSUE THREAD

**Issue by MisterWind** [zyfra/Prizm#579]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Cron
### Версия

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.4.1
```

### Проект в котором используется Prizm

- Редактор даталинк

### Скрин / Видео проблемы

https://github.com/zyfra/Prizm/assets/23579119/8e26e398-de9f-477d-82e0-2fc71dfdb6a8

### Воспроизведение проблемы

[Пример в песочнице](https://ziiot-dev-11.kube01.yc.ziiot.ru/components/cron)

### Описание проблемы

Добавляю компоненту крон для настройки расписания в формате Cron.

Наблюдается проблема, возникающая при изменении блока "День" в компоненте.
При включении блока "День" и переключении между radiobutton-ами дальнейшее редактирование в компоненте перестает работать.

**Comment by alexhawkins94** [comment]
не можем воспроизвести, подробнее опишите кейс и пример с stackblitz

**Comment by MisterWind** [comment]
### Браузеры проверки
Повторяется в следующих браузерах:

- Google Chrome 115.0.5790.171
- Microsoft Edge 115.0.1901.200
- Mozilla Firefox 116.0.2

### Сценарии воспроизведения

Сценарий 1.
1. Откройте https://prizm.site/components/cron
2. Тестируем на компоненте в блоке Base
3. Перейдите во вкладку "День".
4. Выберите Пункт "Каждый <1> час начиная с <0>" (можно другой, кроме "Каждый день"). Далее пункт А.
5. Выберите пункт "Каждый час" (далее пункт Б).
6. Выберите любой другой пункт (отличающийся от пункта А) во вкладке "День".
7. Обратите внимание, что в текстбоксе значение перестало меняться.

https://github.com/zyfra/Prizm/assets/23579119/7916dd90-4fc4-4a4b-b5fd-be43f0c129be



Сценарий 2.
1. Откройте https://prizm.site/components/cron
2. Тестируем на компоненте в блоке Base
3. Перейдите во вкладку "Секунды" и выберите любой пункт (можно попереключаться).
4. Перейдите во вкладку "Минуты" и выберите любой пункт (можно попереключаться).
5. Перейдите во вкладку "Часы" и выберите любой пункт (можно попереключаться).
6. Перейдите во вкладку "Месяцы" и выберите любой пункт (можно попереключаться).
7. Перейдите во вкладку "Годы" и выберите любой пункт (можно попереключаться).
8. Перейдите во вкладку "День".
9. Выберите Пункт "Каждый <1> час начиная с <0>" (можно другой, кроме "Каждый день"). Далее пункт А.
10. Выберите пункт "Каждый час" (далее пункт Б).
11. Выберите любой другой пункт (отличающийся от пункта А) во вкладке "День".
12. Обратите внимание, что в текстбоксе значение перестало меняться.

https://github.com/zyfra/Prizm/assets/23579119/78a9f8d8-ae61-4a4f-853d-bb47073cd808
