### ISSUE TITLE
[BUG] charts-area - при попытке передать только время, график выглядит некорректно 

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#580]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/components`

### Компонент

charts-area

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Проект в котором используется Prizm

- Конфигуратор

### Скрин / Видео проблемы

_Скриншот.jpg_

### Описание проблемы

при попытке передачи только времени, график выглядит следующим образом
![image](https://github.com/zyfra/Prizm/assets/17219726/7da4cbab-1e9a-4538-bcec-e9b59aa9337a)

**Comment by ZurabDev** [comment]
Просим скинуть все данные mock слепок того что передаете в компонент

**Comment by ickisIckis** [comment]
Из скриншота можем предположить, что для одной из точек не было передано значение для оси Y, в таком случае график выдает ожидаемое поведение.

Для более точного ответа на вопрос необходим слепок данных и параметры настроек графика.
