### ISSUE TITLE
[Question]- Как отображать все передаваемые значения даты?

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#581]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

charts-area

### Версия

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

`@prizm-ui/components 2.1.4`

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Проект в котором используется Prizm

- Конфигуратор

### Вопрос

Как отобразить все передаваемые значения времени? На графики передано 42 значения, но отображается только 3 временных интервала.
![image](https://github.com/zyfra/Prizm/assets/17219726/5b6ca542-1cab-4efc-aa59-8683526ffe0b)

**Comment by ZurabDev** [comment]
Просим отправить все слепок данных которые передает в компонент

**Comment by ickisIckis** [comment]
Насколько можно судить по скриншоту, отрисовано не три точки, а больше  - вероятно все 42.
 При этом по оси x задано 3 'тика'.  Управление 'тиками' доступно через опции, подробнее о которых можно узнать по ссылке: https://g2plot.antv.antgroup.com/en/api/options/meta#metaoptionticks
 
 Для более точно ответа необходимо получить слепок данных и все настройки графика.
