### ISSUE TITLE
[Feature] PrizmDialog - добавить возможность отключить закрытие диалогового окна при клике по backdrop

### ISSUE THREAD

**Issue by OlgaMerkulova** [zyfra/Prizm#582]
### Библиотека
- [ ] `@prizm-ui/components`

### Компонент
PrizmDialog

### Предложение
Добавить возможность отключить закрытие диалогового окна при клике по backdrop, то есть чтобы закрыть диалоговое окно можно было только по крестику. Сейчас там при открытии модального окна инлайново добавляется pointer-events: unset, и css стилями это уже не перебить.

**Comment by ZurabDev** [comment]
![Uploading CleanShot 2023-08-11 at 16.02.01@2x.png…]()
Обновлен пример в доке

**Comment by ZurabDev** [comment]
<img width="891" alt="CleanShot 2023-08-11 at 16 03 57@2x" src="https://github.com/zyfra/Prizm/assets/75216044/ceb71f89-f943-4c28-9d99-1c475b9c9775">
Обновлен пример в доке
