### ISSUE TITLE
InputLayoutDateTimeRange. Если интервал задан одним днем/временем, то при редактировании интервала одна из его границ задана автоматически

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#597]
-Перейти к примеру InputLayoutDateTimeRange 
-Отображается дефолтная дата в примере  10.03.2018 00:00 - 10.03.2018 00:00
![image](https://github.com/zyfra/Prizm/assets/122870313/355b4a1e-228c-478b-92c0-c9c5eaf609ff)
-Сделать клик по инпуту и раскрыть выбор даты
-В календаре 10.03 отображается как выбранная граница
-Навести курсор на дату после 10 либо до 10
-Отображается интервал 
-Сделать клик по числу после 10 либо до 10

ФР: Календарь закрывается, в value обновляется значение - выбранная дата становится началом/концом интервала. Таким образом, в случае когда дата начала = дата окончания, при редактировании интервала один из его концов получается заданным как бы автоматически. И календарь закрывается после первого клика.
ОР: поведение как в обычном кейсе при редактировании интервала

![image](https://github.com/zyfra/Prizm/assets/122870313/042fd957-7681-4cab-b961-5e3d3d807df0)

**Comment by ZurabDev** [comment]
Иследование проведено. Такое поводение, было изначально заложено, менять его будет дорого
