### ISSUE TITLE
[BUG] prizm/components - Отправка формы при клике по иконке (статуса)

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#60]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/theme`

### Компонент

**PrizmInputLayout**, иконки на различных форм-контролах

### Версия

Dependencies:

```
➜ npm ls @prizm-ui/components       

`-- @prizm-ui/components@1.0.0-beta.23 
```

```
➜ npm ls @angular/core

`-- @angular/core@14.2.12
```

### Описание проблемы

В различных контролах присутствуют элементы типа `<button>`. Например, [иконка статуса в **InputLayoutComponent**](https://github.com/zyfra/Prizm/blob/6ac5fd3162b401d148272ab025fc506a7711e563/libs/components/src/lib/components/input/common/input-layout/input-layout.component.html#L70), кнопки для открытия выпадающего списка (в частности *prizm-input-date-multi*). 

Проблема заключается в том, что эти кнопки, при расположении компонента внутри `<form>`, вызывают отправку последней ([в соответствии W3C](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#attr-button-type) кнопки по умолчанию являются `[type=submit]`).

Считаю, что использование форм для управления пользовательским вводом является критической функцией, и [используется в Angular](https://angular.io/api/forms/NgForm) для группировки полей ввода и отражения их на модели бизнес логики. Также, частный сценарий использования `<form>` - триггер отправки формы (или произвольного обработчика) по нажатию *Enter* в `<input>` и др. (стандартное браузерное поведение). 

### Workaround

Проверять и фильтровать события по значению свойства *submitter*. (затруднительно из за большого количества возможных кейсов)

_Шаги воспроизведения_:

1. Для сценария http://zds.zyfra.com/components/input#validation-example добавить родительскую форму
2. Кликнуть по иконке валидации (красный кружок с `!`)
3. Проверить *submitted* свойство у формы - оно НЕ должно быть равным `true`

### Предложение
Добавить ко всем **<button>** элементам `[type=button]` для предотвращения отправки формы.

**Comment by ZurabDev** [comment]
Просьба проверить в 24 версии и закрыть issue

**Comment by AleksandrSibiakov** [comment]
На версии 1.0.0-beta.24 проблема не воспроизводится.
