### ISSUE TITLE
[Feature][InputMultiSelect] - Добавить состояние (indeterminate) для элемента "Выбрать все"

### ISSUE THREAD

**Issue by javadoffuad** [zyfra/Prizm#608]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputMultiSelect

### Предложение

В выпадающем компоненте при выборе одной или нескольких элементов, но не всех из списка, в чек-боксе "Выбрать все" показать знак "-"

![image](https://github.com/zyfra/Prizm/assets/7090093/be25459e-d68d-4b04-ab25-f6abd7a64df5)

![image](https://github.com/zyfra/Prizm/assets/7090093/584da78d-c843-4414-953e-47e72b0337ff)

**Comment by ZurabDev** [comment]
<img width="354" alt="CleanShot 2023-08-17 at 15 33 41@2x" src="https://github.com/zyfra/Prizm/assets/75216044/72b30e4a-6f78-443f-8b94-c278ee854e33">
