### ISSUE TITLE
[Feature] Отображение хинта в текстовом поле если значение не отображено полностью

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#615]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Input

### Предложение

Есть потребность отображать хинты с указанными значениями у текстовых полей, если значение не отображается полностью (не вмещаются в видимую область контрола). Кажется, было бы полезно добавить такую возможность в КБ, чтобы она была из  коробки. 

Плюс тут есть нюанс. Хинт с подсказкой может отображаться при наведении на иконку ошибки валидации, например. Надо как-то это обыграть, чтобы эти хинты не мешали друг другу.

Данная доработка нужна в prizm-input-layout, где может быть введён произвольный текст (в порядке убывания приоритетов):
- https://prizm.site/components/input 
- https://prizm.site/components/input-number

**Comment by ZurabDev** [comment]
<img width="702" alt="CleanShot 2023-09-04 at 16 25 21@2x" src="https://github.com/zyfra/Prizm/assets/75216044/5e2c6194-a875-4768-be72-dd1caab7ad31">
Обновлены страницы апи в доке. Добавлено свойства новые
