### ISSUE TITLE
[Feature] Требуется вариант компонент компонента InputSelect для выбора цвета

### ISSUE THREAD

**Issue by alexx3000** [zyfra/Prizm#627]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент
InputSelect

_Название компонента или группы компонентов_

### Предложение
В Prizm есть компонент ColorPicker, используемый для выбора цвета. Однако в КБ отсутствует компонент инициирущий вызов этого пикера. 

_Работаю в рамках задачи_

_Предлагаю сделать ..._
Добавить в InputSelect проперти с компонентом выбора цвета, который будет отображать текущий цвет, и клик по которому будет вызывать панель ColorPicker

**Comment by ZurabDev** [comment]
ColorPicker нет в prizm на данный момент. По поводу выбора цвета, можно https://prizm.site/components/input-select#with-list-item-template вот эту реализацию посмотреть разрботчик, и сделать подобное
