### ISSUE TITLE
[Feature] Добавить для InputSelect поведение, аналогичное zyfra-dropdown с [editable]=true

### ISSUE THREAD

**Issue by algashev123zyfra** [zyfra/Prizm#629]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

InputSelect

### Предложение

На этапе перехода на Prizm возникла проблема: старый подход основывался на компоненте zyfra-dropdown в режиме editable, т.е. можно было вводить значение в сам инпут и при желании выбрать предложенное из выпадающего списка. на данный момент возможности вводить значение в сам инпут нет.

_Работаю в рамках задачи_

https://jira.zyfra.com/browse/PLATFORM01-30386

**Comment by ZurabDev** [comment]
Пробывали использовать searchable параметр?

**Comment by algashev123zyfra** [comment]
> Пробывали использовать searchable параметр? InputSelect > InputLayoutSelect

При searchable параметре появляется инпут в выпадающем списке. Нам же нужна возможность вводить значение в сам инпут без манипуляций с выпадающим списком (то есть помимо значений из выпадашки пользователь может задать свое).

**Comment by ZurabDev** [comment]
Следите за задачей https://github.com/zyfra/Prizm/issues/906 на след спринт назначена, пока готовим тех часть для этого компонента
