### ISSUE TITLE
[Question] @prizm-ui/components - Sidebar нужна лишь одна кнопка `закрыть`

### ISSUE THREAD

**Issue by dmitriy-sokolov** [zyfra/Prizm#630]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

SideBar

### Версия

Dependencies:

`@prizm-ui/components 1.4.2`

### Проект в котором используется Prizm

- Редактор даталинк

### Вопрос

Нужно выполнить задачу согласно макетам 
![изображение](https://github.com/zyfra/Prizm/assets/25181659/cebb7a7c-8fca-4bed-b92b-14592e48aca2)
.

 Есть примеры в [песочнице](https://prizm.site/components/dialogs/sidebar) по работе с компонентом Sidebar. Но нет примеров, когда нужно только вывести информацию пользователю с кнопкой `закрыть`... Как это сделать?!

**Comment by ZurabDev** [comment]
<img width="855" alt="CleanShot 2023-08-25 at 15 41 19@2x" src="https://github.com/zyfra/Prizm/assets/75216044/c606eb9e-0f8b-4b98-b066-090106066287">
Добавлен пример

**Comment by dmitriy-sokolov** [comment]
> <img alt="CleanShot 2023-08-25 at 15 41 19@2x" width="855" src="https://user-images.githubusercontent.com/75216044/263271520-c606eb9e-0f8b-4b98-b066-090106066287.png"> Добавлен пример

отлично, а код можно сюда 
чтобы сразу использовать...

**Comment by dmitriy-sokolov** [comment]
Спасибо за пример, но использовать его к сожалению не могу: так как он перечит контракту, что обязывает накручивать костыли... @ZurabDev , укажите, пожалуйста, тогда поддерживаемый тип `null`
![изображение](https://github.com/zyfra/Prizm/assets/25181659/7f460112-44c3-47d1-8e07-a40cf68e4785)
