### ISSUE TITLE
Почистить live demo от лишних свойств

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#653]
Во многих компонентах в live demo висит большое кол-во лишних свойств, которые отображать на витрине нет особого смысла.
Например, pseudoState и подобные, readonly.

Такие свойства можно найти в компонентах switcher, dialog  и тд 
![chrome_Nhu4LxnnhK](https://github.com/zyfra/Prizm/assets/122870313/11b5b9eb-64b3-497b-992b-ef5b7fcca8be)

Нужно вычистить капитально доку и оставить только актуальные свойства для каждого компонента

**Comment by alexhawkins94** [comment]
dialog
sidebar
confirm dialog
toggle

**Comment by alexhawkins94** [comment]
В списке компонентов ниже в live demo отсутствуют свойства outer и size.
Прошу добавить для удобства проверок и полноты демо

Password
Mask
Chips
Input text
Multi

в chips и input - size отображается в live demo, но не сделана возможность изменять их в live demo

**Comment by ickisIckis** [comment]
> confirm dialog

на данный момент нашла только у dialog
