### ISSUE TITLE
InputSelect. Не обрезается длинное имя выбранного айтема в инпуте

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#662]
-Выбрать айтем с длинным именем
ФР: в инпуте не обрезается имя этого айтема
ОР: раньше такое имя обрезалось
![chrome_qNVzfcgQdQ](https://github.com/zyfra/Prizm/assets/122870313/1e5a4cf1-2a55-4e60-8687-c0b670bcec29)

было:
![image](https://github.com/zyfra/Prizm/assets/122870313/481e31f6-ab75-4063-b34b-3d92f4a68c73)

**Comment by Mainkira** [comment]
Добавлена метка idp, так как появился аналогичный баг с прода. 
https://github.com/zyfra/Prizm/issues/684
