### ISSUE TITLE
InputPassword. Варнинги Found 2 dom elements with non-unique id

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#669]
Перейти в input password, открыть live demo
В консоли варнинги вида
![chrome_LkbPNmkcox](https://github.com/zyfra/Prizm/assets/122870313/83e87a07-8787-4e4b-98a2-29fd3320292f)

появилось в рамках мр https://github.com/zyfra/Prizm/pull/667

**Comment by ickisIckis** [comment]
На 5.1 не воспроизводится,
