### ISSUE TITLE
[Feature] Disabled стейт для PrizmPaginatorComponent

### ISSUE THREAD

**Issue by Zyfra123** [zyfra/Prizm#67]
### Библиотека

- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/theme`

### Компонент

PrizmPaginatorComponent

### Предложение

Добавить disabled стейт с биндингом, блокирующий нажатия по номерам страниц, стрелкам перехода между страницами, rowsSelector'ом

**Comment by ZurabDev** [comment]
Готово просьба проверит и закрыть тикет
