### ISSUE TITLE
[Feature] PrizmInputSelect - stringify - поддержка Observalbe<string> в качестве возвращаемого значения в PrizmSelectStringify

### ISSUE THREAD

**Issue by kolynchick** [zyfra/Prizm#682]
### Библиотека

- [ ] `@prizm-ui/core`
- [ x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmInputSelect

### Предложение

При работе со статичными справочниками часто возникает потребность хранить i18n локали на фронте. Чтобы не создавать промежуточный объект, содержащий переводы, используем stringify совместно с сервисом, взаимодействующим с i18n. В специфичных кейсах, локали не успевают подгрузится и синхронные методы не срабатывают. Возникает потребность взятия локалей асинхронно. 

Как сделано сейчас - export type PrizmSelectStringify<T> = (i: T, nullContent?: string) => string;
Как бы хотелось  - export type PrizmSelectStringify<T> = (i: T, nullContent?: string) => string | Observable<string>;

**Comment by ZurabDev** [comment]
<img width="629" alt="CleanShot 2023-09-04 at 16 24 18@2x" src="https://github.com/zyfra/Prizm/assets/75216044/51d5f0de-445b-4d01-a435-76f8091ffbb0">
Готово
