### ISSUE TITLE
[BUG] @prizm-ui/components - InputSelect длинное название не обрезается

### ISSUE THREAD

**Issue by AntonGrekov** [zyfra/Prizm#684]
### Библиотека

- [ ] `@prizm-ui/components` - 2.1.6 (angular 15)

### Компонент

InputSelect

### Проект в котором используется Prizm

IDP

### Скрин / Видео проблемы

![изображение](https://github.com/zyfra/Prizm/assets/44285258/9d5b115e-cb2b-4338-9217-1038da9427a9)

### Воспроизведение проблемы

К сожалению не удалось собрать стакблитц по ссылке ниже:
https://stackblitz.com/edit/ngx-14-title-demo-enp5ng?file=src%2Fapp%2Fapp.component.html

### Описание проблемы

Если выбранный айтем для InputSelect это длинноедлинноедлинноедлинноесловобезпереносов (слово без пробелов), то компонент расширяется вертикально и не обрезает текст

_Шаги воспроизведения_:

1. Добавить InputSelect
2. Добавить айтем из Описание проблемы
3. Выбрать его

ФР - на скрине
ОР - текст обрезается 

![изображение](https://github.com/zyfra/Prizm/assets/44285258/f5f5edc4-4e43-496d-9513-9795e11aabfb)

**Comment by Mainkira** [comment]
Закрываю issue, так как он является дубликатом https://github.com/zyfra/Prizm/issues/662
