### ISSUE TITLE
[BUG] prizm/components - PrizmSplitterComponent ошибка во время вычисления значения containerSize

### ISSUE THREAD

**Issue by digital-plant-guard** [zyfra/Prizm#69]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/theme`

### Компонент

PrizmSplitterComponent

Dependencies:

```
"@prizm-ui/components": "^1.0.0-beta.23",
"@prizm-ui/core": "^1.0.0-beta.23",
"@prizm-ui/helpers": "^1.0.0-beta.23",
"@prizm-ui/icons": "^1.0.0-beta.23",
"@prizm-ui/theme": "^1.0.0-beta.23",
```

```
"@angular/animations": "^14.2.12",
"@angular/cdk": "^14.2.7",
"@angular/common": "^14.2.12",
"@angular/core": "^14.2.12",
"@angular/forms": "^14.2.12",
"@angular/platform-browser": "^14.2.12",
"@angular/platform-browser-dynamic": "^14.2.12"
```
### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/126816006/223149851-d9f13631-20ac-4129-9d3c-fcb7af2addf7.png)

### Описание проблемы

В приложении мы запоминаем размеры панелей сплитера. Для этого в `ngAfterViewInit` устанавливаем размеры панелей через метод setAreasSize(), что ведет к ошибке: "TypeError: Cannot read properties of null (reading 'width') at **get containerSize** [as containerSize] (prizm-ui-components.js:22744:58)".

Кажется, что это происходит из-за того, что в геттере используется свойство `containerBoxSize` которое инициализируется только после того как придет значение по потоку entries$: ResizeObserverService

![image](https://user-images.githubusercontent.com/126816006/223151872-a9dd1a14-d1d2-4547-9b0f-5abce78f4c30.png)

Пример кода из приложения:

```
@ViewChild('mainViewSplitter')
mainViewSplitter: PrizmSplitterComponent;
```
```
ngAfterViewInit(): void {
    this.savedSizes$.pipe().subscribe(sizes => {
       this.mainViewSplitter.setAreasSize([sizes.left, sizes.right]);
    });
 }
```

**Comment by AleksandrSibiakov** [comment]
@ZurabDev @skkonstantin подскажите статус по задаче? Может нужна помощь? 

Стоит лейбл *question*, но не понятно какой вопрос.

**Comment by skkonstantin** [comment]
В следующем релизе скорее всего будет исправлено. Но будут breaking changes

**Comment by skkonstantin** [comment]
done
