### ISSUE TITLE
[Feature] - Изменить поведение работы Map структур в PrizmTableTreeService 

### ISSUE THREAD

**Issue by kolynchick** [zyfra/Prizm#692]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmTable

### Предложение
Сейчас, для отслеживания признака показа/скрытия дочерних сегментов дерева используем Map структуру showDirectChildrenMap с самогенерируемым числовым id. 
Работает во всех случаях, кроме кейса, при котором измененный массив данных будет передаваться снова в prizmTbody и в prizmRow. (Пример, когда работаем со Store и храним дерево внутри него: https://stackblitz.com/edit/prizm-v2-demo-yiw3wx?file=src%2Fapp%2Fapp.component.ts). Так же при кейсе, когда используем пагинацию и в одну и ту же табличку подгружаем новую пачку данных.

Что предлагаю:
1.  в prizmTbody добавить @Input(), который будет использоваться для взятия уникального ключа из записи, например [metaKey]
2. При формировании Map структуры берем в качестве ключа значение из item[metaKey]. Таким образом увеличиваем гарантийность того, что Map будет хранить раскрытые элементы на протяжении всей жизни компоненты.

**Comment by ZurabDev** [comment]
<img width="380" alt="CleanShot 2023-09-14 at 12 07 34@2x" src="https://github.com/zyfra/Prizm/assets/75216044/ddeb1dcd-3bc5-4911-9844-b9a9c4dd5c76">
https://prizm.site/components/table#tree

вот пример
