### ISSUE TITLE
[Feature] PrizmSplitterComponent - кастомизация splitter-gutter

### ISSUE THREAD

**Issue by digital-plant-guard** [zyfra/Prizm#70]
### Библиотека

- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/theme`

### Компонент
PrizmSplitterComponent 

### Предложение

Сейчас `prizm-splitter-gutter` имеет фиксированную ширину. Зачастую в приложениях требуется такой слайдер, где ширина gutter'а нулевая и есть только "слайдер" (класс .slider) за который можно тянуть для изменения ширины панелей. Пробовали переопределять стили через `::ng-deep` но это приводит к образованию пустой зоны в контейнере, тк ширина панелей контролируется через `flex-basis` а при вычислении учитывается ширина gutter'a.

Хотелось бы иметь возможность более гибко стилизовать gutter'ы PrizmSplitterComponent и чтобы их ширина корректно учитывалась при формировании панелей.

![image](https://user-images.githubusercontent.com/126816006/223158477-30bdd62f-cad3-4424-b571-ab2dfaa9c056.png)

Пустая зона при модификации стилей вручную:

![image](https://user-images.githubusercontent.com/126816006/223161617-62e771d1-6ad4-4f97-a527-7c30f97ba0a4.png)

![image](https://user-images.githubusercontent.com/126816006/223161365-78cfed30-f8a5-484b-a603-d024d4376955.png)

**Comment by AleksandrSibiakov** [comment]
А что если сделать и заэкспортить директиву, которая будет рисовать в определенном месте элемент, за который можно потянуть? По сути гаттер сплиттера это частное применение этой директивы. 
Тогда можно будет просто эту директиву применить к меню, и тем самым управлять его шириной (т.е. не применять непосредственно сплиттер). Это, кстати, поможет не решать проблему с расчетами ширины, и не надо убирать border который по умолчанию splitter так же провайдит.
@skkonstantin @digital-plant-guard

**Comment by AleksandrSibiakov** [comment]
@ZurabDev @skkonstantin Подскажите статус по задаче? Нужна ли помощь? (in_progress стоит давно)

Есть еще идея пофиксить эту задачу через использование `flex: 1 1 auto` для последней панели (или более генерализованное  решение - поддержка `auto` для размера). Применили такое решение локально на уровне CSS - полет нормальный. Правая панель (у нас их 2) занимает все доступное пространство, ей по сути не нужен calc и не надо учитывать вручную ширину `border` & `gutter`. 
Если интересно, могу сделать PR.

**Comment by skkonstantin** [comment]
После обсуждения с дизайнерами было принято решение, что splitter-gutter не кастомизируется

**Comment by skkonstantin** [comment]
Если это прям сильно нужно, можно провести встречу и обсудить

**Comment by AleksandrSibiakov** [comment]
Тогда нужна рекомендация как реализовать поведение, описанное в дизайн документе 
![image](https://user-images.githubusercontent.com/2631748/234269190-ce1ec22b-d156-4c97-94d0-6bf45bf84ead.png)

**Comment by AleksandrSibiakov** [comment]
> Тогда нужна рекомендация как реализовать поведение, описанное в дизайн документе ![image](https://user-images.githubusercontent.com/2631748/234269190-ce1ec22b-d156-4c97-94d0-6bf45bf84ead.png)

Сплиттер, выходит, в данном случае не применим - он имеет бордер и гаттер, которые не кастомизируются.

**Comment by skkonstantin** [comment]
border у сплитера можно убрать, он на хосте. по поводу кастомизации поговорю с дизайнерами еще раз, но также надо понять почему у вас на проекте сделано не по дизайн системе
