### ISSUE TITLE
[BUG][DOC] prizm/components - На витрине в ярлыке ряда страниц вместо названия undefined

### ISSUE THREAD

**Issue by ickisIckis** [zyfra/Prizm#72]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/theme`

### Компонент

Документация

### Версия
 1.0.0-beta.24 

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Скрин / Видео проблемы

![image](https://user-images.githubusercontent.com/18642277/223949655-bc10b206-f79d-4110-89f9-f4dec15affcb.png)

### Описание проблемы

На витрине на ярлыке браузера вместо названия страницы Undefined.

_Шаги воспроизведения_:

Воспроизводится на страницах
http://zds.zyfra.com/about-prizm/license
http://zds.zyfra.com/about-prizm/changelog
http://zds.zyfra.com/about-prizm/contacts
http://zds.zyfra.com/guidelines/typography
http://zds.zyfra.com/guidelines/colors
http://zds.zyfra.com/guidelines/grid
http://zds.zyfra.com/how-to-start/for-developers
http://zds.zyfra.com/how-to-start/migration

**Comment by ZurabDev** [comment]
Просьба проверить и закрыть тикет
