### ISSUE TITLE
Toast. Отсутствует "красивая" обрезка длинного текста в тосте, в случае если текст не умещается в отображаемой области тоста.

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#734]
Кейс:
-перейти в live demo компонента navigation menu
-развернуть дерево в меню и кликнуть на дочерние элементы

ФР: отображается тост с длинным текстом. Текст не помещается по высоте и просто обрывается/перекрывается границей тоста. + отсутствует нижний отступ 
![chrome_2RcAyIkYaw](https://github.com/zyfra/Prizm/assets/122870313/f377c073-5998-48b3-a4f9-a2e6fda7ff69)

ОР: предлагаю сделать:  если у нас отображается один огромный тост, то в нем сделать бы обрезку многоточием лишнего текста (который не умещается в тосте) в случае, когда тост занимает 60% высоты на текущем масштабе/размере экрана.

**Comment by ZurabDev** [comment]
Расмотреть добавление скробара
