### ISSUE TITLE
InputMonth & InputMonthRange. Зона клика находится за пределами инпута

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#740]
-Перейти к примерам и live demo компонентов Input Month, Input month range
-Сделать клик вне инпута рядом
Фактический результат: происходит вызов и раскрытие дейтпикера
Ожидаемый результат: область клика д.б ограничена инпутом

**Comment by ickisIckis** [comment]
InputMonth в данный момент устаревший компонент, помечен флагом  deprecated, рекомендуется использовать аналог InputLayoutMonth, в котором эта проблема отсутствует
