### ISSUE TITLE
InputDateTime. Ширина дропдауна не соответствует ширине инпута (сильно уже)

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#741]
-Перейти к InputLayoutDateTime
-Раскрыть выбор времени
Фактический результат: дропдаун сильно меньше ширины инпута
Ождиаемый результат: ширина дропдауна с выбором времени соответствует ширине инпута - как в inputLayoutTime

Аналогично в 
InputDateMulti
DropDownHost - пример Date Range Template (Nested Dropdown), Date Range 2 Template

![image](https://github.com/zyfra/Prizm/assets/122870313/d4b74984-9894-4144-8049-d81e8d04df51)

**Comment by ZurabDev** [comment]
![CleanShot 2023-10-27 at 16 54 11@2x](https://github.com/zyfra/Prizm/assets/75216044/d099ca30-59a4-47ee-9fbb-3b3e6d0dabc3)
