### ISSUE TITLE
Dialog. Длинный текст в хедере не обрезается/нет скролла

### ISSUE THREAD

**Issue by alexhawkins94** [zyfra/Prizm#755]
1. На витрине перейти в компонент Dialog
2. На странице с компонентом открыть режим live demo
3. В атрибуте header установить "ОченьДлинныйТекстОченьДлинный…"
4. Нажать кнопку Show Dialog
ФР: текст не обрезается, хедер растягивается и не видно остальной части диалога.
ОР: либо обрезка текста, либо скролл в зоне хедера (как в sidebar)

![image](https://github.com/zyfra/Prizm/assets/122870313/27e10816-9f68-4a08-be0e-086c227e64e3)

**Comment by alexhawkins94** [comment]
поправим пример

**Comment by PrizmDS** [comment]
В обычном диалоге в заголовке может быть только одна строка. В конфирм диалоге может быть три строки, остальное в три точки. 

P.S. В обычном диалоге должен быть компонент "panel"
