### ISSUE TITLE
[BUG] @prizm-ui/components - PrizmInputLayoutDateRangeComponent, не срабатывает позиционирование выбранного года

### ISSUE THREAD

**Issue by AntonGrekov** [zyfra/Prizm#760]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/components` @ 2.1.7

### Компонент
PrizmInputLayoutDateRangeComponent

### Проект в котором используется Prizm
IDP

### Скрин / Видео проблемы
![изображение](https://github.com/zyfra/Prizm/assets/44285258/e4b5cb67-2d99-4047-be47-32cb723b7f4b)

### Воспроизведение проблемы
Можно увидеть воспроизведение на устаревшем компоненте (https://prizm-v2.web.app/components/input-date-range). 
V2 Angular 15.
Cсылки на стакблитц для InputLayoutDateRange у меня не работают(не собирается проект)
https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.html

Пример:

https://stackblitz.com/edit/ngx-14-title-demo-enp5ng?file=src%2Fapp%2Fapp.component.html

### Описание проблемы
_Есть проблема следующего характера:_
Если в рендже выбран год 2023, то при клике по году для выбора года из списка - список не позиционируется на текущем выбранном годе(2023), а начинается либо с 2000 либо с 1923(-100лет)

_Шаги воспроизведения_:
1. Добавить компонент
2. Задать дату
3. Нажать на выбор года

**Comment by ZurabDev** [comment]
Просьба создать пример в песочнице. Можно перейти сразу с доки (где выбирают версии) или же в примерах использования если есть кнопка stackblitz

**Comment by AntonGrekov** [comment]
@ZurabDev Не получается перейти по ссылке из доки. Вот такое показывает при выборе V2 (NG 15) с этой страницы: https://prizm-v2.web.app/components/input-date-range

![image](https://github.com/zyfra/Prizm/assets/44285258/b2928ea9-c2db-4102-87f8-1c3aa42ec230)

**Comment by AntonGrekov** [comment]
@ZurabDev а почему не удаётся найти 2.3.0 версию в репозитории, хотя на сайте доки она есть ?
Вот тут мне удалось воспроизвести. Версия призм 2.1.7

View: https://prizm-v2-demo-mloftw.stackblitz.io
Editor: https://stackblitz.com/edit/prizm-v2-demo-mloftw?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

**Comment by ZurabDev** [comment]
Добавил в текущий релиз

**Comment by ZurabDev** [comment]
> @ZurabDev а почему не удаётся найти 2.3.0 версию в репозитории, хотя на сайте доки она есть ?
> 
> Вот тут мне удалось воспроизвести. Версия призм 2.1.3 View: https://prizm-v2-demo-mloftw.stackblitz.io Editor: https://stackblitz.com/edit/prizm-v2-demo-mloftw?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

Посмотрю

**Comment by ZurabDev** [comment]
> @ZurabDev Не получается перейти по ссылке из доки и сделать рабочий stackblita. Вот такое показывает при выборе V2 (NG 15) с этой страницы: https://prizm-v2.web.app/components/input-date-range
> 
> ![image](https://user-images.githubusercontent.com/44285258/277732425-b2928ea9-c2db-4102-87f8-1c3aa42ec230.png)

Проверю

**Comment by ZurabDev** [comment]
> @ZurabDev задача уже подгорает прилично. Достаточно давно висит. Посмотрите, пожалуйста. От меня что-то еще требуется добавить ? Ссылки на воспроизведение проблемы есть в пред сообщении

Вроде все. Сори что пропустили, зафорсим

**Comment by ZurabDev** [comment]
Написал в личку @AntonGrekov. Ждем ответа по поводу проверки.  Просьба если проблема есть переоткрыть и написать как воспроизвести

**Comment by stepandr** [comment]
Проблема устранилась за исключением ошибки в консоли возникающей при запуске версии но она связана с dev режимом https://github.com/zyfra/Prizm/issues/492

Для проверки использовалось

    "@prizm-ui/components": "^3.8.0-beta.3",
    "@prizm-ui/core": "^3.8.0-beta.3",
    "@prizm-ui/helpers": "^3.8.0-beta.3",
    "@prizm-ui/i18n": "^3.8.0-beta.3",
    "@prizm-ui/icons": "^3.8.0-beta.3",
    "@prizm-ui/theme": "^3.8.0-beta.3",
