### ISSUE TITLE
[Docs] добавить информацию как менять темы, цветовые схемы, актуализировать страницу со цветами.

### ISSUE THREAD

**Issue by bumalai** [zyfra/Prizm#765]
Необходимо добавить Theme Guidline.

Пример хорошего гайдлайна: https://clarity.design/documentation/themes

**Comment by PrizmDS** [comment]
@ickisIckis  Ссылка на внутренний документ https://jira.zyfra.com/wiki/pages/viewpage.action?pageId=198133230

**Comment by ickisIckis** [comment]
В рамках задачи обновлена страница с цветами и добавлено описание работы с токенами,
гайд для разработчиков будет реализовано в задаче #979
