### ISSUE TITLE
[Feature] Добавить св-во white-space: pre-line для заголовка и дополнительного текста диалога

### ISSUE THREAD

**Issue by webatom** [zyfra/Prizm#768]
### Библиотека

- [x] `@prizm-ui/components`

### Компонент

`PrizmDialogConfirmComponent`

### Предложение

Предлагаю добавить css свойство `white-space: pre-line` для `title` и `description` компонента `ConfirmDialog`.

Позволит корректно выводить подобные сообщения:
```json
"LabelTitle": "Вы не сохранили внесённые изменения.\nПроизвести расчёт?"
```

**Comment by ZurabDev** [comment]
Похожий кейс https://github.com/zyfra/Prizm/issues/781
