### ISSUE TITLE
[Feature] Реализация компонента ColorPicker

### ISSUE THREAD

**Issue by Zyfra123** [zyfra/Prizm#77]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

ColorPicker

### Предложение

Предлагаю реализовать компонент ColorPicker, аналогичный [компоненту PrimeNG](https://primeng.org/colorpicker)

![image](https://user-images.githubusercontent.com/125573094/224738806-73063afc-b11a-47c1-8ba9-d969c4f2d311.png)

**Comment by ZurabDev** [comment]
Обсудили. Предлагаем использовать сторонний компонент или свою реализацию
