### ISSUE TITLE
[BUG] @prizm-ui/components - prizm-scroll-controls - visibility не корректно работает

### ISSUE THREAD

**Issue by stepandr** [zyfra/Prizm#780]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_Название компонента или группы компонентов_

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

**Версия 117.0.5938.150 (Официальная сборка), (64 бит)**

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 2.1.8
```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Проект в котором используется Prizm

- Везде

### Скрин / Видео проблемы

https://disk.yandex.ru/i/tkpIEJvhrBiIow - видео с проблемой

### Воспроизведение проблемы

Пример: https://doc.prizm.zyfra.com/components/scrollbar

### Описание проблемы

У одной из наших сотрудниц в браузере не показывается полоса прокрутки, если задать в классе visibility=visible тогда показывается а если просто style остается то у нее ничего не показывает. Настройки хрома пробовали крутить вертеть не помогло.

В общем рекомендую явно прописать для элемента prizm-scroll-controls - стиль visibility:visible

**Comment by stepandr** [comment]
Проблема так же связана с https://github.com/zyfra/Prizm/issues/491 - но тут похоже что она не решилась

**Comment by ZurabDev** [comment]
Для контроля есть опция
<img width="1039" alt="CleanShot 2023-10-06 at 15 33 22@2x" src="https://github.com/zyfra/Prizm/assets/75216044/c743e128-cab4-43ab-a279-a4c8bd665233">

**Comment by alexhawkins94** [comment]
@stepandr актуально? ответ выше помог?

**Comment by AntonGrekov** [comment]
@alexhawkins94 
@ZurabDev 

ответ выше не удаётся применить, т.к. у нас окно со скролом вызывается через PrizmConfirmDialogService, а у него в опциях данной настройки нет. Нашёл только overscrollMode, наверно это другое, да ?

**Comment by AntonGrekov** [comment]
@ZurabDev @alexhawkins94 как быть в ситуации описанной выше ?

**Comment by AntonGrekov** [comment]
Коллеги, подскажите статус по этой задаче ? @ZurabDev @alexhawkins94

**Comment by alexhawkins94** [comment]
@AntonGrekov пока планируем в 3.9 

@ZurabDev может что-то еще посоветуешь?

**Comment by ZurabDev** [comment]
Привет.
Да след неделю завершить постараемся @AntonGrekov  @alexhawkins94
