### ISSUE TITLE
[BUG] @prizm-ui/components - Отсутствует кнопка закрытия виджета, несмотря на установленное свойство closeable: true

### ISSUE THREAD

**Issue by YashaKorolev** [zyfra/Prizm#785]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Sidebar

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 2.1.8
```

```
➜ npm ls @angular/core

@prizm-ui/components@0.0.2
├─┬ @angular/animations@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/cdk@12.2.13
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/common@12.2.12
│ └── @angular/core@12.2.12 deduped
├── @angular/core@12.2.12
├─┬ @angular/forms@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser-dynamic@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/platform-browser@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @angular/router@12.2.12
│ └── @angular/core@12.2.12 deduped
├─┬ @storybook/angular@6.3.12
│ └── @angular/core@12.2.12 deduped
├─┬ jest-preset-angular@10.0.1
│ └── @angular/core@12.2.12 deduped
└─┬ primeng@12.2.2
  └── @angular/core@12.2.12 deduped


```

### Проект в котором используется Prizm

- Энергоконтроль

### Скрин / Видео проблемы

![sidebar_1](https://github.com/zyfra/Prizm/assets/47750082/9c502172-341c-4a19-ac6d-4d5831ff367b)

Фактический результат:

![sidebar_2](https://github.com/zyfra/Prizm/assets/47750082/9de3beeb-3b43-4da4-86e3-065621116201)

Ожидаемый результат:

![sidebar_3](https://github.com/zyfra/Prizm/assets/47750082/e70cedb8-572d-434d-a20a-a59d55d12191)

### Описание проблемы

_Есть проблема следующего характера:_

При открытии виджета не появляется кнопка его закрытия, несмотря на установленное свойство closeable: true

_Шаги воспроизведения_:

1. Зайти по адресу [energycontrol](https://energycontrol-dev-02.kube02.yc.ziiot.ru/dashboard/aspes/long)
2. в фильтрах выбрать значения

![Screenshot_1](https://github.com/zyfra/Prizm/assets/47750082/9f8111d4-0f03-4a2b-85dd-e578b5c525a2)

3. выбрать ЭСМ и нажать ПКМ
4. нажать в открывшемся контекстном меню на "Комментарии"

**Comment by alexhawkins94** [comment]
@YashaKorolev все еще актуально?

**Comment by imonogarov** [comment]
@YashaKorolev т.к. нет обратной связи issue закрываем
