### ISSUE TITLE
[Feature] Поддержка локализации (Валидаторов и file-upload)

### ISSUE THREAD

**Issue by zerodi** [zyfra/Prizm#79]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Предложение

Необходимо реализовать локализацию компонентов. В очень многих компонентах зашит текст на русском языке.

**Comment by ZurabDev** [comment]
Какой  именно компонент нужен на данном этапе?

**Comment by zerodi** [comment]
На текущий момент требуется локализация Валидаторов и file-upload

**Comment by ZurabDev** [comment]
Добавлена страница как добавить язык /how-to-work/internationalization
И поддержка мультиязычности в file-upload

**Comment by zerodi** [comment]
Из документации непонятно, как работать с языками, как переключать, как формировать словарь.

**Comment by ZurabDev** [comment]
Поддержку мультиязычности в file-upload добавили, просьба создать новый issue для добавления примера как использовать и изменять словари
