### ISSUE TITLE
[Feature] Text wrap mode for select

### ISSUE THREAD

**Issue by YashaKorolev** [zyfra/Prizm#793]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

inputSelect

### Предложение

В данный момент inputSelect ведет себя следующим образом:
Если название внутри items длинное и состоит из нескольких слов, то select растягивается вниз чтобы вместить value полностью.

![photo_2023-10-06_14-46-20](https://github.com/zyfra/Prizm/assets/47750082/edfe2e4b-e50c-4130-9a65-a4cfa31a30f4)

Предлагаю добавить функцию контроля данного поведения, чтобы была возможность не растягивать select вниз

**Comment by ZurabDev** [comment]
![CleanShot 2023-10-11 at 17 55 07@2x](https://github.com/zyfra/Prizm/assets/75216044/8cb81737-b514-4c49-be7c-f5845682dddb)
Готово
