### ISSUE TITLE
Кастомный footer для Confirm Dialog

### ISSUE THREAD

**Issue by ZyfraKonstantinKulik** [zyfra/Prizm#799]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Confirm Dialog

### Предложение

Работаю в рамках задачи, в которой надо показывать Confirm Dialog с отличными от стандартных элементами подтверждения/отказа 

Предлагаю предусмотреть возможность передачи шаблона для footer компоненту Confirm Dialog

**Comment by AleksandrSibiakov** [comment]
Поддерживаю. 

Также считаю, было бы неплохо заменить текущий интерфейс добавления кнопок
https://github.com/zyfra/Prizm/blob/2359b74b818c2026807f2282ce249afe7b966067/libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.models.ts#L13-L16
на что то вроде
```ts
buttons: (PrizmConfirmDialogButton | string)[]
```
