### ISSUE TITLE
[Feature] Синхронизировать иконки с дизайнерскими

### ISSUE THREAD

**Issue by TheSpaceHuman** [zyfra/Prizm#803]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [x] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### PrizmIconsSvgComponent

`<prizm-icons-svg/>`

### Предложение

Работаю в рамках задачи PLATFORM01-30048, столкнулся с проблемой отличия и отсутствия ряда иконок при разработке. 
Первоначальным решением было добавления кастомных иконок с предварительной оптимизацией svg и прототипированием названий:
<img width="280" alt="Снимок экрана 2023-10-10 в 14 01 57" src="https://github.com/zyfra/Prizm/assets/39803718/b1427118-0ab5-46db-8f27-96f3f72ed81a">
<img width="420" alt="Снимок экрана 2023-10-10 в 14 02 23" src="https://github.com/zyfra/Prizm/assets/39803718/29163f51-c977-4571-9af7-4b167f553fbe">

Все новые [иконки](https://www.figma.com/file/dhv3tzSiwqo1ztD2pewr03/%F0%9F%92%8E-Prizm.-Icons-V2?type=design&node-id=397%3A11491&mode=design&t=3vSt8PfPJUMHE8XV-1), которые встречаются по макетам, требуют этой процедуры.
Пример различий иконок в случае, если находятся аналогичные (новые иконки тоньше и с корректным размером полотна):
<img width="152" alt="Снимок экрана 2023-10-10 в 14 13 07" src="https://github.com/zyfra/Prizm/assets/39803718/332b1857-9bb0-40fe-9614-785dea6339c4">

Исходя из этого, считаю целесообразным интегрировать новые иконки в компонент PrizmIconsSvgComponent, для использования их всеми командами, а не городить одну и ту же кастомизации для разных команд.

Предлагаю добавить новые иконки в PrizmIconsSvgComponent сохранив преемственность названий из [макета](https://www.figma.com/file/dhv3tzSiwqo1ztD2pewr03/%F0%9F%92%8E-Prizm.-Icons-V2?type=design&node-id=397%3A11491&mode=design&t=3vSt8PfPJUMHE8XV-1).
Что делать со старыми иконками, решайте сами: удалять их или состыковывать с коллизиями названий новых иконок. В любом случае, останутся иконочные шрифты `<i class="prizm-icon icon-name">`, с помощью чего можно будет применить старые иконки.

С внимание отнестить к `viewBox` svg-icons, чтобы полотно не привышало размеров границ самой иконки.

### Важно
Изменения необходимы в версии v.2.x.x - c Angular 15

**Comment by ZurabDev** [comment]
Иконки будут доступны с 4 версии из за breacking changes
