### ISSUE TITLE
[Feature] Добавления функционала в Button

### ISSUE THREAD

**Issue by TheSpaceHuman** [zyfra/Prizm#809]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### PrizmButtonComponent

prizmIconButton

### Предложение

Работаю в рамках задачи PLATFORM01-30048, столкнулся с необходимостью помечать prizmIconButton флагом активности. Для наглядного отображения активации (toggled) prizmIconButton.
<img width="274" alt="Снимок экрана 2023-10-11 в 13 34 56" src="https://github.com/zyfra/Prizm/assets/39803718/99541194-c446-4918-aac1-869ab6175b60">
Это позволит отказаться от компонента обертки и перейти в полной мере на prizmButton.

Кроме этого аспекта, есть проблема в удобстве использования компонента кнопки с заданной иконкой. Из-за того, что компонента внутри себя использует устаревший `<prizm-icon/>` приходиться добавлять иконки через template.
<img width="735" alt="image" src="https://github.com/zyfra/Prizm/assets/39803718/af762cbf-3afe-4e02-a297-52d8fd7f3bec">

Предлагаю добавить новое свойство `active: boolean`, которое будет отвечать за отображения кнопки в активированном режиме для их тоглирования. Вместе с этим добавить новые переменны в тему для кастомизации, т.к. понадобиться поведение между `primary` и `secondary` в `ghost` режиме.
<img width="631" alt="Снимок экрана 2023-10-11 в 13 52 53" src="https://github.com/zyfra/Prizm/assets/39803718/eca4bb6b-992a-4ecd-94d7-601065d3b84e">
И заменить `<prizm-icon/>` на `<prizm-svg-icon/>` внутри компонентов кнопок.

### Важно
Изменения необходимы в версии v.2.x.x - c Angular 15

**Comment by AleksandrSibiakov** [comment]
@TheSpaceHuman можно добиться требуемого поведения используя инпут `[pseudoPressed]="isActive"`

**Comment by ickisIckis** [comment]
Как @AleksandrSibiakov написал выше, с этой целью можно использовать состояние  [pseudoPressed], пример в документации обновим.
