### ISSUE TITLE
[Question] title prizm-widget

### ISSUE THREAD

**Issue by if1t** [zyfra/Prizm#811]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [x] #819
- [ ] `@prizm-ui/nx-plugin`

### Компонент

prizm-widget

### Версия

NodeJS:

```
➜ node --version
v16.20.2
```

Dependencies:

`@prizm-ui/components3.1.0`

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Вопрос

Можно ли как-то поместить компоненты <prizm-input-date-time-range> и <button> в title компонента prizm-widget?

**Comment by if1t** [comment]
И еще вопрос, как можно увеличить высоту prizm-panel, при этом чтобы не появлялась горизонтальная линия?
![изображение](https://github.com/zyfra/Prizm/assets/93567572/853dc7b1-b010-4b04-b2f1-7f67106de110)
```
<div class="container">
  <prizm-panel style="height: 80px">
    <div class="header" header>
      <div class="vl"></div>

      <prizm-breadcrumbs
        [breadcrumbs]="breadcrumbs"
        (breadcrumbChange)="changeCrumbListener($event)"
      ></prizm-breadcrumbs>


      <div class="container" instruments>
      ...
```

**Comment by ickisIckis** [comment]
Добрый день, title принимает на вход PolymorphContent,  поэтому туда можно передать шаблон с нужными компонентами. Например, так:
`html
<prizm-widget [title]="myTemp">
  ...
</prizm-widget>

<ng-template #myTemp>
 <my-component</my-component>>
</ng-template>
` 
По второму вопросу: не могли бы вы уточнить, про какую горизонтальную линию идет речь?

**Comment by if1t** [comment]
> <ng-template #myTemp> <my-component> ` По второму вопросу: не могли бы вы уточнить, про какую горизонтальную линию идет речь?

Речь шла про border-bottom у компонента prizm-panel. По этому вопросу решил проблему через 
```
::ng-deep .panel {
   height: 64px;
}
```
