### ISSUE TITLE
[Feature] Overlay. Передача контекста в шаблон, инжектора в компонент

### ISSUE THREAD

**Issue by skkonstantin** [zyfra/Prizm#813]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmOverlay

### Предложение

1)Нужен пример как передать контекст в template при использовании PrizmOverlayService
2) Нужен пример как передать injector компонент при использовании PrizmOverlayService

**Comment by ZurabDev** [comment]
![CleanShot 2023-11-01 at 17 02 19](https://github.com/zyfra/Prizm/assets/75216044/960ac246-7fec-43d8-ab2f-8d5caedbeda6)
Готово
