### ISSUE TITLE
[Feature] Управление колонками таблицы: скрыть/показать столбец.

### ISSUE THREAD

**Issue by ickisIckis** [zyfra/Prizm#82]
### Библиотека

- [ ] `@prizm-ui/core`
- [X ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

Table

### Предложение
 Часто в таблицах требуется функционал управления колонками: скрыть/показать столбцы. 
Было бы здорово на уровне библиотеки реализовать такую возможность.

На нашем проекте управление столбцами предполагается из шапки виджета: по кнопке открывается дропдаун с чекбоксами и списком колонок, которые можно скрыть. При таком подходе, идеальным была бы возможность передать таблице список активных (или наоборот скрытых) колонок.

**Comment by ZurabDev** [comment]
Дизайнеры добавить пример реализации после возьмем в разрботку

**Comment by PrizmDS** [comment]
@ZurabDev  https://www.figma.com/file/2KJZq6hHEdxQmFMRVTJWKT/branch/TpC0IF0ALw996r0KvS9h9o/%F0%9F%92%8E-Prizm.-%D0%A1omponent-base-4.0?type=design&node-id=20818%3A267112&mode=design&t=QN7FF7JNKmtwAWIJ-1
