### ISSUE TITLE
[Question] График с несколькими линиями

### ISSUE THREAD

**Issue by if1t** [zyfra/Prizm#823]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

prizm-charts-line

### Версия

NodeJS:

```
➜ node --version
v16.20.2
```

Dependencies:

`@prizm-ui/components 3.1.0`

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Вопрос

1. Можно ли построить на [графике](https://doc.prizm.zyfra.com/charts/line#base) несколько линий? Если да, то как?
2. Есть ли возможность поменять [tooltip](https://doc.prizm.zyfra.com/components/tooltip#base) при наведении на точку графика?  Если да, то как?
3. Есть ли возможность изменять масштаб графика?  Если да, то как?
![изображение](https://github.com/zyfra/Prizm/assets/93567572/2ed3ded5-f04d-4496-8995-342eee186a4f)

**Comment by ickisIckis** [comment]
Добрый день.
1. Для того, чтобы нарисовать на графике несколько линий в [options] для графика нужно установить значение seriesField: key. Где key  будет значение поля, по которому чарт будет сортировать точки по сериям.
Например, при входных данных вида
`[
    {
      x: 'Понедельник',
      y: 50,
      name: 'Мария'
    },
    {
      x: 'Вторник',
      y: 200,
      name: 'Мария'
    },
    {
      x: 'Понедельник',
      y: 150,
      name: 'Петр'
    },
    {
      x: 'Вторник',
      y: 100,
      name: 'Петр'
    },
    ]`
    И [options]="{seriesField: 'name'}"
    будет отрисовано две линии: для Марии и для Петра каждая.
    
    2. Для tooltip в options также можно задавать значения, например можно передать функцию-форматтер:
```
    tooltip: {
  formatter: (datum: Datum) => {
    return { name: datum.x, value: datum.y + '%' };
  },
}
```

**Comment by if1t** [comment]
Добрый день!
Спасибо большое! Где-то можно посмотреть все доступные опции графика?

**Comment by ickisIckis** [comment]
Графики реализованы на базе AntV g2plot, с  подробным API можно ознакомиться здесь: https://g2plot.antv.antgroup.com/en/api/plot-api

**Comment by if1t** [comment]
> Графики реализованы на базе AntV g2plot, с подробным API можно ознакомиться здесь: https://g2plot.antv.antgroup.com/en/api/plot-api

Принял, спасибо!

**Comment by if1t** [comment]
Легенду графика также можно изменять? Например местоположение или стили?

**Comment by ickisIckis** [comment]
Да, для легенды тоже можно предать настройки в options. Как для самой легенды в целом, так и для отдельных элементов внутри: заголовка, кнопок управления страницами, маркеров и т.п. Для имени и значения кроме стилей можно передать функцию-форматтер. 
Чтоб задать положение легенды используется поле position:
`ts
    legend: {
      position: 'bottom',
    },
`
