### ISSUE TITLE
[BUG] @prizm-ui/components - неверный размер компонента prizm-input-date-time-range.

### ISSUE THREAD

**Issue by if1t** [zyfra/Prizm#826]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

prizm-input-date-time-range

### Версия

Операционная ситема:

`Manjaro Linux`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v16.202
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 3.1.0
```

```
➜ npm ls @angular/core

 @prizm-ui/components@3.1.0
│ ├── @angular/core@16.2.8 deduped
│ ├─┬ @ng-web-apis/intersection-observer@3.1.3
│ │ └── @angular/core@16.2.8 deduped
│ ├─┬ @ng-web-apis/mutation-observer@3.0.1
│ │ └── @angular/core@16.2.8 deduped
│ ├─┬ @ng-web-apis/resize-observer@3.0.3
│ │ └── @angular/core@16.2.8 deduped
│ └─┬ @prizm-ui/i18n@3.1.0
│   └── @angular/core@16.2.8 deduped
```

### Скрин / Видео проблемы

![изображение](https://github.com/zyfra/Prizm/assets/93567572/d4601913-7eb1-4366-95c1-9fbdef9bc645)

### Описание проблемы

Добрый день! Столкнулся с проблемой изменения размера компонента prizm-input-date-time-range. На скриншоте представлен фрагмент следующего кода:
```
<prizm-input-date-time-range [formControl]="dateTime" size="l"></prizm-input-date-time-range>
<prizm-input-date-time-range [formControl]="dateTime" size="m"></prizm-input-date-time-range>
<prizm-input-date-time-range [formControl]="dateTime" size="s"></prizm-input-date-time-range>
```
Как видно из скриншота, компонент с указанным размером "s" имеет размер "l".

**Comment by if1t** [comment]
Помимо этого я увидел в консоли браузера ошибки при загрузке страницы, которые вызваны компонентом prizm-input-date-time-range.
![изображение](https://github.com/zyfra/Prizm/assets/93567572/8ac323af-3347-4065-b222-e3d43ef99900)
html:
```
<prizm-input-date-time-range [formControl]="dateTime" size="m"></prizm-input-date-time-range>
```

ts:
```
dateTime: FormControl = new FormControl(undefined);
```

**Comment by alexhawkins94** [comment]
inner input не имеет размера s, только l и m
