### ISSUE TITLE
[BUG] @prizm-ui/components/table — ошибки в примерах на stackblitz

### ISSUE THREAD

**Issue by elquid** [zyfra/Prizm#829]
### Библиотека

- [x] `@prizm-ui/components`

### Компонент

_@prizm-ui/components/table_

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/5610681/96e8cce4-5ab3-41ab-a6a3-8793bba78ebe)

### Воспроизведение проблемы

_Ссылка на stackblitz с минимальным воспроизведением_ https://p3watr--run.stackblitz.io/

### Описание проблемы

_Есть проблема следующего характера:_ примеры для таблиц на stackblitz не содержат `TABLE_EXAMPLE_DATA_1`, возникает ошибка.

_Шаги воспроизведения_:

1. Зайти по адресу [prizm](https://prizm.site/components/table).
2. Перейти по ссылке на stackblitz для первого примера.
3. Возникает ошибка, пример не отображается.

**Comment by imonogarov** [comment]
Для базового примера таблицы надо использовать общий stackblitz из переключалки версий, для примеров, где используются моки stackblitz временно отключен.
