### ISSUE TITLE
[Feature] @prizm-ui/components - Фокусируемый hint

### ISSUE THREAD

**Issue by algashev123zyfra** [zyfra/Prizm#830]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

PrizmHint

### Версия

Операционная сиcтема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

NodeJS:

```
➜ node --version
v14.21.3
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components: "1.5.0"
@angular/core: "^14.2.0"

```

### Проект в котором используется Prizm

- Ziiot
### Скрин / Видео проблемы

![Анимация](https://github.com/zyfra/Prizm/assets/142902249/097afcb8-ee3e-4a20-931f-75a016feec8b)

### Воспроизведение проблемы

_Ссылка на stackblitz с минимальным воспроизведением_
Пример:

https://stackblitz.com/edit/ngx-14-title-demo-xkfvji?file=src%2Fapp%2Fapp.component.html

### Описание проблемы

_Делаю задачу_
https://jira.zyfra.com/browse/PLATFORM01-31739
_Есть проблема следующего характера:_
В нашем случае в зависимости от того, нажата кнопка или нет, меняется текст хинта. Сейчас при быстром наведении и нажатии на кнопку отрисовывается подсказка с обновленным текстом, которая висит и не скрывается (см. гифку).
_Шаги воспроизведения_:

1. Создать кнопку с иконкой
2. Навесить на кнопку хинт
3. Поменять динамически текст хинта при клике на кнопку

**Comment by imonogarov** [comment]
@ZurabDev возможно пофикшено с #1704
