### ISSUE TITLE
[Feature] Добавить возможность кастомизации кнопок очистки (для к примеру выведения hint в формах)

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#855]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

Все компоненты из раздела Inputs

### Проект в котором используется Prizm

- СОУ

### Вопрос

Есть ли возможность добавить hint при наведении на кнопку "Очистить" в компонентах формы
![image](https://github.com/zyfra/Prizm/assets/17219726/c821e596-8f1b-4ce2-a8cf-a7ac354a837b)

**Comment by ZurabDev** [comment]
На данный момент, прикреплю задачи по которым это добавиться
