### ISSUE TITLE
[Question] Есть ли возможность использовать prizmHint в prizmIconButton?

### ISSUE THREAD

**Issue by AsyaSokolova** [zyfra/Prizm#861]
### Библиотека

- [ ] `@prizm-ui/components`

### Компонент

prizmIconButton

### Проект в котором используется Prizm

- СОУ

### Вопрос

При попытке использовать prizmHint в таком виде
![image](https://github.com/zyfra/Prizm/assets/17219726/41c82242-3e6a-4297-bcbc-6fce9a5ea4cd)
возникает ошибка:
Can't bind to 'prizmHint' since it isn't a known property of 'button'.

Есть ли возможность использовать prizmHint в prizmIconButton?

**Comment by ickisIckis** [comment]
Да, хинт работает с такими кнопками. Для этого необходимо импортировать PrizmHintModule в модуль, где планируется его использовать.
Вот тут можно посмотреть, как работает с обычными кнопками:
https://prizm.site/components/hint#base
 Для иконочных кнопок принцип работы тот же.

![image](https://github.com/zyfra/Prizm/assets/18642277/d42ba14a-0f19-4ca7-852e-ca5e8f7d56eb)
