### ISSUE TITLE
Перекраска компонентов (2 iteration)

### ISSUE THREAD

**Issue by ZurabDev** [zyfra/Prizm#862]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [x] #874
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

Готово
1) Button
2) Tabs
3) Swticher
В процессе
1) Toggle
2) Indicator
3) Card
4) Checkbox
5) Loader
6) Spinner
7) Progress bar - circle
8) Progress bar - line
9) Progress bar - segmented
10) Panel 
11) Scrollbar  

### Предложение

_Работаю в рамках задачи_

_Предлагаю сделать ..._

**Comment by ickisIckis** [comment]
#867 Индикатор

**Comment by ickisIckis** [comment]
#870 Spinner & Loader

**Comment by ickisIckis** [comment]
#876 Toggle

**Comment by ickisIckis** [comment]
#895 scrollbar

**Comment by ickisIckis** [comment]
#897 Card, Panel

**Comment by ickisIckis** [comment]
#902 Progress

**Comment by ickisIckis** [comment]
#871 checkbox
