### ISSUE TITLE
[FEATURE][Calendar] @prizm-ui/components - Выбор года и месяца перекрывает футер

### ISSUE THREAD

**Issue by MisterWind** [zyfra/Prizm#880]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

PrizmCalendarComponent

### Версия

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 2.3.0
```

### Проект в котором используется Prizm

- Редактор отчетов Datalink

### Скрин / Видео проблемы

_Скриншот.jpg_

### Воспроизведение проблемы

[https://stackblitz.com/edit/prizm-v1-overlay-cached-params-5acamb?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/prizm-v1-overlay-cached-params-5acamb?file=src%2Fapp%2Fapp.component.html)

### Описание проблемы

Создаю свой компонент на Prizm (range-календарь с бесконечностями)

_Шаги воспроизведения_:

1. Зайти на stackblitz, пример 2.
2. Увидеть футер под календарем "Hello there"
3. Развернуть месяц или год
4. Меню перекрывает футер, при этом не расстягиваясь в полную высоту

**Comment by ZurabDev** [comment]
На счет футер это часть компонента primitive-calendar а переключалка другой компонент
Если нужно создать календарь своей логикой можно отнаследоваться от календаря.
Сделали необходимые компоненты для этого доступными
