### ISSUE TITLE
[BUG][InputDateTime] @prizm-ui/components - Ручной ввод не учитывает min и max 

### ISSUE THREAD

**Issue by MisterWind** [zyfra/Prizm#883]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

PrizmInputLayoutDateTimeComponent

### Версия

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 1.6.0
```

### Проект в котором используется Prizm

- Редактор отчетов Datalink

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/23579119/5c6f4f1b-3d66-40cd-8d7a-27140206ef40)

https://github.com/zyfra/Prizm/assets/23579119/51638e63-ad40-4fe8-87a7-18d5565c047a

### Описание проблемы

При ручном вводе я добавил проверку на min и max календаря, сбрасывая дату до min / max, однако при сбросе ручной ввод не изменяется.

Просьба добавить проверку при передаче нового значения и обновление ручного ввода.

**Comment by ickisIckis** [comment]
https://github.com/zyfra/Prizm/pull/1629
