### ISSUE TITLE
[BUG][PrizmInputLayout] @prizm-ui/components - Ошибки в консоли 

### ISSUE THREAD

**Issue by katkovergina** [zyfra/Prizm#909]
### Библиотека

- [x] `@prizm-ui/components`

### Компонент

PrizmInputLayout

### Dependencies:

```
"@angular/animations": "^14.2.0",
    "@angular/cdk": "^14.2.0",
    "@angular/common": "^14.2.0",
    "@angular/compiler": "^14.2.0",
    "@angular/core": "^14.2.0",
    "@angular/forms": "^14.2.0",
    "@angular/material": "^14.2.7",
    "@angular/platform-browser": "^14.2.0",
    "@angular/platform-browser-dynamic": "^14.2.0",
    "@angular/router": "^14.2.0",
...

"@prizm-ui/components": "^1.7.0",
    "@prizm-ui/core": "^1.7.0",
    "@prizm-ui/helpers": "^1.7.0",
    "@prizm-ui/i18n": "^1.7.0",
    "@prizm-ui/icons": "^1.7.0",
    "@prizm-ui/theme": "^1.7.0",
    "@taiga-ui/cdk": "^3.15.0",

```

### Проект в котором используется Prizm

- Энергоконтроль

### Скрин 

![image](https://github.com/zyfra/Prizm/assets/51058477/7ce5ca37-1213-44d1-8dc7-7a760951c653)

### Описание проблемы

Если на странице есть форма `form` с `input`, у которого `type="number"`, этот `input` обернут в `prizm-input-layout`, то при попытке перейти в эту форму, страница зависает в состоянии загрузки и в консоль выводятся ошибки, количество которых постоянно растет. 
Воспроизводится только в таком сочетании: 

```
              <prizm-input-layout [outer]="true" label="label">
                <input prizmInput type="number" formControlName="formControlName" placeholder="Введите значение" />
              </prizm-input-layout>

```
если оставить один `input`, у которого `type="number"`, но без обертки в `prizm-input-layout`  ИЛИ  у  `input` убрать `type="number"` и оставить обертку `prizm-input-layout`, то проблема не воспроизводится.

**Comment by ickisIckis** [comment]
Начиная с версии 3.2.0(1.6.0 для Angular 14) необходимо импортировать PrizmInputNumberModule отдельно. Ранее он был доступен через PrizmInputTextModule.
Начиная с версии 3.5.0 будет доступен импорт stand alone компонента для этого контрола, импорт модуля станет depreceted.
