### ISSUE TITLE
[Question] change start y-line

### ISSUE THREAD

**Issue by if1t** [zyfra/Prizm#922]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_Название компонента или группы компонентов_

### Версия

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

`@prizm-ui/components 2.4.0`

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Проект в котором используется Prizm

- _Название проекта_

### Вопрос

Как поменять масштаб для оси Y, чтобы график отображал значения в интервале от 900 до 1200?
![изображение](https://github.com/zyfra/Prizm/assets/93567572/16247e55-4685-470e-b958-b4715d27a477)

**Comment by ickisIckis** [comment]
Для того, чтобы поменять максимальное и минимальное значение на графике, используйте свойства оси minLimit и maxLimit:
` 
  yAxis: {
    minLimit: 900,
    maxLimit: 1200,
  },
`
