### ISSUE TITLE
[Feature][Accordion][Breadcrumbs] Заменить цвета компонентов на v3

### ISSUE THREAD

**Issue by ickisIckis** [zyfra/Prizm#929]
### Библиотека

- [ ] `@prizm-ui/core`
- [X] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

[Accordion][Breadcrumbs]

### Предложение

 Заменить цвета компонентов на v3

**Comment by PrizmDS** [comment]
Ховеры убрать, такое поведение не заводилось.
