### ISSUE TITLE
[BUG] prizm/components - PrizmSidebar при создание отстутствует свойство footer

### ISSUE THREAD

**Issue by gustav2775** [zyfra/Prizm#94]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [X] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[PrizmSidebar](http://zds.zyfra.com/components/dialogs/sidebar)

### Версия

1.0.0-beta.26

### Скрин / Видео проблемы

[Screencast from 22.03.2023 12:18:55.webm](https://user-images.githubusercontent.com/71187404/226862973-234f2e9c-4942-462f-86a4-60d3e3b67fc3.webm)

![Screenshot from 2023-03-22 12-43-10](https://user-images.githubusercontent.com/71187404/226863827-6d9bd29d-8df2-41f2-85e6-0be6eff49b69.png)

### Описание проблемы

Отсутствует свойство footer при создание sidebar. Нет возможности передвть полиморфный контент или текст, а так же скрыть footer. 

Выдержа и документации к свойству footer.
"Footer template or button array (PrizmDialogButton) If pass empty string '', footer will not be showed"

_Шаги воспроизведения_:

1. Зайти по адресу [PrizmSidebar](http://zds.zyfra.com/components/dialogs/sidebar)
2. В footer установить текст, null, PolymorphContent

**Comment by AleksandrSibiakov** [comment]
Хочу воспользоваться возможностью и поделиться мыслями: в библиотеке есть блок [Widget](http://zds.zyfra.com/components/widget) - было бы здорово если бы он так же имел слот `footer` со схожей структурой\поведением.

Да и в целом, насколько вам кажется удачной идея использовать все тот же Widget для наполнения Sidebar? так мы получим схожее поведение и знакомые DOM структуры. Не надо будет беспокоиться что в одном месте футер\хедер работает так, а здесь иначе. (Так же вижу смысл в пере-использовании [Panel](http://zds.zyfra.com/components/panel) для дефолтного заголовка, как в sidebar, так и в том же Widget).

**Comment by ZurabDev** [comment]
<img width="954" alt="CleanShot 2023-03-31 at 05 32 41@2x" src="https://user-images.githubusercontent.com/75216044/229008296-995af74f-41cf-4e5d-93c4-54cdef9ce35c.png">

Исправлено. Будет в 28 версии
