### ISSUE TITLE
[Feature] prizm/components - закрытие SideBar при клике в области backdrop

### ISSUE THREAD

**Issue by badeevdm** [zyfra/Prizm#98]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`

### Компонент

[SideBar](http://zds.zyfra.com/components/dialogs/sidebar)

### Предложение

Возможно ли добавить поведение, при котором компонент SideBar будет закрываться при клике за областью компонента SIdeBar?

**Comment by ZurabDev** [comment]
<img width="730" alt="CleanShot 2023-03-23 at 12 11 35@2x" src="https://user-images.githubusercontent.com/75216044/227156122-b4dc31d5-b701-40d9-9090-0231b7051d7a.png">
Добавили dismisable свойство для закрытия при клике вне sidebar

**Comment by badeevdm** [comment]
Исправлено, спасибо!
