### ISSUE TITLE
[Question] изменение количества значений на графике

### ISSUE THREAD

**Issue by if1t** [zyfra/Prizm#981]
### Библиотека

- [ ] `@prizm-ui/core`
- [ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [x] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_Название компонента или группы компонентов_

### Версия

NodeJS:

```
➜ node --version
v16.13.0
```

Dependencies:

`@prizm-ui/components 2.5.0`

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 96.0.4664.110 (Официальная сборка), (x86_64)`

### Проект в котором используется Prizm

- _Название проекта_

### Вопрос

Если данных на графике  <prizm-charts-line> слишком много, то вся страница начинает подвисать. В связи с этим возникает вопрос: можно ли как-то усреднять данные на графике если их слишком много?

html:
```
<prizm-charts-line [options]="options" [data]="data"></prizm-charts-line>
```

ts:
```
options: Partial<PrizmChartsLineOptions> = {
   renderer: 'canvas',
    seriesField: 'code',
    yAxis: {
      title: {
        text: 'м/с',
        style: {
          fontSize: 10,
        },
      },
    },
    slider: {
      height: 30,
    },
    legend: {
      position: 'bottom-left',
    },
    autoFit: false,
}
```

**Comment by ickisIckis** [comment]
Именно такой функциональности найти в чартах не удалось, попробуйте решить проблему с усреднением значений на стороне своего сервера/платформы
